/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    HTTPValidationError,
    PricingResponse,
    SetPricingRequest,
} from '../models/index';

export interface DeletePricingV1PricingModelKeyDeleteRequest {
    modelKey: string;
    effectiveAt?: Date | null;
}

export interface GetPricingHistoryV1PricingModelKeyHistoryGetRequest {
    modelKey: string;
}

export interface GetPricingV1PricingModelKeyGetRequest {
    modelKey: string;
    asOf?: Date | null;
}

export interface ListPricingV1PricingGetRequest {
    skip?: number;
    limit?: number;
}

export interface SetPricingV1PricingPostRequest {
    setPricingRequest: SetPricingRequest;
}

/**
 * 
 */
export class PricingApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePricingV1PricingModelKeyDelete without sending the request
     */
    async deletePricingV1PricingModelKeyDeleteRequestOpts(requestParameters: DeletePricingV1PricingModelKeyDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelKey'] == null) {
            throw new runtime.RequiredError(
                'modelKey',
                'Required parameter "modelKey" was null or undefined when calling deletePricingV1PricingModelKeyDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['effectiveAt'] != null) {
            queryParameters['effective_at'] = (requestParameters['effectiveAt'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pricing/{model_key}`;
        urlPath = urlPath.replace('{model_key}', encodeURIComponent(String(requestParameters['modelKey'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete pricing entries for a model.
     * Delete Pricing
     */
    async deletePricingV1PricingModelKeyDeleteRaw(requestParameters: DeletePricingV1PricingModelKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePricingV1PricingModelKeyDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete pricing entries for a model.
     * Delete Pricing
     */
    async deletePricingV1PricingModelKeyDelete(requestParameters: DeletePricingV1PricingModelKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePricingV1PricingModelKeyDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPricingHistoryV1PricingModelKeyHistoryGet without sending the request
     */
    async getPricingHistoryV1PricingModelKeyHistoryGetRequestOpts(requestParameters: GetPricingHistoryV1PricingModelKeyHistoryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelKey'] == null) {
            throw new runtime.RequiredError(
                'modelKey',
                'Required parameter "modelKey" was null or undefined when calling getPricingHistoryV1PricingModelKeyHistoryGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pricing/{model_key}/history`;
        urlPath = urlPath.replace('{model_key}', encodeURIComponent(String(requestParameters['modelKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the full pricing history for a model.
     * Get Pricing History
     */
    async getPricingHistoryV1PricingModelKeyHistoryGetRaw(requestParameters: GetPricingHistoryV1PricingModelKeyHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PricingResponse>>> {
        const requestOptions = await this.getPricingHistoryV1PricingModelKeyHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Return the full pricing history for a model.
     * Get Pricing History
     */
    async getPricingHistoryV1PricingModelKeyHistoryGet(requestParameters: GetPricingHistoryV1PricingModelKeyHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PricingResponse>> {
        const response = await this.getPricingHistoryV1PricingModelKeyHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPricingV1PricingModelKeyGet without sending the request
     */
    async getPricingV1PricingModelKeyGetRequestOpts(requestParameters: GetPricingV1PricingModelKeyGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelKey'] == null) {
            throw new runtime.RequiredError(
                'modelKey',
                'Required parameter "modelKey" was null or undefined when calling getPricingV1PricingModelKeyGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['asOf'] != null) {
            queryParameters['as_of'] = (requestParameters['asOf'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pricing/{model_key}`;
        urlPath = urlPath.replace('{model_key}', encodeURIComponent(String(requestParameters['modelKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get pricing for a specific model as of a timestamp.
     * Get Pricing
     */
    async getPricingV1PricingModelKeyGetRaw(requestParameters: GetPricingV1PricingModelKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricingResponse>> {
        const requestOptions = await this.getPricingV1PricingModelKeyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get pricing for a specific model as of a timestamp.
     * Get Pricing
     */
    async getPricingV1PricingModelKeyGet(requestParameters: GetPricingV1PricingModelKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricingResponse> {
        const response = await this.getPricingV1PricingModelKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPricingV1PricingGet without sending the request
     */
    async listPricingV1PricingGetRequestOpts(requestParameters: ListPricingV1PricingGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pricing`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all model pricing.
     * List Pricing
     */
    async listPricingV1PricingGetRaw(requestParameters: ListPricingV1PricingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PricingResponse>>> {
        const requestOptions = await this.listPricingV1PricingGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List all model pricing.
     * List Pricing
     */
    async listPricingV1PricingGet(requestParameters: ListPricingV1PricingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PricingResponse>> {
        const response = await this.listPricingV1PricingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setPricingV1PricingPost without sending the request
     */
    async setPricingV1PricingPostRequestOpts(requestParameters: SetPricingV1PricingPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['setPricingRequest'] == null) {
            throw new runtime.RequiredError(
                'setPricingRequest',
                'Required parameter "setPricingRequest" was null or undefined when calling setPricingV1PricingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/pricing`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['setPricingRequest'],
        };
    }

    /**
     * Set or update pricing for a model.
     * Set Pricing
     */
    async setPricingV1PricingPostRaw(requestParameters: SetPricingV1PricingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricingResponse>> {
        const requestOptions = await this.setPricingV1PricingPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Set or update pricing for a model.
     * Set Pricing
     */
    async setPricingV1PricingPost(requestParameters: SetPricingV1PricingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricingResponse> {
        const response = await this.setPricingV1PricingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
