/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    HTTPValidationError,
    UsageEntry,
} from '../models/index';

export interface ListUsageV1UsageGetRequest {
    startDate?: Date | null;
    endDate?: Date | null;
    userId?: string | null;
    skip?: number;
    limit?: number;
}

/**
 * 
 */
export class UsageApi extends runtime.BaseAPI {

    /**
     * Creates request options for listUsageV1UsageGet without sending the request
     */
    async listUsageV1UsageGetRequestOpts(requestParameters: ListUsageV1UsageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString();
        }

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/usage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List usage logs ordered by timestamp (most recent first).  Supports optional filters for time range and user. Paginated via skip/limit. Timestamps accept either ISO 8601 strings or Unix epoch seconds (numeric).
     * List Usage
     */
    async listUsageV1UsageGetRaw(requestParameters: ListUsageV1UsageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsageEntry>>> {
        const requestOptions = await this.listUsageV1UsageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List usage logs ordered by timestamp (most recent first).  Supports optional filters for time range and user. Paginated via skip/limit. Timestamps accept either ISO 8601 strings or Unix epoch seconds (numeric).
     * List Usage
     */
    async listUsageV1UsageGet(requestParameters: ListUsageV1UsageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsageEntry>> {
        const response = await this.listUsageV1UsageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
