/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AudioSpeechRequest,
    AudioSpeechRequestFromJSON,
    AudioSpeechRequestToJSON,
} from '../models/AudioSpeechRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateSpeechV1AudioSpeechPostRequest {
    audioSpeechRequest: AudioSpeechRequest;
}

export interface CreateTranscriptionV1AudioTranscriptionsPostRequest {
    file: string;
    model: string;
    language?: string | null;
    prompt?: string | null;
    responseFormat?: string | null;
    temperature?: number | null;
    user?: string | null;
}

/**
 * 
 */
export class AudioApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSpeechV1AudioSpeechPost without sending the request
     */
    async createSpeechV1AudioSpeechPostRequestOpts(requestParameters: CreateSpeechV1AudioSpeechPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['audioSpeechRequest'] == null) {
            throw new runtime.RequiredError(
                'audioSpeechRequest',
                'Required parameter "audioSpeechRequest" was null or undefined when calling createSpeechV1AudioSpeechPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/audio/speech`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AudioSpeechRequestToJSON(requestParameters['audioSpeechRequest']),
        };
    }

    /**
     * OpenAI-compatible audio speech (TTS) endpoint.  Authentication modes: - Master key + user field: Use specified user (must exist) - API key + user field: Use specified user (must exist) - API key without user field: Use virtual user created with API key
     * Create Speech
     */
    async createSpeechV1AudioSpeechPostRaw(requestParameters: CreateSpeechV1AudioSpeechPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createSpeechV1AudioSpeechPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * OpenAI-compatible audio speech (TTS) endpoint.  Authentication modes: - Master key + user field: Use specified user (must exist) - API key + user field: Use specified user (must exist) - API key without user field: Use virtual user created with API key
     * Create Speech
     */
    async createSpeechV1AudioSpeechPost(requestParameters: CreateSpeechV1AudioSpeechPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSpeechV1AudioSpeechPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTranscriptionV1AudioTranscriptionsPost without sending the request
     */
    async createTranscriptionV1AudioTranscriptionsPostRequestOpts(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling createTranscriptionV1AudioTranscriptionsPost().'
            );
        }

        if (requestParameters['model'] == null) {
            throw new runtime.RequiredError(
                'model',
                'Required parameter "model" was null or undefined when calling createTranscriptionV1AudioTranscriptionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['language'] != null) {
            formParams.append('language', requestParameters['language'] as any);
        }

        if (requestParameters['model'] != null) {
            formParams.append('model', requestParameters['model'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        if (requestParameters['responseFormat'] != null) {
            formParams.append('response_format', requestParameters['responseFormat'] as any);
        }

        if (requestParameters['temperature'] != null) {
            formParams.append('temperature', requestParameters['temperature'] as any);
        }

        if (requestParameters['user'] != null) {
            formParams.append('user', requestParameters['user'] as any);
        }


        let urlPath = `/v1/audio/transcriptions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * OpenAI-compatible audio transcription endpoint.  Authentication modes: - Master key + user field: Use specified user (must exist) - API key + user field: Use specified user (must exist) - API key without user field: Use virtual user created with API key
     * Create Transcription
     */
    async createTranscriptionV1AudioTranscriptionsPostRaw(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createTranscriptionV1AudioTranscriptionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * OpenAI-compatible audio transcription endpoint.  Authentication modes: - Master key + user field: Use specified user (must exist) - API key + user field: Use specified user (must exist) - API key without user field: Use virtual user created with API key
     * Create Transcription
     */
    async createTranscriptionV1AudioTranscriptionsPost(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createTranscriptionV1AudioTranscriptionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
