/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type DeploymentBootstrap,
    DeploymentBootstrapFromJSON,
    DeploymentBootstrapToJSON,
} from '../models/DeploymentBootstrap.js';

/**
 * 
 */
export class BootstrapApi extends runtime.BaseAPI {

    /**
     * Creates request options for bootstrapGetBootstrap without sending the request
     */
    async bootstrapGetBootstrapRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/bootstrap`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the deployment context the dashboard shell renders from.  Public: the shell fetches this before it knows whether it can authenticate. That is also why ``sign_in_methods`` is answered here rather than behind a credential, and it publishes nothing an unauthenticated caller could not already learn by trying both credentials against the sign-in endpoint.  The database read is two primary-key lookups: the ``tenancy_bootstrap_user_id`` marker, and the identity it names, to answer whether *that* identity holds a password (#702). It runs only in standalone mode: a hybrid gateway has no session to describe, and ``get_db_if_needed`` hands it no session to read one from.
     * Get Bootstrap
     */
    async bootstrapGetBootstrapRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentBootstrap>> {
        const requestOptions = await this.bootstrapGetBootstrapRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentBootstrapFromJSON(jsonValue));
    }

    /**
     * Return the deployment context the dashboard shell renders from.  Public: the shell fetches this before it knows whether it can authenticate. That is also why ``sign_in_methods`` is answered here rather than behind a credential, and it publishes nothing an unauthenticated caller could not already learn by trying both credentials against the sign-in endpoint.  The database read is two primary-key lookups: the ``tenancy_bootstrap_user_id`` marker, and the identity it names, to answer whether *that* identity holds a password (#702). It runs only in standalone mode: a hybrid gateway has no session to describe, and ``get_db_if_needed`` hands it no session to read one from.
     * Get Bootstrap
     */
    async bootstrapGetBootstrap(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentBootstrap> {
        const response = await this.bootstrapGetBootstrapRaw(initOverrides);
        return await response.value();
    }

}
