/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError.js';
import {
    type PolicyCheckRequest,
    PolicyCheckRequestFromJSON,
    PolicyCheckRequestToJSON,
} from '../models/PolicyCheckRequest.js';
import {
    type PolicyCheckResponse,
    PolicyCheckResponseFromJSON,
    PolicyCheckResponseToJSON,
} from '../models/PolicyCheckResponse.js';

export interface HooksCheckPolicyRequest {
    policyCheckRequest: PolicyCheckRequest;
}

/**
 * 
 */
export class HooksApi extends runtime.BaseAPI {

    /**
     * Creates request options for hooksCheckPolicy without sending the request
     */
    async hooksCheckPolicyRequestOpts(requestParameters: HooksCheckPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['policyCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'policyCheckRequest',
                'Required parameter "policyCheckRequest" was null or undefined when calling hooksCheckPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/hooks/check`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolicyCheckRequestToJSON(requestParameters['policyCheckRequest']),
        };
    }

    /**
     * Evaluate a submitted policy against submitted evidence.  Authenticated with either an API key or the master key (the router-level gate), like ``POST /api/v1/usage/external-events``: this identifies who sent the request, not whether its evidence is true. `blocked` is set when a required gate\'s outcome is not `pass`/`not_applicable` (an unresolved gate never counts as a pass).
     * Check Policy
     */
    async hooksCheckPolicyRaw(requestParameters: HooksCheckPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolicyCheckResponse>> {
        const requestOptions = await this.hooksCheckPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyCheckResponseFromJSON(jsonValue));
    }

    /**
     * Evaluate a submitted policy against submitted evidence.  Authenticated with either an API key or the master key (the router-level gate), like ``POST /api/v1/usage/external-events``: this identifies who sent the request, not whether its evidence is true. `blocked` is set when a required gate\'s outcome is not `pass`/`not_applicable` (an unresolved gate never counts as a pass).
     * Check Policy
     */
    async hooksCheckPolicy(requestParameters: HooksCheckPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolicyCheckResponse> {
        const response = await this.hooksCheckPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
