/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ModelListResponse,
    ModelListResponseFromJSON,
    ModelListResponseToJSON,
} from '../models/ModelListResponse';
import {
    type ModelObject,
    ModelObjectFromJSON,
    ModelObjectToJSON,
} from '../models/ModelObject';

export interface GetModelV1ModelsModelIdGetRequest {
    modelId: string;
}

export interface ListModelsV1ModelsGetRequest {
    provider?: string | null;
}

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getModelV1ModelsModelIdGet without sending the request
     */
    async getModelV1ModelsModelIdGetRequestOpts(requestParameters: GetModelV1ModelsModelIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModelV1ModelsModelIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/models/{model_id}`;
        urlPath = urlPath.replace('{model_id}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get details for a specific model.
     * Get Model
     */
    async getModelV1ModelsModelIdGetRaw(requestParameters: GetModelV1ModelsModelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelObject>> {
        const requestOptions = await this.getModelV1ModelsModelIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelObjectFromJSON(jsonValue));
    }

    /**
     * Get details for a specific model.
     * Get Model
     */
    async getModelV1ModelsModelIdGet(requestParameters: GetModelV1ModelsModelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelObject> {
        const response = await this.getModelV1ModelsModelIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listModelsV1ModelsGet without sending the request
     */
    async listModelsV1ModelsGetRequestOpts(requestParameters: ListModelsV1ModelsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all available models.  Returns models auto-discovered from configured providers, enriched with pricing data from the model_pricing table when available. Models that only exist in the pricing table are also included for backward compatibility.
     * List Models
     */
    async listModelsV1ModelsGetRaw(requestParameters: ListModelsV1ModelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelListResponse>> {
        const requestOptions = await this.listModelsV1ModelsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelListResponseFromJSON(jsonValue));
    }

    /**
     * List all available models.  Returns models auto-discovered from configured providers, enriched with pricing data from the model_pricing table when available. Models that only exist in the pricing table are also included for backward compatibility.
     * List Models
     */
    async listModelsV1ModelsGet(requestParameters: ListModelsV1ModelsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelListResponse> {
        const response = await this.listModelsV1ModelsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
