/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ChatCompletionRequest,
    ChatCompletionRequestFromJSON,
    ChatCompletionRequestToJSON,
} from '../models/ChatCompletionRequest.js';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError.js';
import {
    type PlaygroundComparisonCreate,
    PlaygroundComparisonCreateFromJSON,
    PlaygroundComparisonCreateToJSON,
} from '../models/PlaygroundComparisonCreate.js';
import {
    type PlaygroundComparisonSummary,
    PlaygroundComparisonSummaryFromJSON,
    PlaygroundComparisonSummaryToJSON,
} from '../models/PlaygroundComparisonSummary.js';
import {
    type PlaygroundComparisonsPublic,
    PlaygroundComparisonsPublicFromJSON,
    PlaygroundComparisonsPublicToJSON,
} from '../models/PlaygroundComparisonsPublic.js';
import {
    type PlaygroundConsentPublic,
    PlaygroundConsentPublicFromJSON,
    PlaygroundConsentPublicToJSON,
} from '../models/PlaygroundConsentPublic.js';
import {
    type PlaygroundConsentUpdate,
    PlaygroundConsentUpdateFromJSON,
    PlaygroundConsentUpdateToJSON,
} from '../models/PlaygroundConsentUpdate.js';
import {
    type PlaygroundConversationCreate,
    PlaygroundConversationCreateFromJSON,
    PlaygroundConversationCreateToJSON,
} from '../models/PlaygroundConversationCreate.js';
import {
    type PlaygroundConversationSummary,
    PlaygroundConversationSummaryFromJSON,
    PlaygroundConversationSummaryToJSON,
} from '../models/PlaygroundConversationSummary.js';
import {
    type PlaygroundConversationsPublic,
    PlaygroundConversationsPublicFromJSON,
    PlaygroundConversationsPublicToJSON,
} from '../models/PlaygroundConversationsPublic.js';
import {
    type PlaygroundFavoriteModelsPublic,
    PlaygroundFavoriteModelsPublicFromJSON,
    PlaygroundFavoriteModelsPublicToJSON,
} from '../models/PlaygroundFavoriteModelsPublic.js';
import {
    type PlaygroundFavoriteModelsUpdate,
    PlaygroundFavoriteModelsUpdateFromJSON,
    PlaygroundFavoriteModelsUpdateToJSON,
} from '../models/PlaygroundFavoriteModelsUpdate.js';
import {
    type PlaygroundMessagesPublic,
    PlaygroundMessagesPublicFromJSON,
    PlaygroundMessagesPublicToJSON,
} from '../models/PlaygroundMessagesPublic.js';
import {
    type PlaygroundToolsResponse,
    PlaygroundToolsResponseFromJSON,
    PlaygroundToolsResponseToJSON,
} from '../models/PlaygroundToolsResponse.js';

export interface PlaygroundDeletePlaygroundComparisonRequest {
    comparisonId: string;
}

export interface PlaygroundDeletePlaygroundConversationRequest {
    conversationId: string;
}

export interface PlaygroundListPlaygroundComparisonsRequest {
    workspaceId?: string | null;
}

export interface PlaygroundListPlaygroundConversationsRequest {
    workspaceId?: string | null;
}

export interface PlaygroundPlaygroundChatCompletionsRequest {
    chatCompletionRequest: ChatCompletionRequest;
    workspaceId?: string | null;
}

export interface PlaygroundReadPlaygroundConversationMessagesRequest {
    conversationId: string;
}

export interface PlaygroundReadPlaygroundFavoriteModelsRequest {
    workspaceId?: string | null;
}

export interface PlaygroundReadPlaygroundToolsRequest {
    workspaceId?: string | null;
}

export interface PlaygroundReplacePlaygroundFavoriteModelsRequest {
    playgroundFavoriteModelsUpdate: PlaygroundFavoriteModelsUpdate;
    workspaceId?: string | null;
}

export interface PlaygroundSavePlaygroundComparisonRequest {
    playgroundComparisonCreate: PlaygroundComparisonCreate;
}

export interface PlaygroundSavePlaygroundConversationRequest {
    playgroundConversationCreate: PlaygroundConversationCreate;
}

export interface PlaygroundUpdatePlaygroundConsentRequest {
    playgroundConsentUpdate: PlaygroundConsentUpdate;
}

/**
 * 
 */
export class PlaygroundApi extends runtime.BaseAPI {

    /**
     * Creates request options for playgroundDeletePlaygroundComparison without sending the request
     */
    async playgroundDeletePlaygroundComparisonRequestOpts(requestParameters: PlaygroundDeletePlaygroundComparisonRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['comparisonId'] == null) {
            throw new runtime.RequiredError(
                'comparisonId',
                'Required parameter "comparisonId" was null or undefined when calling playgroundDeletePlaygroundComparison().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/comparisons/{comparison_id}`;
        urlPath = urlPath.replace('{comparison_id}', encodeURIComponent(String(requestParameters['comparisonId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one of the caller\'s saved comparisons.
     * Delete Playground Comparison
     */
    async playgroundDeletePlaygroundComparisonRaw(requestParameters: PlaygroundDeletePlaygroundComparisonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.playgroundDeletePlaygroundComparisonRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete one of the caller\'s saved comparisons.
     * Delete Playground Comparison
     */
    async playgroundDeletePlaygroundComparison(requestParameters: PlaygroundDeletePlaygroundComparisonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.playgroundDeletePlaygroundComparisonRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for playgroundDeletePlaygroundConversation without sending the request
     */
    async playgroundDeletePlaygroundConversationRequestOpts(requestParameters: PlaygroundDeletePlaygroundConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling playgroundDeletePlaygroundConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/conversations/{conversation_id}`;
        urlPath = urlPath.replace('{conversation_id}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one of the caller\'s saved transcripts, and its turns with it.
     * Delete Playground Conversation
     */
    async playgroundDeletePlaygroundConversationRaw(requestParameters: PlaygroundDeletePlaygroundConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.playgroundDeletePlaygroundConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete one of the caller\'s saved transcripts, and its turns with it.
     * Delete Playground Conversation
     */
    async playgroundDeletePlaygroundConversation(requestParameters: PlaygroundDeletePlaygroundConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.playgroundDeletePlaygroundConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for playgroundListPlaygroundComparisons without sending the request
     */
    async playgroundListPlaygroundComparisonsRequestOpts(requestParameters: PlaygroundListPlaygroundComparisonsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/comparisons`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The caller\'s own rated comparisons in one workspace, newest first.  Without the two answer bodies: the list shows a dozen rows and renders neither, and there is no detail endpoint because the page has no screen that reads one back. A comparison is a judgment that was recorded, not a transcript to resume.
     * List Playground Comparisons
     */
    async playgroundListPlaygroundComparisonsRaw(requestParameters: PlaygroundListPlaygroundComparisonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundComparisonsPublic>> {
        const requestOptions = await this.playgroundListPlaygroundComparisonsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundComparisonsPublicFromJSON(jsonValue));
    }

    /**
     * The caller\'s own rated comparisons in one workspace, newest first.  Without the two answer bodies: the list shows a dozen rows and renders neither, and there is no detail endpoint because the page has no screen that reads one back. A comparison is a judgment that was recorded, not a transcript to resume.
     * List Playground Comparisons
     */
    async playgroundListPlaygroundComparisons(requestParameters: PlaygroundListPlaygroundComparisonsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundComparisonsPublic> {
        const response = await this.playgroundListPlaygroundComparisonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundListPlaygroundConversations without sending the request
     */
    async playgroundListPlaygroundConversationsRequestOpts(requestParameters: PlaygroundListPlaygroundConversationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/conversations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The caller\'s own saved transcripts in one workspace, newest first.  Not gated on consent: withdrawing it stops new saves, so a transcript saved while it was granted has to stay listable and deletable by its owner.
     * List Playground Conversations
     */
    async playgroundListPlaygroundConversationsRaw(requestParameters: PlaygroundListPlaygroundConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundConversationsPublic>> {
        const requestOptions = await this.playgroundListPlaygroundConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundConversationsPublicFromJSON(jsonValue));
    }

    /**
     * The caller\'s own saved transcripts in one workspace, newest first.  Not gated on consent: withdrawing it stops new saves, so a transcript saved while it was granted has to stay listable and deletable by its owner.
     * List Playground Conversations
     */
    async playgroundListPlaygroundConversations(requestParameters: PlaygroundListPlaygroundConversationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundConversationsPublic> {
        const response = await this.playgroundListPlaygroundConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundPlaygroundChatCompletions without sending the request
     */
    async playgroundPlaygroundChatCompletionsRequestOpts(requestParameters: PlaygroundPlaygroundChatCompletionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatCompletionRequest'] == null) {
            throw new runtime.RequiredError(
                'chatCompletionRequest',
                'Required parameter "chatCompletionRequest" was null or undefined when calling playgroundPlaygroundChatCompletions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/chat/completions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatCompletionRequestToJSON(requestParameters['chatCompletionRequest']),
        };
    }

    /**
     * Run one chat completion for the signed-in caller.  Streaming and non-streaming both, identically to ``POST /api/v1/chat/completions``: this resolves the principal and then calls the very same handler. The request is billed to the caller\'s own attribution user in the workspace they named (or their organization\'s default), against that user\'s budget, and writes the ordinary usage row with no ``api_key_id``, because there was no key.  The body is ``ChatCompletionRequest`` unchanged, so the page sends the same request an SDK would and a model, tool or parameter the gateway gains is available here the day it lands. The workspace rides in the query string rather than in the body for that reason: a field added to the body would also have to be added to the pipeline\'s strip list, and a gateway-internal field that is not stripped is forwarded to the provider as a call kwarg.  ``user`` in the body is the one field the pipeline will not read here: spend binds to the session\'s own attribution user, derived and never accepted.  On a hosted control plane there is no local pipeline to call, so the same principal is forwarded to the data-plane gateway instead (:func:`_dispatch_to_data_plane`). The request and the response are the same either way.
     * Playground Chat Completions
     */
    async playgroundPlaygroundChatCompletionsRaw(requestParameters: PlaygroundPlaygroundChatCompletionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.playgroundPlaygroundChatCompletionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run one chat completion for the signed-in caller.  Streaming and non-streaming both, identically to ``POST /api/v1/chat/completions``: this resolves the principal and then calls the very same handler. The request is billed to the caller\'s own attribution user in the workspace they named (or their organization\'s default), against that user\'s budget, and writes the ordinary usage row with no ``api_key_id``, because there was no key.  The body is ``ChatCompletionRequest`` unchanged, so the page sends the same request an SDK would and a model, tool or parameter the gateway gains is available here the day it lands. The workspace rides in the query string rather than in the body for that reason: a field added to the body would also have to be added to the pipeline\'s strip list, and a gateway-internal field that is not stripped is forwarded to the provider as a call kwarg.  ``user`` in the body is the one field the pipeline will not read here: spend binds to the session\'s own attribution user, derived and never accepted.  On a hosted control plane there is no local pipeline to call, so the same principal is forwarded to the data-plane gateway instead (:func:`_dispatch_to_data_plane`). The request and the response are the same either way.
     * Playground Chat Completions
     */
    async playgroundPlaygroundChatCompletions(requestParameters: PlaygroundPlaygroundChatCompletionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.playgroundPlaygroundChatCompletionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundReadPlaygroundConsent without sending the request
     */
    async playgroundReadPlaygroundConsentRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/consent`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * What the caller has agreed the Playground may store.  Both flags false for a caller who has never answered, and nothing is written: the page asks at the moment it needs the grant, so recording an answer on a page load would record one nobody gave.
     * Read Playground Consent
     */
    async playgroundReadPlaygroundConsentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundConsentPublic>> {
        const requestOptions = await this.playgroundReadPlaygroundConsentRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundConsentPublicFromJSON(jsonValue));
    }

    /**
     * What the caller has agreed the Playground may store.  Both flags false for a caller who has never answered, and nothing is written: the page asks at the moment it needs the grant, so recording an answer on a page load would record one nobody gave.
     * Read Playground Consent
     */
    async playgroundReadPlaygroundConsent(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundConsentPublic> {
        const response = await this.playgroundReadPlaygroundConsentRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundReadPlaygroundConversationMessages without sending the request
     */
    async playgroundReadPlaygroundConversationMessagesRequestOpts(requestParameters: PlaygroundReadPlaygroundConversationMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling playgroundReadPlaygroundConversationMessages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/conversations/{conversation_id}/messages`;
        urlPath = urlPath.replace('{conversation_id}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One saved transcript\'s turns, in order.  404 for a transcript belonging to somebody else, the same answer an unknown id gets: the owner predicate is in the query, so the two are indistinguishable from here. An empty transcript is not a state a save can produce (the request requires at least one turn), so no rows means no row for this caller.
     * Read Playground Conversation Messages
     */
    async playgroundReadPlaygroundConversationMessagesRaw(requestParameters: PlaygroundReadPlaygroundConversationMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundMessagesPublic>> {
        const requestOptions = await this.playgroundReadPlaygroundConversationMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundMessagesPublicFromJSON(jsonValue));
    }

    /**
     * One saved transcript\'s turns, in order.  404 for a transcript belonging to somebody else, the same answer an unknown id gets: the owner predicate is in the query, so the two are indistinguishable from here. An empty transcript is not a state a save can produce (the request requires at least one turn), so no rows means no row for this caller.
     * Read Playground Conversation Messages
     */
    async playgroundReadPlaygroundConversationMessages(requestParameters: PlaygroundReadPlaygroundConversationMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundMessagesPublic> {
        const response = await this.playgroundReadPlaygroundConversationMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundReadPlaygroundFavoriteModels without sending the request
     */
    async playgroundReadPlaygroundFavoriteModelsRequestOpts(requestParameters: PlaygroundReadPlaygroundFavoriteModelsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/favorite-models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The caller\'s pinned model keys in one workspace, in pinned order.  Stored rather than kept in the browser, so a pin follows the person to their other devices; that is what the hosted original did and what makes the Favorites group in every picker worth having.
     * Read Playground Favorite Models
     */
    async playgroundReadPlaygroundFavoriteModelsRaw(requestParameters: PlaygroundReadPlaygroundFavoriteModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundFavoriteModelsPublic>> {
        const requestOptions = await this.playgroundReadPlaygroundFavoriteModelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundFavoriteModelsPublicFromJSON(jsonValue));
    }

    /**
     * The caller\'s pinned model keys in one workspace, in pinned order.  Stored rather than kept in the browser, so a pin follows the person to their other devices; that is what the hosted original did and what makes the Favorites group in every picker worth having.
     * Read Playground Favorite Models
     */
    async playgroundReadPlaygroundFavoriteModels(requestParameters: PlaygroundReadPlaygroundFavoriteModelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundFavoriteModelsPublic> {
        const response = await this.playgroundReadPlaygroundFavoriteModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundReadPlaygroundTools without sending the request
     */
    async playgroundReadPlaygroundToolsRequestOpts(requestParameters: PlaygroundReadPlaygroundToolsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/tools`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The gateway-run tools the caller\'s workspace may attach to a message.  One read rather than the three the dashboard would otherwise make (the deployment\'s tool settings, the workspace\'s web-search row, its code-execution row), because the answer is a composition of them in a fixed direction: the deployment decides whether a tool exists and the workspace may only narrow that. Composing it here is what keeps the menu from offering something the request path would refuse.
     * Read Playground Tools
     */
    async playgroundReadPlaygroundToolsRaw(requestParameters: PlaygroundReadPlaygroundToolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundToolsResponse>> {
        const requestOptions = await this.playgroundReadPlaygroundToolsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundToolsResponseFromJSON(jsonValue));
    }

    /**
     * The gateway-run tools the caller\'s workspace may attach to a message.  One read rather than the three the dashboard would otherwise make (the deployment\'s tool settings, the workspace\'s web-search row, its code-execution row), because the answer is a composition of them in a fixed direction: the deployment decides whether a tool exists and the workspace may only narrow that. Composing it here is what keeps the menu from offering something the request path would refuse.
     * Read Playground Tools
     */
    async playgroundReadPlaygroundTools(requestParameters: PlaygroundReadPlaygroundToolsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundToolsResponse> {
        const response = await this.playgroundReadPlaygroundToolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundReplacePlaygroundFavoriteModels without sending the request
     */
    async playgroundReplacePlaygroundFavoriteModelsRequestOpts(requestParameters: PlaygroundReplacePlaygroundFavoriteModelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playgroundFavoriteModelsUpdate'] == null) {
            throw new runtime.RequiredError(
                'playgroundFavoriteModelsUpdate',
                'Required parameter "playgroundFavoriteModelsUpdate" was null or undefined when calling playgroundReplacePlaygroundFavoriteModels().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/favorite-models`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlaygroundFavoriteModelsUpdateToJSON(requestParameters['playgroundFavoriteModelsUpdate']),
        };
    }

    /**
     * Replace the caller\'s pin list for one workspace.  A replace rather than a toggle, because the order is part of the value and the client already holds the list it is rendering. Two tabs racing therefore resolve to one of the two lists rather than to an interleaving neither of them showed. Model keys are not validated against the catalog: a pinned model that leaves the catalog simply stops appearing in the picker, and refusing the write would make a stale pin unremovable.
     * Replace Playground Favorite Models
     */
    async playgroundReplacePlaygroundFavoriteModelsRaw(requestParameters: PlaygroundReplacePlaygroundFavoriteModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundFavoriteModelsPublic>> {
        const requestOptions = await this.playgroundReplacePlaygroundFavoriteModelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundFavoriteModelsPublicFromJSON(jsonValue));
    }

    /**
     * Replace the caller\'s pin list for one workspace.  A replace rather than a toggle, because the order is part of the value and the client already holds the list it is rendering. Two tabs racing therefore resolve to one of the two lists rather than to an interleaving neither of them showed. Model keys are not validated against the catalog: a pinned model that leaves the catalog simply stops appearing in the picker, and refusing the write would make a stale pin unremovable.
     * Replace Playground Favorite Models
     */
    async playgroundReplacePlaygroundFavoriteModels(requestParameters: PlaygroundReplacePlaygroundFavoriteModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundFavoriteModelsPublic> {
        const response = await this.playgroundReplacePlaygroundFavoriteModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundSavePlaygroundComparison without sending the request
     */
    async playgroundSavePlaygroundComparisonRequestOpts(requestParameters: PlaygroundSavePlaygroundComparisonRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playgroundComparisonCreate'] == null) {
            throw new runtime.RequiredError(
                'playgroundComparisonCreate',
                'Required parameter "playgroundComparisonCreate" was null or undefined when calling playgroundSavePlaygroundComparison().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/comparisons`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaygroundComparisonCreateToJSON(requestParameters['playgroundComparisonCreate']),
        };
    }

    /**
     * Record which of two models answered a question better.  403 when comparison retention has not been granted; this is the flag with the wider disclosure, because the row keeps both models\' full answers.
     * Save Playground Comparison
     */
    async playgroundSavePlaygroundComparisonRaw(requestParameters: PlaygroundSavePlaygroundComparisonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundComparisonSummary>> {
        const requestOptions = await this.playgroundSavePlaygroundComparisonRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundComparisonSummaryFromJSON(jsonValue));
    }

    /**
     * Record which of two models answered a question better.  403 when comparison retention has not been granted; this is the flag with the wider disclosure, because the row keeps both models\' full answers.
     * Save Playground Comparison
     */
    async playgroundSavePlaygroundComparison(requestParameters: PlaygroundSavePlaygroundComparisonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundComparisonSummary> {
        const response = await this.playgroundSavePlaygroundComparisonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundSavePlaygroundConversation without sending the request
     */
    async playgroundSavePlaygroundConversationRequestOpts(requestParameters: PlaygroundSavePlaygroundConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playgroundConversationCreate'] == null) {
            throw new runtime.RequiredError(
                'playgroundConversationCreate',
                'Required parameter "playgroundConversationCreate" was null or undefined when calling playgroundSavePlaygroundConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaygroundConversationCreateToJSON(requestParameters['playgroundConversationCreate']),
        };
    }

    /**
     * Save one transcript whole, for the caller, in a workspace they belong to.  403 when content retention has not been granted. The page asks first, so reaching that is a client that skipped the prompt: a consent gate enforced only in the browser is not a consent gate.
     * Save Playground Conversation
     */
    async playgroundSavePlaygroundConversationRaw(requestParameters: PlaygroundSavePlaygroundConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundConversationSummary>> {
        const requestOptions = await this.playgroundSavePlaygroundConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundConversationSummaryFromJSON(jsonValue));
    }

    /**
     * Save one transcript whole, for the caller, in a workspace they belong to.  403 when content retention has not been granted. The page asks first, so reaching that is a client that skipped the prompt: a consent gate enforced only in the browser is not a consent gate.
     * Save Playground Conversation
     */
    async playgroundSavePlaygroundConversation(requestParameters: PlaygroundSavePlaygroundConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundConversationSummary> {
        const response = await this.playgroundSavePlaygroundConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playgroundUpdatePlaygroundConsent without sending the request
     */
    async playgroundUpdatePlaygroundConsentRequestOpts(requestParameters: PlaygroundUpdatePlaygroundConsentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playgroundConsentUpdate'] == null) {
            throw new runtime.RequiredError(
                'playgroundConsentUpdate',
                'Required parameter "playgroundConsentUpdate" was null or undefined when calling playgroundUpdatePlaygroundConsent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/playground/consent`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlaygroundConsentUpdateToJSON(requestParameters['playgroundConsentUpdate']),
        };
    }

    /**
     * Grant or withdraw content retention, one flag at a time.  An omitted flag is left as it was. Withdrawing blocks new saves and deletes nothing: what was stored with consent stays until its owner deletes it, which is what keeps a withdrawal from being a destructive action nobody asked for.
     * Update Playground Consent
     */
    async playgroundUpdatePlaygroundConsentRaw(requestParameters: PlaygroundUpdatePlaygroundConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaygroundConsentPublic>> {
        const requestOptions = await this.playgroundUpdatePlaygroundConsentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaygroundConsentPublicFromJSON(jsonValue));
    }

    /**
     * Grant or withdraw content retention, one flag at a time.  An omitted flag is left as it was. Withdrawing blocks new saves and deletes nothing: what was stored with consent stays until its owner deletes it, which is what keeps a withdrawal from being a destructive action nobody asked for.
     * Update Playground Consent
     */
    async playgroundUpdatePlaygroundConsent(requestParameters: PlaygroundUpdatePlaygroundConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaygroundConsentPublic> {
        const response = await this.playgroundUpdatePlaygroundConsentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
