/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ResponsesRequest,
    ResponsesRequestFromJSON,
    ResponsesRequestToJSON,
} from '../models/ResponsesRequest';

export interface CreateResponseV1ResponsesPostRequest {
    responsesRequest: ResponsesRequest;
}

/**
 * 
 */
export class ResponsesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createResponseV1ResponsesPost without sending the request
     */
    async createResponseV1ResponsesPostRequestOpts(requestParameters: CreateResponseV1ResponsesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['responsesRequest'] == null) {
            throw new runtime.RequiredError(
                'responsesRequest',
                'Required parameter "responsesRequest" was null or undefined when calling createResponseV1ResponsesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/responses`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResponsesRequestToJSON(requestParameters['responsesRequest']),
        };
    }

    /**
     * OpenAI-compatible Responses endpoint.  Supports MCP tool-use loops, sandboxed code execution, and SearXNG web_search in both standalone mode and platform mode. Platform-mode requests resolve credentials via the platform service and (for non-tool-loop requests) get multi-attempt fallback across the resolved route. Tool-loop requests collapse to a single attempt — once ``on_first_response`` lock-in plumbing lands across the codebase, a follow-up will enable pre-lock-in fallback for tool-loop requests too.
     * Create Response
     */
    async createResponseV1ResponsesPostRaw(requestParameters: CreateResponseV1ResponsesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createResponseV1ResponsesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * OpenAI-compatible Responses endpoint.  Supports MCP tool-use loops, sandboxed code execution, and SearXNG web_search in both standalone mode and platform mode. Platform-mode requests resolve credentials via the platform service and (for non-tool-loop requests) get multi-attempt fallback across the resolved route. Tool-loop requests collapse to a single attempt — once ``on_first_response`` lock-in plumbing lands across the codebase, a follow-up will enable pre-lock-in fallback for tool-loop requests too.
     * Create Response
     */
    async createResponseV1ResponsesPost(requestParameters: CreateResponseV1ResponsesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createResponseV1ResponsesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
