/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CreateSearchToolRequest,
    CreateSearchToolRequestFromJSON,
    CreateSearchToolRequestToJSON,
} from '../models/CreateSearchToolRequest.js';
import {
    type CreatedSearchToolSchema,
    CreatedSearchToolSchemaFromJSON,
    CreatedSearchToolSchemaToJSON,
} from '../models/CreatedSearchToolSchema.js';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError.js';
import {
    type ReencryptSearchToolsResponse,
    ReencryptSearchToolsResponseFromJSON,
    ReencryptSearchToolsResponseToJSON,
} from '../models/ReencryptSearchToolsResponse.js';
import {
    type SearchProviderSchema,
    SearchProviderSchemaFromJSON,
    SearchProviderSchemaToJSON,
} from '../models/SearchProviderSchema.js';
import {
    type SearchToolTestRequest,
    SearchToolTestRequestFromJSON,
    SearchToolTestRequestToJSON,
} from '../models/SearchToolTestRequest.js';
import {
    type SearchToolTestResponse,
    SearchToolTestResponseFromJSON,
    SearchToolTestResponseToJSON,
} from '../models/SearchToolTestResponse.js';
import {
    type SearchToolsResponse,
    SearchToolsResponseFromJSON,
    SearchToolsResponseToJSON,
} from '../models/SearchToolsResponse.js';
import {
    type StoredSearchToolSchema,
    StoredSearchToolSchemaFromJSON,
    StoredSearchToolSchemaToJSON,
} from '../models/StoredSearchToolSchema.js';
import {
    type StoredSearchToolTestRequest,
    StoredSearchToolTestRequestFromJSON,
    StoredSearchToolTestRequestToJSON,
} from '../models/StoredSearchToolTestRequest.js';
import {
    type UpdateSearchToolRequest,
    UpdateSearchToolRequestFromJSON,
    UpdateSearchToolRequestToJSON,
} from '../models/UpdateSearchToolRequest.js';

export interface SearchToolsCreateSearchToolRequest {
    createSearchToolRequest: CreateSearchToolRequest;
}

export interface SearchToolsDeleteStoredSearchToolRequest {
    name: string;
}

export interface SearchToolsListAllSearchToolsRequest {
    kind?: SearchToolsListAllSearchToolsKindEnum;
}

export interface SearchToolsListSearchProvidersRequest {
    kind?: SearchToolsListSearchProvidersKindEnum;
}

export interface SearchToolsTestSearchToolRequest {
    name: string;
    storedSearchToolTestRequest: StoredSearchToolTestRequest;
}

export interface SearchToolsTestUnsavedSearchToolRequest {
    searchToolTestRequest: SearchToolTestRequest;
}

export interface SearchToolsUpdateSearchToolRequest {
    name: string;
    updateSearchToolRequest: UpdateSearchToolRequest;
}

/**
 * 
 */
export class SearchToolsApi extends runtime.BaseAPI {

    /**
     * Creates request options for searchToolsCreateSearchTool without sending the request
     */
    async searchToolsCreateSearchToolRequestOpts(requestParameters: SearchToolsCreateSearchToolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSearchToolRequest'] == null) {
            throw new runtime.RequiredError(
                'createSearchToolRequest',
                'Required parameter "createSearchToolRequest" was null or undefined when calling searchToolsCreateSearchTool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSearchToolRequestToJSON(requestParameters['createSearchToolRequest']),
        };
    }

    /**
     * Add a search or fetch instance at runtime. Storing an API key requires OTARI_SECRET_KEY.  Creating a second search instance, while the first is the in-loop default only because it is the only one, first sets ``web_search_default_tool`` to the first in the same commit, and says so in the response, so that adding an instance never turns in-loop search off. That runtime value wins over the configuration file until it is cleared.
     * Create Search Tool
     */
    async searchToolsCreateSearchToolRaw(requestParameters: SearchToolsCreateSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedSearchToolSchema>> {
        const requestOptions = await this.searchToolsCreateSearchToolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedSearchToolSchemaFromJSON(jsonValue));
    }

    /**
     * Add a search or fetch instance at runtime. Storing an API key requires OTARI_SECRET_KEY.  Creating a second search instance, while the first is the in-loop default only because it is the only one, first sets ``web_search_default_tool`` to the first in the same commit, and says so in the response, so that adding an instance never turns in-loop search off. That runtime value wins over the configuration file until it is cleared.
     * Create Search Tool
     */
    async searchToolsCreateSearchTool(requestParameters: SearchToolsCreateSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedSearchToolSchema> {
        const response = await this.searchToolsCreateSearchToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsDeleteStoredSearchTool without sending the request
     */
    async searchToolsDeleteStoredSearchToolRequestOpts(requestParameters: SearchToolsDeleteStoredSearchToolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling searchToolsDeleteStoredSearchTool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a stored search or fetch instance. A config-file one, or ``builtin_fetch``, cannot be deleted here.
     * Delete Stored Search Tool
     */
    async searchToolsDeleteStoredSearchToolRaw(requestParameters: SearchToolsDeleteStoredSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.searchToolsDeleteStoredSearchToolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a stored search or fetch instance. A config-file one, or ``builtin_fetch``, cannot be deleted here.
     * Delete Stored Search Tool
     */
    async searchToolsDeleteStoredSearchTool(requestParameters: SearchToolsDeleteStoredSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.searchToolsDeleteStoredSearchToolRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for searchToolsListAllSearchTools without sending the request
     */
    async searchToolsListAllSearchToolsRequestOpts(requestParameters: SearchToolsListAllSearchToolsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List every search instance ``POST /api/v1/search`` can name, or with ``?kind=fetch`` every fetch instance.  ``stored`` are the editable rows written through this API; ``config`` are the config-file entries, which are still honored and are reported so the operator can see the whole set, ``builtin_fetch`` first among the fetch instances. Keys are never returned, only ``last4``.
     * List All Search Tools
     */
    async searchToolsListAllSearchToolsRaw(requestParameters: SearchToolsListAllSearchToolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchToolsResponse>> {
        const requestOptions = await this.searchToolsListAllSearchToolsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchToolsResponseFromJSON(jsonValue));
    }

    /**
     * List every search instance ``POST /api/v1/search`` can name, or with ``?kind=fetch`` every fetch instance.  ``stored`` are the editable rows written through this API; ``config`` are the config-file entries, which are still honored and are reported so the operator can see the whole set, ``builtin_fetch`` first among the fetch instances. Keys are never returned, only ``last4``.
     * List All Search Tools
     */
    async searchToolsListAllSearchTools(requestParameters: SearchToolsListAllSearchToolsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchToolsResponse> {
        const response = await this.searchToolsListAllSearchToolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsListSearchProviders without sending the request
     */
    async searchToolsListSearchProvidersRequestOpts(requestParameters: SearchToolsListSearchProvidersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the providers a search or fetch tool may name, for the add-tool form.  The list comes from the metadata any-search and any-fetch publish, so a provider either library adds appears with no change to the gateway. Reports per provider whether an API key is required, what endpoint a tool inherits when it declares none, and the native options a tool may set. Providers that exist only for tests are left out, and so is the fetch provider ``builtin``, which only the implicit ``builtin_fetch`` tool uses.  What belongs to this deployment rather than to the libraries, its own tools on each provider and an endpoint a tool inherits from its settings, is shown only to a caller who operates the deployment: the tool settings reader withholds the same from anyone else.
     * List Search Providers
     */
    async searchToolsListSearchProvidersRaw(requestParameters: SearchToolsListSearchProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchProviderSchema>>> {
        const requestOptions = await this.searchToolsListSearchProvidersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchProviderSchemaFromJSON));
    }

    /**
     * List the providers a search or fetch tool may name, for the add-tool form.  The list comes from the metadata any-search and any-fetch publish, so a provider either library adds appears with no change to the gateway. Reports per provider whether an API key is required, what endpoint a tool inherits when it declares none, and the native options a tool may set. Providers that exist only for tests are left out, and so is the fetch provider ``builtin``, which only the implicit ``builtin_fetch`` tool uses.  What belongs to this deployment rather than to the libraries, its own tools on each provider and an endpoint a tool inherits from its settings, is shown only to a caller who operates the deployment: the tool settings reader withholds the same from anyone else.
     * List Search Providers
     */
    async searchToolsListSearchProviders(requestParameters: SearchToolsListSearchProvidersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchProviderSchema>> {
        const response = await this.searchToolsListSearchProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsReencryptStoredSearchToolKeys without sending the request
     */
    async searchToolsReencryptStoredSearchToolKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/reencrypt`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Re-encrypt stored search-tool keys with the primary OTARI_SECRET_KEY.  The search-tool half of the ``OTARI_SECRET_KEY`` rotation procedure; run it alongside ``POST /api/v1/provider-credentials/reencrypt``. Rows that cannot be decrypted are left untouched and must be recovered by replacing the affected tool\'s key.
     * Reencrypt Stored Search Tool Keys
     */
    async searchToolsReencryptStoredSearchToolKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReencryptSearchToolsResponse>> {
        const requestOptions = await this.searchToolsReencryptStoredSearchToolKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReencryptSearchToolsResponseFromJSON(jsonValue));
    }

    /**
     * Re-encrypt stored search-tool keys with the primary OTARI_SECRET_KEY.  The search-tool half of the ``OTARI_SECRET_KEY`` rotation procedure; run it alongside ``POST /api/v1/provider-credentials/reencrypt``. Rows that cannot be decrypted are left untouched and must be recovered by replacing the affected tool\'s key.
     * Reencrypt Stored Search Tool Keys
     */
    async searchToolsReencryptStoredSearchToolKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReencryptSearchToolsResponse> {
        const response = await this.searchToolsReencryptStoredSearchToolKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsTestSearchTool without sending the request
     */
    async searchToolsTestSearchToolRequestOpts(requestParameters: SearchToolsTestSearchToolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling searchToolsTestSearchTool().'
            );
        }

        if (requestParameters['storedSearchToolTestRequest'] == null) {
            throw new runtime.RequiredError(
                'storedSearchToolTestRequest',
                'Required parameter "storedSearchToolTestRequest" was null or undefined when calling searchToolsTestSearchTool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/{name}/test`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoredSearchToolTestRequestToJSON(requestParameters['storedSearchToolTestRequest']),
        };
    }

    /**
     * Test a configured or stored instance with one search or one fetch.  Takes ``query`` for a search instance or ``url`` for a fetch instance, and answers as ``POST /search-tools/test`` does. ``builtin_fetch`` has no test yet, and answers a 400.
     * Test Search Tool
     */
    async searchToolsTestSearchToolRaw(requestParameters: SearchToolsTestSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchToolTestResponse>> {
        const requestOptions = await this.searchToolsTestSearchToolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchToolTestResponseFromJSON(jsonValue));
    }

    /**
     * Test a configured or stored instance with one search or one fetch.  Takes ``query`` for a search instance or ``url`` for a fetch instance, and answers as ``POST /search-tools/test`` does. ``builtin_fetch`` has no test yet, and answers a 400.
     * Test Search Tool
     */
    async searchToolsTestSearchTool(requestParameters: SearchToolsTestSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchToolTestResponse> {
        const response = await this.searchToolsTestSearchToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsTestUnsavedSearchTool without sending the request
     */
    async searchToolsTestUnsavedSearchToolRequestOpts(requestParameters: SearchToolsTestUnsavedSearchToolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchToolTestRequest'] == null) {
            throw new runtime.RequiredError(
                'searchToolTestRequest',
                'Required parameter "searchToolTestRequest" was null or undefined when calling searchToolsTestUnsavedSearchTool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/test`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchToolTestRequestToJSON(requestParameters['searchToolTestRequest']),
        };
    }

    /**
     * Test an instance before saving it, with one search or one fetch.  Takes the create request\'s fields, held to the create\'s checks against the instances this worker has loaded, plus ``query`` for a search instance or ``url`` for a fetch instance. Answers whether the provider answered without an error, the error\'s tag when it did not, and how many hits or characters came back, never the results or the page.
     * Test Unsaved Search Tool
     */
    async searchToolsTestUnsavedSearchToolRaw(requestParameters: SearchToolsTestUnsavedSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchToolTestResponse>> {
        const requestOptions = await this.searchToolsTestUnsavedSearchToolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchToolTestResponseFromJSON(jsonValue));
    }

    /**
     * Test an instance before saving it, with one search or one fetch.  Takes the create request\'s fields, held to the create\'s checks against the instances this worker has loaded, plus ``query`` for a search instance or ``url`` for a fetch instance. Answers whether the provider answered without an error, the error\'s tag when it did not, and how many hits or characters came back, never the results or the page.
     * Test Unsaved Search Tool
     */
    async searchToolsTestUnsavedSearchTool(requestParameters: SearchToolsTestUnsavedSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchToolTestResponse> {
        const response = await this.searchToolsTestUnsavedSearchToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchToolsUpdateSearchTool without sending the request
     */
    async searchToolsUpdateSearchToolRequestOpts(requestParameters: SearchToolsUpdateSearchToolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling searchToolsUpdateSearchTool().'
            );
        }

        if (requestParameters['updateSearchToolRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSearchToolRequest',
                'Required parameter "updateSearchToolRequest" was null or undefined when calling searchToolsUpdateSearchTool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/search-tools/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSearchToolRequestToJSON(requestParameters['updateSearchToolRequest']),
        };
    }

    /**
     * Update a stored search or fetch instance. Omitted fields are left as-is; an explicit ``null`` clears them.  ``api_key`` follows the same rule: omit it to keep the stored key, send a new one to rotate, or send ``null`` to clear it (a keyless SearXNG backend). The row is locked ``FOR UPDATE`` so the ``expected_updated_at`` check and the write it guards are atomic. The tool as it will be after the update is validated, so a change that would leave it unusable (clearing the key of a provider that needs one) is refused rather than stored. Its options are checked against the provider\'s when the update sets them or changes the provider, and ``fetch_tool`` when the update sets it, so rotating the key of an instance stored before those rules never trips on them. ``kind`` cannot change, so an instance never moves between the search and fetch maps.
     * Update Search Tool
     */
    async searchToolsUpdateSearchToolRaw(requestParameters: SearchToolsUpdateSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredSearchToolSchema>> {
        const requestOptions = await this.searchToolsUpdateSearchToolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoredSearchToolSchemaFromJSON(jsonValue));
    }

    /**
     * Update a stored search or fetch instance. Omitted fields are left as-is; an explicit ``null`` clears them.  ``api_key`` follows the same rule: omit it to keep the stored key, send a new one to rotate, or send ``null`` to clear it (a keyless SearXNG backend). The row is locked ``FOR UPDATE`` so the ``expected_updated_at`` check and the write it guards are atomic. The tool as it will be after the update is validated, so a change that would leave it unusable (clearing the key of a provider that needs one) is refused rather than stored. Its options are checked against the provider\'s when the update sets them or changes the provider, and ``fetch_tool`` when the update sets it, so rotating the key of an instance stored before those rules never trips on them. ``kind`` cannot change, so an instance never moves between the search and fetch maps.
     * Update Search Tool
     */
    async searchToolsUpdateSearchTool(requestParameters: SearchToolsUpdateSearchToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredSearchToolSchema> {
        const response = await this.searchToolsUpdateSearchToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchToolsListAllSearchToolsKindEnum = {
    Search: 'search',
    Fetch: 'fetch'
} as const;
export type SearchToolsListAllSearchToolsKindEnum = typeof SearchToolsListAllSearchToolsKindEnum[keyof typeof SearchToolsListAllSearchToolsKindEnum];
/**
 * @export
 */
export const SearchToolsListSearchProvidersKindEnum = {
    Search: 'search',
    Fetch: 'fetch'
} as const;
export type SearchToolsListSearchProvidersKindEnum = typeof SearchToolsListSearchProvidersKindEnum[keyof typeof SearchToolsListSearchProvidersKindEnum];
