/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError.js';
import {
    type WorkspaceCodeExecutionPolicyPublic,
    WorkspaceCodeExecutionPolicyPublicFromJSON,
    WorkspaceCodeExecutionPolicyPublicToJSON,
} from '../models/WorkspaceCodeExecutionPolicyPublic.js';
import {
    type WorkspaceCodeExecutionPolicyUpdate,
    WorkspaceCodeExecutionPolicyUpdateFromJSON,
    WorkspaceCodeExecutionPolicyUpdateToJSON,
} from '../models/WorkspaceCodeExecutionPolicyUpdate.js';

export interface WorkspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequest {
    workspaceId: string;
}

export interface WorkspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequest {
    workspaceId: string;
}

export interface WorkspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequest {
    workspaceId: string;
    workspaceCodeExecutionPolicyUpdate: WorkspaceCodeExecutionPolicyUpdate;
}

/**
 * 
 */
export class WorkspaceCodeExecutionPolicyApi extends runtime.BaseAPI {

    /**
     * Creates request options for workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicy without sending the request
     */
    async workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequestOpts(requestParameters: WorkspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/workspaces/{workspace_id}/code-execution-policy`;
        urlPath = urlPath.replace('{workspace_id}', encodeURIComponent(String(requestParameters['workspaceId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Drop a workspace\'s policy, returning it to the deployment\'s behavior.  Idempotent: a workspace that has no policy is already in the state this asks for, so it answers with the unconfigured policy rather than a 404.
     * Clear Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRaw(requestParameters: WorkspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceCodeExecutionPolicyPublic>> {
        const requestOptions = await this.workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceCodeExecutionPolicyPublicFromJSON(jsonValue));
    }

    /**
     * Drop a workspace\'s policy, returning it to the deployment\'s behavior.  Idempotent: a workspace that has no policy is already in the state this asks for, so it answers with the unconfigured policy rather than a 404.
     * Clear Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicy(requestParameters: WorkspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceCodeExecutionPolicyPublic> {
        const response = await this.workspaceCodeExecutionPolicyClearWorkspaceCodeExecutionPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicy without sending the request
     */
    async workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequestOpts(requestParameters: WorkspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/workspaces/{workspace_id}/code-execution-policy`;
        urlPath = urlPath.replace('{workspace_id}', encodeURIComponent(String(requestParameters['workspaceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a workspace\'s code-execution policy.  Takes the same role as setting it (an organization owner/admin, or an owner/admin of this workspace), because the policy describes the workspace\'s security and billing posture rather than one member\'s allowance. A workspace with no policy answers with the unconfigured one (``configured: false``), which is the deployment\'s own behavior described in the same shape rather than a 404.
     * Get Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRaw(requestParameters: WorkspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceCodeExecutionPolicyPublic>> {
        const requestOptions = await this.workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceCodeExecutionPolicyPublicFromJSON(jsonValue));
    }

    /**
     * Read a workspace\'s code-execution policy.  Takes the same role as setting it (an organization owner/admin, or an owner/admin of this workspace), because the policy describes the workspace\'s security and billing posture rather than one member\'s allowance. A workspace with no policy answers with the unconfigured one (``configured: false``), which is the deployment\'s own behavior described in the same shape rather than a 404.
     * Get Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicy(requestParameters: WorkspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceCodeExecutionPolicyPublic> {
        const response = await this.workspaceCodeExecutionPolicyGetWorkspaceCodeExecutionPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicy without sending the request
     */
    async workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequestOpts(requestParameters: WorkspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicy().'
            );
        }

        if (requestParameters['workspaceCodeExecutionPolicyUpdate'] == null) {
            throw new runtime.RequiredError(
                'workspaceCodeExecutionPolicyUpdate',
                'Required parameter "workspaceCodeExecutionPolicyUpdate" was null or undefined when calling workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // XApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Otari-Key"] = await this.configuration.apiKey("Otari-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/workspaces/{workspace_id}/code-execution-policy`;
        urlPath = urlPath.replace('{workspace_id}', encodeURIComponent(String(requestParameters['workspaceId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceCodeExecutionPolicyUpdateToJSON(requestParameters['workspaceCodeExecutionPolicyUpdate']),
        };
    }

    /**
     * Set a workspace\'s code-execution policy, replacing any existing one.  An organization owner/admin, or an owner/admin of this workspace, may write it. The policy can only narrow what the deployment permits: turning code execution off for the workspace, lowering the loop and execution ceilings, and removing tool kinds from what the sandbox backend serves. It never turns a sandbox the deployment has not configured on, and ``image`` may only name one the operator curated (``allowed_images`` on the response reports the set); anything else is refused with 400.
     * Set Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRaw(requestParameters: WorkspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceCodeExecutionPolicyPublic>> {
        const requestOptions = await this.workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceCodeExecutionPolicyPublicFromJSON(jsonValue));
    }

    /**
     * Set a workspace\'s code-execution policy, replacing any existing one.  An organization owner/admin, or an owner/admin of this workspace, may write it. The policy can only narrow what the deployment permits: turning code execution off for the workspace, lowering the loop and execution ceilings, and removing tool kinds from what the sandbox backend serves. It never turns a sandbox the deployment has not configured on, and ``image`` may only name one the operator curated (``allowed_images`` on the response reports the set); anything else is refused with 400.
     * Set Workspace Code Execution Policy
     */
    async workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicy(requestParameters: WorkspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceCodeExecutionPolicyPublic> {
        const response = await this.workspaceCodeExecutionPolicySetWorkspaceCodeExecutionPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
