/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActiveOrganizationUpdateRequest
 */
export interface ActiveOrganizationUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ActiveOrganizationUpdateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ActiveOrganizationUpdateRequest interface.
 */
export function instanceOfActiveOrganizationUpdateRequest(value: object): value is ActiveOrganizationUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ActiveOrganizationUpdateRequestFromJSON(json: any): ActiveOrganizationUpdateRequest {
    return ActiveOrganizationUpdateRequestFromJSONTyped(json, false);
}

export function ActiveOrganizationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveOrganizationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ActiveOrganizationUpdateRequestToJSON(json: any): ActiveOrganizationUpdateRequest {
    return ActiveOrganizationUpdateRequestToJSONTyped(json, false);
}

export function ActiveOrganizationUpdateRequestToJSONTyped(value?: ActiveOrganizationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

