/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActiveOrganizationMemberUpdateRequest
 */
export interface ActiveOrganizationMemberUpdateRequest {
    /**
     * 
     * @type {ActiveOrganizationMemberUpdateRequestRoleEnum}
     * @memberof ActiveOrganizationMemberUpdateRequest
     */
    role?: ActiveOrganizationMemberUpdateRequestRoleEnum | null;
    /**
     * 
     * @type {ActiveOrganizationMemberUpdateRequestStatusEnum}
     * @memberof ActiveOrganizationMemberUpdateRequest
     */
    status?: ActiveOrganizationMemberUpdateRequestStatusEnum | null;
}


/**
 * @export
 */
export const ActiveOrganizationMemberUpdateRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member',
    Viewer: 'viewer'
} as const;
export type ActiveOrganizationMemberUpdateRequestRoleEnum = typeof ActiveOrganizationMemberUpdateRequestRoleEnum[keyof typeof ActiveOrganizationMemberUpdateRequestRoleEnum];

/**
 * @export
 */
export const ActiveOrganizationMemberUpdateRequestStatusEnum = {
    Active: 'active',
    Suspended: 'suspended'
} as const;
export type ActiveOrganizationMemberUpdateRequestStatusEnum = typeof ActiveOrganizationMemberUpdateRequestStatusEnum[keyof typeof ActiveOrganizationMemberUpdateRequestStatusEnum];


/**
 * Check if a given object implements the ActiveOrganizationMemberUpdateRequest interface.
 */
export function instanceOfActiveOrganizationMemberUpdateRequest(value: object): value is ActiveOrganizationMemberUpdateRequest {
    return true;
}

export function ActiveOrganizationMemberUpdateRequestFromJSON(json: any): ActiveOrganizationMemberUpdateRequest {
    return ActiveOrganizationMemberUpdateRequestFromJSONTyped(json, false);
}

export function ActiveOrganizationMemberUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveOrganizationMemberUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ActiveOrganizationMemberUpdateRequestToJSON(json: any): ActiveOrganizationMemberUpdateRequest {
    return ActiveOrganizationMemberUpdateRequestToJSONTyped(json, false);
}

export function ActiveOrganizationMemberUpdateRequestToJSONTyped(value?: ActiveOrganizationMemberUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'status': value['status'],
    };
}

