/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * How much work the agent produced inside the window.
 * 
 * Each value is the read-time increment for its metric: a delta series is
 * summed, a cumulative one is diffed per series generation, so a counter that
 * is re-reported in full on every export is never counted twice.
 * ``lines_of_code`` sums the added and removed series, which are stored
 * separately. ``active_time`` is in seconds, as the agent reports it.
 * @export
 * @interface AgentTelemetryOutcomes
 */
export interface AgentTelemetryOutcomes {
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryOutcomes
     */
    activeTime?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryOutcomes
     */
    commits?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryOutcomes
     */
    linesOfCode?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryOutcomes
     */
    pullRequests?: number;
}

/**
 * Check if a given object implements the AgentTelemetryOutcomes interface.
 */
export function instanceOfAgentTelemetryOutcomes(value: object): value is AgentTelemetryOutcomes {
    return true;
}

export function AgentTelemetryOutcomesFromJSON(json: any): AgentTelemetryOutcomes {
    return AgentTelemetryOutcomesFromJSONTyped(json, false);
}

export function AgentTelemetryOutcomesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTelemetryOutcomes {
    if (json == null) {
        return json;
    }
    return {
        
        'activeTime': json['active_time'] == null ? undefined : json['active_time'],
        'commits': json['commits'] == null ? undefined : json['commits'],
        'linesOfCode': json['lines_of_code'] == null ? undefined : json['lines_of_code'],
        'pullRequests': json['pull_requests'] == null ? undefined : json['pull_requests'],
    };
}

export function AgentTelemetryOutcomesToJSON(json: any): AgentTelemetryOutcomes {
    return AgentTelemetryOutcomesToJSONTyped(json, false);
}

export function AgentTelemetryOutcomesToJSONTyped(value?: AgentTelemetryOutcomes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_time': value['activeTime'],
        'commits': value['commits'],
        'lines_of_code': value['linesOfCode'],
        'pull_requests': value['pullRequests'],
    };
}

