/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentTelemetryToolRow } from './AgentTelemetryToolRow.js';
import {
    AgentTelemetryToolRowFromJSON,
    AgentTelemetryToolRowFromJSONTyped,
    AgentTelemetryToolRowToJSON,
    AgentTelemetryToolRowToJSONTyped,
} from './AgentTelemetryToolRow.js';

/**
 * Counts from the behavioral events already captured on the logs signal.
 * @export
 * @interface AgentTelemetryBehavior
 */
export interface AgentTelemetryBehavior {
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    apiErrors?: number;
    /**
     * 
     * @type {Array<AgentTelemetryToolRow>}
     * @memberof AgentTelemetryBehavior
     */
    byTool?: Array<AgentTelemetryToolRow>;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    sessions?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    toolAccepts?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    toolCalls?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    toolRejects?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTelemetryBehavior
     */
    turns?: number;
}

/**
 * Check if a given object implements the AgentTelemetryBehavior interface.
 */
export function instanceOfAgentTelemetryBehavior(value: object): value is AgentTelemetryBehavior {
    return true;
}

export function AgentTelemetryBehaviorFromJSON(json: any): AgentTelemetryBehavior {
    return AgentTelemetryBehaviorFromJSONTyped(json, false);
}

export function AgentTelemetryBehaviorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTelemetryBehavior {
    if (json == null) {
        return json;
    }
    return {
        
        'apiErrors': json['api_errors'] == null ? undefined : json['api_errors'],
        'byTool': json['by_tool'] == null ? undefined : ((json['by_tool'] as Array<any>).map(AgentTelemetryToolRowFromJSON)),
        'sessions': json['sessions'] == null ? undefined : json['sessions'],
        'toolAccepts': json['tool_accepts'] == null ? undefined : json['tool_accepts'],
        'toolCalls': json['tool_calls'] == null ? undefined : json['tool_calls'],
        'toolRejects': json['tool_rejects'] == null ? undefined : json['tool_rejects'],
        'turns': json['turns'] == null ? undefined : json['turns'],
    };
}

export function AgentTelemetryBehaviorToJSON(json: any): AgentTelemetryBehavior {
    return AgentTelemetryBehaviorToJSONTyped(json, false);
}

export function AgentTelemetryBehaviorToJSONTyped(value?: AgentTelemetryBehavior | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_errors': value['apiErrors'],
        'by_tool': value['byTool'] == null ? undefined : ((value['byTool'] as Array<any>).map(AgentTelemetryToolRowToJSON)),
        'sessions': value['sessions'],
        'tool_accepts': value['toolAccepts'],
        'tool_calls': value['toolCalls'],
        'tool_rejects': value['toolRejects'],
        'turns': value['turns'],
    };
}

