/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * One file in the ``FileMetadata`` shape of Anthropic's GA Files API.
 * 
 * ``expires_at`` is always present and ``None`` for a file kept indefinitely.
 * ``downloadable`` is always true, because the gateway serves every stored file's bytes back.
 * @export
 * @interface AnthropicFileMetadata
 */
export interface AnthropicFileMetadata {
    /**
     * 
     * @type {string}
     * @memberof AnthropicFileMetadata
     */
    createdAt: string;
    /**
     * 
     * @type {AnthropicFileMetadataDownloadableEnum}
     * @memberof AnthropicFileMetadata
     */
    downloadable?: AnthropicFileMetadataDownloadableEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicFileMetadata
     */
    expiresAt: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnthropicFileMetadata
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof AnthropicFileMetadata
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AnthropicFileMetadata
     */
    mimeType: string;
    /**
     * 
     * @type {number}
     * @memberof AnthropicFileMetadata
     */
    sizeBytes: number;
    /**
     * 
     * @type {AnthropicFileMetadataTypeEnum}
     * @memberof AnthropicFileMetadata
     */
    type?: AnthropicFileMetadataTypeEnum;
}


/**
 * @export
 */
export const AnthropicFileMetadataDownloadableEnum = {
    True: true
} as const;
export type AnthropicFileMetadataDownloadableEnum = typeof AnthropicFileMetadataDownloadableEnum[keyof typeof AnthropicFileMetadataDownloadableEnum];

/**
 * @export
 */
export const AnthropicFileMetadataTypeEnum = {
    File: 'file'
} as const;
export type AnthropicFileMetadataTypeEnum = typeof AnthropicFileMetadataTypeEnum[keyof typeof AnthropicFileMetadataTypeEnum];


/**
 * Check if a given object implements the AnthropicFileMetadata interface.
 */
export function instanceOfAnthropicFileMetadata(value: object): value is AnthropicFileMetadata {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function AnthropicFileMetadataFromJSON(json: any): AnthropicFileMetadata {
    return AnthropicFileMetadataFromJSONTyped(json, false);
}

export function AnthropicFileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicFileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'downloadable': json['downloadable'] == null ? undefined : json['downloadable'],
        'expiresAt': json['expires_at'],
        'filename': json['filename'],
        'id': json['id'],
        'mimeType': json['mime_type'],
        'sizeBytes': json['size_bytes'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AnthropicFileMetadataToJSON(json: any): AnthropicFileMetadata {
    return AnthropicFileMetadataToJSONTyped(json, false);
}

export function AnthropicFileMetadataToJSONTyped(value?: AnthropicFileMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'downloadable': value['downloadable'],
        'expires_at': value['expiresAt'],
        'filename': value['filename'],
        'id': value['id'],
        'mime_type': value['mimeType'],
        'size_bytes': value['sizeBytes'],
        'type': value['type'],
    };
}

