/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Where to send the browser, and the state to check when it comes back.
 * @export
 * @interface AuthorizeResponse
 */
export interface AuthorizeResponse {
    /**
     * The provider consent screen to navigate to.
     * @type {string}
     * @memberof AuthorizeResponse
     */
    authorizationUrl: string;
    /**
     * An opaque CSRF value to keep for the length of the redirect and compare against the 'state' the provider returns. It is not stored on this deployment, so a callback whose state does not match the one held by the browser that started the flow must be abandoned by the client rather than sent here.
     * @type {string}
     * @memberof AuthorizeResponse
     */
    state: string;
}

/**
 * Check if a given object implements the AuthorizeResponse interface.
 */
export function instanceOfAuthorizeResponse(value: object): value is AuthorizeResponse {
    if (!('authorizationUrl' in value) || value['authorizationUrl'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function AuthorizeResponseFromJSON(json: any): AuthorizeResponse {
    return AuthorizeResponseFromJSONTyped(json, false);
}

export function AuthorizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationUrl': json['authorization_url'],
        'state': json['state'],
    };
}

export function AuthorizeResponseToJSON(json: any): AuthorizeResponse {
    return AuthorizeResponseToJSONTyped(json, false);
}

export function AuthorizeResponseToJSONTyped(value?: AuthorizeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization_url': value['authorizationUrl'],
        'state': value['state'],
    };
}

