/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BATCHBatchUsage } from './BATCHBatchUsage.js';
import {
    BATCHBatchUsageFromJSON,
    BATCHBatchUsageFromJSONTyped,
    BATCHBatchUsageToJSON,
    BATCHBatchUsageToJSONTyped,
} from './BATCHBatchUsage.js';
import type { BATCHErrors } from './BATCHErrors.js';
import {
    BATCHErrorsFromJSON,
    BATCHErrorsFromJSONTyped,
    BATCHErrorsToJSON,
    BATCHErrorsToJSONTyped,
} from './BATCHErrors.js';
import type { BATCHBatchRequestCounts } from './BATCHBatchRequestCounts.js';
import {
    BATCHBatchRequestCountsFromJSON,
    BATCHBatchRequestCountsFromJSONTyped,
    BATCHBatchRequestCountsToJSON,
    BATCHBatchRequestCountsToJSONTyped,
} from './BATCHBatchRequestCounts.js';

/**
 * 
 * @export
 * @interface BatchResponse
 */
export interface BatchResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof BatchResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BatchResponse
     */
    completionWindow: string;
    /**
     * 
     * @type {number}
     * @memberof BatchResponse
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof BatchResponse
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof BatchResponse
     */
    inputFileId: string;
    /**
     * 
     * @type {BatchResponseObjectEnum}
     * @memberof BatchResponse
     */
    object: BatchResponseObjectEnum;
    /**
     * 
     * @type {BatchResponseStatusEnum}
     * @memberof BatchResponse
     */
    status: BatchResponseStatusEnum;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    cancelledAt?: number | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    cancellingAt?: number | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    completedAt?: number | null;
    /**
     * Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
     * @type {string}
     * @memberof BatchResponse
     */
    errorFileId?: string | null;
    /**
     * 
     * @type {BATCHErrors}
     * @memberof BatchResponse
     */
    errors?: BATCHErrors | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    expiredAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BatchResponse
     */
    expiresAt?: number | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    failedAt?: number | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    finalizingAt?: number | null;
    /**
     * Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
     * @type {number}
     * @memberof BatchResponse
     */
    inProgressAt?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BatchResponse
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
     * @type {string}
     * @memberof BatchResponse
     */
    model?: string | null;
    /**
     * Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
     * @type {string}
     * @memberof BatchResponse
     */
    outputFileId?: string | null;
    /**
     * 
     * @type {BATCHBatchRequestCounts}
     * @memberof BatchResponse
     */
    requestCounts?: BATCHBatchRequestCounts | null;
    /**
     * 
     * @type {BATCHBatchUsage}
     * @memberof BatchResponse
     */
    usage?: BATCHBatchUsage | null;
    /**
     * Provider instance that owns the batch.
     * @type {string}
     * @memberof BatchResponse
     */
    provider: string;
}


/**
 * @export
 */
export const BatchResponseObjectEnum = {
    Batch: 'batch'
} as const;
export type BatchResponseObjectEnum = typeof BatchResponseObjectEnum[keyof typeof BatchResponseObjectEnum];

/**
 * @export
 */
export const BatchResponseStatusEnum = {
    Validating: 'validating',
    Failed: 'failed',
    InProgress: 'in_progress',
    Finalizing: 'finalizing',
    Completed: 'completed',
    Expired: 'expired',
    Cancelling: 'cancelling',
    Cancelled: 'cancelled'
} as const;
export type BatchResponseStatusEnum = typeof BatchResponseStatusEnum[keyof typeof BatchResponseStatusEnum];


/**
 * Check if a given object implements the BatchResponse interface.
 */
export function instanceOfBatchResponse(value: object): value is BatchResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('completionWindow' in value) || value['completionWindow'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('inputFileId' in value) || value['inputFileId'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function BatchResponseFromJSON(json: any): BatchResponse {
    return BatchResponseFromJSONTyped(json, false);
}

export function BatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'completionWindow': json['completion_window'],
        'createdAt': json['created_at'],
        'endpoint': json['endpoint'],
        'inputFileId': json['input_file_id'],
        'object': json['object'],
        'status': json['status'],
        'cancelledAt': json['cancelled_at'] == null ? undefined : json['cancelled_at'],
        'cancellingAt': json['cancelling_at'] == null ? undefined : json['cancelling_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'errorFileId': json['error_file_id'] == null ? undefined : json['error_file_id'],
        'errors': json['errors'] == null ? undefined : BATCHErrorsFromJSON(json['errors']),
        'expiredAt': json['expired_at'] == null ? undefined : json['expired_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'failedAt': json['failed_at'] == null ? undefined : json['failed_at'],
        'finalizingAt': json['finalizing_at'] == null ? undefined : json['finalizing_at'],
        'inProgressAt': json['in_progress_at'] == null ? undefined : json['in_progress_at'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'model': json['model'] == null ? undefined : json['model'],
        'outputFileId': json['output_file_id'] == null ? undefined : json['output_file_id'],
        'requestCounts': json['request_counts'] == null ? undefined : BATCHBatchRequestCountsFromJSON(json['request_counts']),
        'usage': json['usage'] == null ? undefined : BATCHBatchUsageFromJSON(json['usage']),
        'provider': json['provider'],
    };
}

export function BatchResponseToJSON(json: any): BatchResponse {
    return BatchResponseToJSONTyped(json, false);
}

export function BatchResponseToJSONTyped(value?: BatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'completion_window': value['completionWindow'],
        'created_at': value['createdAt'],
        'endpoint': value['endpoint'],
        'input_file_id': value['inputFileId'],
        'object': value['object'],
        'status': value['status'],
        'cancelled_at': value['cancelledAt'],
        'cancelling_at': value['cancellingAt'],
        'completed_at': value['completedAt'],
        'error_file_id': value['errorFileId'],
        'errors': BATCHErrorsToJSON(value['errors']),
        'expired_at': value['expiredAt'],
        'expires_at': value['expiresAt'],
        'failed_at': value['failedAt'],
        'finalizing_at': value['finalizingAt'],
        'in_progress_at': value['inProgressAt'],
        'metadata': value['metadata'],
        'model': value['model'],
        'output_file_id': value['outputFileId'],
        'request_counts': BATCHBatchRequestCountsToJSON(value['requestCounts']),
        'usage': BATCHBatchUsageToJSON(value['usage']),
        'provider': value['provider'],
    };
}

