/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ChatCompletion } from './ChatCompletion.js';
import {
    ChatCompletionFromJSON,
    ChatCompletionFromJSONTyped,
    ChatCompletionToJSON,
    ChatCompletionToJSONTyped,
} from './ChatCompletion.js';
import type { BatchResultItemError } from './BatchResultItemError.js';
import {
    BatchResultItemErrorFromJSON,
    BatchResultItemErrorFromJSONTyped,
    BatchResultItemErrorToJSON,
    BatchResultItemErrorToJSONTyped,
} from './BatchResultItemError.js';

/**
 * 
 * @export
 * @interface BatchResultItem
 */
export interface BatchResultItem {
    /**
     * Identifier supplied for this request in the batch.
     * @type {string}
     * @memberof BatchResultItem
     */
    customId: string;
    /**
     * Serialized provider result, or null when the request failed.
     * @type {ChatCompletion}
     * @memberof BatchResultItem
     */
    result: ChatCompletion | null;
    /**
     * 
     * @type {BatchResultItemError}
     * @memberof BatchResultItem
     */
    error: BatchResultItemError | null;
}

/**
 * Check if a given object implements the BatchResultItem interface.
 */
export function instanceOfBatchResultItem(value: object): value is BatchResultItem {
    if (!('customId' in value) || value['customId'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BatchResultItemFromJSON(json: any): BatchResultItem {
    return BatchResultItemFromJSONTyped(json, false);
}

export function BatchResultItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResultItem {
    if (json == null) {
        return json;
    }
    return {
        
        'customId': json['custom_id'],
        'result': ChatCompletionFromJSON(json['result']),
        'error': BatchResultItemErrorFromJSON(json['error']),
    };
}

export function BatchResultItemToJSON(json: any): BatchResultItem {
    return BatchResultItemToJSONTyped(json, false);
}

export function BatchResultItemToJSONTyped(value?: BatchResultItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_id': value['customId'],
        'result': ChatCompletionToJSON(value['result']),
        'error': BatchResultItemErrorToJSON(value['error']),
    };
}

