/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BatchResultItemError
 */
export interface BatchResultItemError {
    /**
     * 
     * @type {string}
     * @memberof BatchResultItemError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof BatchResultItemError
     */
    message: string;
}

/**
 * Check if a given object implements the BatchResultItemError interface.
 */
export function instanceOfBatchResultItemError(value: object): value is BatchResultItemError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function BatchResultItemErrorFromJSON(json: any): BatchResultItemError {
    return BatchResultItemErrorFromJSONTyped(json, false);
}

export function BatchResultItemErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResultItemError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function BatchResultItemErrorToJSON(json: any): BatchResultItemError {
    return BatchResultItemErrorToJSONTyped(json, false);
}

export function BatchResultItemErrorToJSONTyped(value?: BatchResultItemError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

