/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for budget information.
 * @export
 * @interface BudgetResponse
 */
export interface BudgetResponse {
    /**
     * 
     * @type {number}
     * @memberof BudgetResponse
     */
    budgetDurationSec: number | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetResponse
     */
    budgetId: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetResponse
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof BudgetResponse
     */
    maxBudget: number | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the BudgetResponse interface.
 */
export function instanceOfBudgetResponse(value: object): value is BudgetResponse {
    if ((!('budgetDurationSec' in value) && !('budget_duration_sec' in value)) || (value['budgetDurationSec'] === undefined && value['budget_duration_sec'] === undefined)) return false;
    if ((!('budgetId' in value) && !('budget_id' in value)) || (value['budgetId'] === undefined && value['budget_id'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('maxBudget' in value) && !('max_budget' in value)) || (value['maxBudget'] === undefined && value['max_budget'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function BudgetResponseFromJSON(json: any): BudgetResponse {
    return BudgetResponseFromJSONTyped(json, false);
}

export function BudgetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'budgetDurationSec': json['budget_duration_sec'],
        'budgetId': json['budget_id'],
        'createdAt': json['created_at'],
        'maxBudget': json['max_budget'],
        'updatedAt': json['updated_at'],
    };
}

export function BudgetResponseToJSON(json: any): BudgetResponse {
    return BudgetResponseToJSONTyped(json, false);
}

export function BudgetResponseToJSONTyped(value?: BudgetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget_duration_sec': value['budgetDurationSec'],
        'budget_id': value['budgetId'],
        'created_at': value['createdAt'],
        'max_budget': value['maxBudget'],
        'updated_at': value['updatedAt'],
    };
}

