/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaServerToolCaller } from './MRBetaServerToolCaller.js';
import {
    MRBetaServerToolCallerFromJSON,
    MRBetaServerToolCallerFromJSONTyped,
    MRBetaServerToolCallerToJSON,
    MRBetaServerToolCallerToJSONTyped,
} from './MRBetaServerToolCaller.js';
import type { MRBetaServerToolCaller20260120 } from './MRBetaServerToolCaller20260120.js';
import {
    MRBetaServerToolCaller20260120FromJSON,
    MRBetaServerToolCaller20260120FromJSONTyped,
    MRBetaServerToolCaller20260120ToJSON,
    MRBetaServerToolCaller20260120ToJSONTyped,
} from './MRBetaServerToolCaller20260120.js';
import type { MRBetaDirectCaller } from './MRBetaDirectCaller.js';
import {
    MRBetaDirectCallerFromJSON,
    MRBetaDirectCallerFromJSONTyped,
    MRBetaDirectCallerToJSON,
    MRBetaDirectCallerToJSONTyped,
} from './MRBetaDirectCaller.js';

/**
 * 
 * @export
 * @interface Caller
 */
export interface Caller {
    /**
     * 
     * @type {CallerTypeEnum}
     * @memberof Caller
     */
    type: CallerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Caller
     */
    toolId: string;
}


/**
 * @export
 */
export const CallerTypeEnum = {
    Direct: 'direct',
    CodeExecution20250825: 'code_execution_20250825',
    CodeExecution20260120: 'code_execution_20260120'
} as const;
export type CallerTypeEnum = typeof CallerTypeEnum[keyof typeof CallerTypeEnum];


/**
 * Check if a given object implements the Caller interface.
 */
export function instanceOfCaller(value: object): value is Caller {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('toolId' in value) || value['toolId'] === undefined) return false;
    return true;
}

export function CallerFromJSON(json: any): Caller {
    return CallerFromJSONTyped(json, false);
}

export function CallerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Caller {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'toolId': json['tool_id'],
    };
}

export function CallerToJSON(json: any): Caller {
    return CallerToJSONTyped(json, false);
}

export function CallerToJSONTyped(value?: Caller | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'tool_id': value['toolId'],
    };
}

