/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * One candidate in a compiled plan.
 * @export
 * @interface CandidateResponse
 */
export interface CandidateResponse {
    /**
     * 
     * @type {string}
     * @memberof CandidateResponse
     */
    dispatchModel: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResponse
     */
    instance: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResponse
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateResponse
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateResponse
     */
    selectionReason: string;
}

/**
 * Check if a given object implements the CandidateResponse interface.
 */
export function instanceOfCandidateResponse(value: object): value is CandidateResponse {
    if (!('dispatchModel' in value) || value['dispatchModel'] === undefined) return false;
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('selectionReason' in value) || value['selectionReason'] === undefined) return false;
    return true;
}

export function CandidateResponseFromJSON(json: any): CandidateResponse {
    return CandidateResponseFromJSONTyped(json, false);
}

export function CandidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dispatchModel': json['dispatch_model'],
        'instance': json['instance'],
        'model': json['model'],
        'position': json['position'],
        'selectionReason': json['selection_reason'],
    };
}

export function CandidateResponseToJSON(json: any): CandidateResponse {
    return CandidateResponseToJSONTyped(json, false);
}

export function CandidateResponseToJSONTyped(value?: CandidateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dispatch_model': value['dispatchModel'],
        'instance': value['instance'],
        'model': value['model'],
        'position': value['position'],
        'selection_reason': value['selectionReason'],
    };
}

