/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CatalogCapabilities } from './CatalogCapabilities.js';
import {
    CatalogCapabilitiesFromJSON,
    CatalogCapabilitiesFromJSONTyped,
    CatalogCapabilitiesToJSON,
    CatalogCapabilitiesToJSONTyped,
} from './CatalogCapabilities.js';
import type { CatalogOffering } from './CatalogOffering.js';
import {
    CatalogOfferingFromJSON,
    CatalogOfferingFromJSONTyped,
    CatalogOfferingToJSON,
    CatalogOfferingToJSONTyped,
} from './CatalogOffering.js';
import type { CatalogElsewhere } from './CatalogElsewhere.js';
import {
    CatalogElsewhereFromJSON,
    CatalogElsewhereFromJSONTyped,
    CatalogElsewhereToJSON,
    CatalogElsewhereToJSONTyped,
} from './CatalogElsewhere.js';

/**
 * One model with everything the detail page shows.
 * @export
 * @interface CatalogModelDetail
 */
export interface CatalogModelDetail {
    /**
     * 
     * @type {Array<CatalogElsewhere>}
     * @memberof CatalogModelDetail
     */
    alsoAvailableFrom: Array<CatalogElsewhere>;
    /**
     * 
     * @type {CatalogCapabilities}
     * @memberof CatalogModelDetail
     */
    capabilities: CatalogCapabilities;
    /**
     * The largest any offering serves.
     * @type {number}
     * @memberof CatalogModelDetail
     */
    contextWindow?: number | null;
    /**
     * Whether an unpriced model is metered at the genai-prices default.
     * @type {boolean}
     * @memberof CatalogModelDetail
     */
    defaultPricing: boolean;
    /**
     * True only when every offering with metadata says so.
     * @type {boolean}
     * @memberof CatalogModelDetail
     */
    deprecated?: boolean;
    /**
     * models.dev's, from the offering that named the model.
     * @type {string}
     * @memberof CatalogModelDetail
     */
    description?: string | null;
    /**
     * Whether any offering was discovered from its provider.
     * @type {boolean}
     * @memberof CatalogModelDetail
     */
    discovered: boolean;
    /**
     * 
     * @type {string}
     * @memberof CatalogModelDetail
     */
    family?: string | null;
    /**
     * The catalog id, vendor-qualified where the vendor is known: `z-ai/glm-5.3`, else the bare slug.
     * @type {string}
     * @memberof CatalogModelDetail
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogModelDetail
     */
    inputModalities: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogModelDetail
     */
    knowledgeCutoff?: string | null;
    /**
     * The largest any offering serves.
     * @type {number}
     * @memberof CatalogModelDetail
     */
    maxOutputTokens?: number | null;
    /**
     * The cheapest offering's, at the comparison context where one was asked for.
     * @type {number}
     * @memberof CatalogModelDetail
     */
    minInputPricePerMillion?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CatalogModelDetail
     */
    minOutputPricePerMillion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogModelDetail
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogModelDetail
     */
    offeringCount: number;
    /**
     * 
     * @type {Array<CatalogOffering>}
     * @memberof CatalogModelDetail
     */
    offerings: Array<CatalogOffering>;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogModelDetail
     */
    openWeights?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogModelDetail
     */
    outputModalities: Array<string>;
    /**
     * Which price lists the priced offerings came from, distinct and sorted.
     * @type {Array<CatalogModelDetailPriceSourcesEnum>}
     * @memberof CatalogModelDetail
     */
    priceSources: Array<CatalogModelDetailPriceSourcesEnum>;
    /**
     * 
     * @type {number}
     * @memberof CatalogModelDetail
     */
    providerCount: number;
    /**
     * The provider instances offering it, sorted.
     * @type {Array<string>}
     * @memberof CatalogModelDetail
     */
    providers: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogModelDetail
     */
    releaseDate?: string | null;
    /**
     * The offering `selector` resolves to.
     * @type {string}
     * @memberof CatalogModelDetail
     */
    resolvesTo?: string | null;
    /**
     * The id as a selector: send it as `model` and the model's cheapest offering answers. Null until the gateway has indexed the catalog.
     * @type {string}
     * @memberof CatalogModelDetail
     */
    selector?: string | null;
    /**
     * Every offering's selector, so the list can be searched by one.
     * @type {Array<string>}
     * @memberof CatalogModelDetail
     */
    selectors: Array<string>;
    /**
     * How many offerings carry no price for this caller.
     * @type {number}
     * @memberof CatalogModelDetail
     */
    unpricedCount: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogModelDetail
     */
    vendor: string | null;
}


/**
 * @export
 */
export const CatalogModelDetailPriceSourcesEnum = {
    Organization: 'organization',
    Deployment: 'deployment',
    Defaults: 'defaults'
} as const;
export type CatalogModelDetailPriceSourcesEnum = typeof CatalogModelDetailPriceSourcesEnum[keyof typeof CatalogModelDetailPriceSourcesEnum];


/**
 * Check if a given object implements the CatalogModelDetail interface.
 */
export function instanceOfCatalogModelDetail(value: object): value is CatalogModelDetail {
    if (!('alsoAvailableFrom' in value) || value['alsoAvailableFrom'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('defaultPricing' in value) || value['defaultPricing'] === undefined) return false;
    if (!('discovered' in value) || value['discovered'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('inputModalities' in value) || value['inputModalities'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('offeringCount' in value) || value['offeringCount'] === undefined) return false;
    if (!('offerings' in value) || value['offerings'] === undefined) return false;
    if (!('outputModalities' in value) || value['outputModalities'] === undefined) return false;
    if (!('priceSources' in value) || value['priceSources'] === undefined) return false;
    if (!('providerCount' in value) || value['providerCount'] === undefined) return false;
    if (!('providers' in value) || value['providers'] === undefined) return false;
    if (!('selectors' in value) || value['selectors'] === undefined) return false;
    if (!('unpricedCount' in value) || value['unpricedCount'] === undefined) return false;
    if (!('vendor' in value) || value['vendor'] === undefined) return false;
    return true;
}

export function CatalogModelDetailFromJSON(json: any): CatalogModelDetail {
    return CatalogModelDetailFromJSONTyped(json, false);
}

export function CatalogModelDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogModelDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'alsoAvailableFrom': ((json['also_available_from'] as Array<any>).map(CatalogElsewhereFromJSON)),
        'capabilities': CatalogCapabilitiesFromJSON(json['capabilities']),
        'contextWindow': json['context_window'] == null ? undefined : json['context_window'],
        'defaultPricing': json['default_pricing'],
        'deprecated': json['deprecated'] == null ? undefined : json['deprecated'],
        'description': json['description'] == null ? undefined : json['description'],
        'discovered': json['discovered'],
        'family': json['family'] == null ? undefined : json['family'],
        'id': json['id'],
        'inputModalities': json['input_modalities'],
        'knowledgeCutoff': json['knowledge_cutoff'] == null ? undefined : json['knowledge_cutoff'],
        'maxOutputTokens': json['max_output_tokens'] == null ? undefined : json['max_output_tokens'],
        'minInputPricePerMillion': json['min_input_price_per_million'] == null ? undefined : json['min_input_price_per_million'],
        'minOutputPricePerMillion': json['min_output_price_per_million'] == null ? undefined : json['min_output_price_per_million'],
        'name': json['name'],
        'offeringCount': json['offering_count'],
        'offerings': ((json['offerings'] as Array<any>).map(CatalogOfferingFromJSON)),
        'openWeights': json['open_weights'] == null ? undefined : json['open_weights'],
        'outputModalities': json['output_modalities'],
        'priceSources': json['price_sources'],
        'providerCount': json['provider_count'],
        'providers': json['providers'],
        'releaseDate': json['release_date'] == null ? undefined : json['release_date'],
        'resolvesTo': json['resolves_to'] == null ? undefined : json['resolves_to'],
        'selector': json['selector'] == null ? undefined : json['selector'],
        'selectors': json['selectors'],
        'unpricedCount': json['unpriced_count'],
        'vendor': json['vendor'],
    };
}

export function CatalogModelDetailToJSON(json: any): CatalogModelDetail {
    return CatalogModelDetailToJSONTyped(json, false);
}

export function CatalogModelDetailToJSONTyped(value?: CatalogModelDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'also_available_from': ((value['alsoAvailableFrom'] as Array<any>).map(CatalogElsewhereToJSON)),
        'capabilities': CatalogCapabilitiesToJSON(value['capabilities']),
        'context_window': value['contextWindow'],
        'default_pricing': value['defaultPricing'],
        'deprecated': value['deprecated'],
        'description': value['description'],
        'discovered': value['discovered'],
        'family': value['family'],
        'id': value['id'],
        'input_modalities': value['inputModalities'],
        'knowledge_cutoff': value['knowledgeCutoff'],
        'max_output_tokens': value['maxOutputTokens'],
        'min_input_price_per_million': value['minInputPricePerMillion'],
        'min_output_price_per_million': value['minOutputPricePerMillion'],
        'name': value['name'],
        'offering_count': value['offeringCount'],
        'offerings': ((value['offerings'] as Array<any>).map(CatalogOfferingToJSON)),
        'open_weights': value['openWeights'],
        'output_modalities': value['outputModalities'],
        'price_sources': value['priceSources'],
        'provider_count': value['providerCount'],
        'providers': value['providers'],
        'release_date': value['releaseDate'],
        'resolves_to': value['resolvesTo'],
        'selector': value['selector'],
        'selectors': value['selectors'],
        'unpriced_count': value['unpricedCount'],
        'vendor': value['vendor'],
    };
}

