/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CCFunction } from './CCFunction.js';
import {
    CCFunctionFromJSON,
    CCFunctionFromJSONTyped,
    CCFunctionToJSON,
    CCFunctionToJSONTyped,
} from './CCFunction.js';

/**
 * Extended tool call type that includes extra_content for provider-specific data.
 * 
 * The extra_content field is used to store provider-specific metadata that needs
 * to be preserved across multi-turn conversations. For example, Gemini 3 models
 * require thought_signature to be passed back with function calls.
 * 
 * Example extra_content structure for Gemini:
 *     {"google": {"thought_signature": "<base64-encoded-signature>"}}
 * @export
 * @interface CCChatCompletionMessageFunctionToolCall
 */
export interface CCChatCompletionMessageFunctionToolCall {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CCChatCompletionMessageFunctionToolCall
     */
    id: string;
    /**
     * 
     * @type {CCFunction}
     * @memberof CCChatCompletionMessageFunctionToolCall
     */
    _function: CCFunction;
    /**
     * 
     * @type {CCChatCompletionMessageFunctionToolCallTypeEnum}
     * @memberof CCChatCompletionMessageFunctionToolCall
     */
    type: CCChatCompletionMessageFunctionToolCallTypeEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CCChatCompletionMessageFunctionToolCall
     */
    extraContent?: { [key: string]: any; } | null;
}


/**
 * @export
 */
export const CCChatCompletionMessageFunctionToolCallTypeEnum = {
    Function: 'function'
} as const;
export type CCChatCompletionMessageFunctionToolCallTypeEnum = typeof CCChatCompletionMessageFunctionToolCallTypeEnum[keyof typeof CCChatCompletionMessageFunctionToolCallTypeEnum];


/**
 * Check if a given object implements the CCChatCompletionMessageFunctionToolCall interface.
 */
export function instanceOfCCChatCompletionMessageFunctionToolCall(value: object): value is CCChatCompletionMessageFunctionToolCall {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CCChatCompletionMessageFunctionToolCallFromJSON(json: any): CCChatCompletionMessageFunctionToolCall {
    return CCChatCompletionMessageFunctionToolCallFromJSONTyped(json, false);
}

export function CCChatCompletionMessageFunctionToolCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): CCChatCompletionMessageFunctionToolCall {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        '_function': CCFunctionFromJSON(json['function']),
        'type': json['type'],
        'extraContent': json['extra_content'] == null ? undefined : json['extra_content'],
    };
}

export function CCChatCompletionMessageFunctionToolCallToJSON(json: any): CCChatCompletionMessageFunctionToolCall {
    return CCChatCompletionMessageFunctionToolCallToJSONTyped(json, false);
}

export function CCChatCompletionMessageFunctionToolCallToJSONTyped(value?: CCChatCompletionMessageFunctionToolCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'function': CCFunctionToJSON(value['_function']),
        'type': value['type'],
        'extra_content': value['extraContent'],
    };
}

