/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Partial audio object emitted by a streaming chat completion.
 * 
 * Providers may send the identifier, transcript, data, and expiration timestamp in
 * separate chunks, so every field is optional. The data field contains the
 * base64-encoded bytes for the current chunk.
 * @export
 * @interface CCKChoiceDeltaAudio
 */
export interface CCKChoiceDeltaAudio {
    /**
     * Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
     * @type {string}
     * @memberof CCKChoiceDeltaAudio
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CCKChoiceDeltaAudio
     */
    data?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CCKChoiceDeltaAudio
     */
    transcript?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CCKChoiceDeltaAudio
     */
    expiresAt?: number | null;
}

/**
 * Check if a given object implements the CCKChoiceDeltaAudio interface.
 */
export function instanceOfCCKChoiceDeltaAudio(value: object): value is CCKChoiceDeltaAudio {
    return true;
}

export function CCKChoiceDeltaAudioFromJSON(json: any): CCKChoiceDeltaAudio {
    return CCKChoiceDeltaAudioFromJSONTyped(json, false);
}

export function CCKChoiceDeltaAudioFromJSONTyped(json: any, ignoreDiscriminator: boolean): CCKChoiceDeltaAudio {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'data': json['data'] == null ? undefined : json['data'],
        'transcript': json['transcript'] == null ? undefined : json['transcript'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
    };
}

export function CCKChoiceDeltaAudioToJSON(json: any): CCKChoiceDeltaAudio {
    return CCKChoiceDeltaAudioToJSONTyped(json, false);
}

export function CCKChoiceDeltaAudioToJSONTyped(value?: CCKChoiceDeltaAudio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'data': value['data'],
        'transcript': value['transcript'],
        'expires_at': value['expiresAt'],
    };
}

