/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Breakdown of tokens used in the prompt.
 * @export
 * @interface CCKPromptTokensDetails
 */
export interface CCKPromptTokensDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof CCKPromptTokensDetails
     */
    audioTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CCKPromptTokensDetails
     */
    cachedTokens?: number | null;
}

/**
 * Check if a given object implements the CCKPromptTokensDetails interface.
 */
export function instanceOfCCKPromptTokensDetails(value: object): value is CCKPromptTokensDetails {
    return true;
}

export function CCKPromptTokensDetailsFromJSON(json: any): CCKPromptTokensDetails {
    return CCKPromptTokensDetailsFromJSONTyped(json, false);
}

export function CCKPromptTokensDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CCKPromptTokensDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'audioTokens': json['audio_tokens'] == null ? undefined : json['audio_tokens'],
        'cachedTokens': json['cached_tokens'] == null ? undefined : json['cached_tokens'],
    };
}

export function CCKPromptTokensDetailsToJSON(json: any): CCKPromptTokensDetails {
    return CCKPromptTokensDetailsToJSONTyped(json, false);
}

export function CCKPromptTokensDetailsToJSONTyped(value?: CCKPromptTokensDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'audio_tokens': value['audioTokens'],
        'cached_tokens': value['cachedTokens'],
    };
}

