/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reasoning content emitted by a model.
 * 
 * Serializes as a plain JSON string so that responses are compatible with
 * OpenAI-style clients that expect ``delta.reasoning`` / ``message.reasoning``
 * to be a string. The Python attribute ``content`` remains available for
 * typed access (e.g. ``message.reasoning.content``).
 * @export
 * @interface CCKReasoning
 */
export interface CCKReasoning {
    /**
     * 
     * @type {string}
     * @memberof CCKReasoning
     */
    content: string;
}

/**
 * Check if a given object implements the CCKReasoning interface.
 */
export function instanceOfCCKReasoning(value: object): value is CCKReasoning {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CCKReasoningFromJSON(json: any): CCKReasoning {
    return CCKReasoningFromJSONTyped(json, false);
}

export function CCKReasoningFromJSONTyped(json: any, ignoreDiscriminator: boolean): CCKReasoning {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function CCKReasoningToJSON(json: any): CCKReasoning {
    return CCKReasoningToJSONTyped(json, false);
}

export function CCKReasoningToJSONTyped(value?: CCKReasoning | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

