/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CCTopLogprob
 */
export interface CCTopLogprob {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CCTopLogprob
     */
    token: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CCTopLogprob
     */
    bytes?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof CCTopLogprob
     */
    logprob: number;
}

/**
 * Check if a given object implements the CCTopLogprob interface.
 */
export function instanceOfCCTopLogprob(value: object): value is CCTopLogprob {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('logprob' in value) || value['logprob'] === undefined) return false;
    return true;
}

export function CCTopLogprobFromJSON(json: any): CCTopLogprob {
    return CCTopLogprobFromJSONTyped(json, false);
}

export function CCTopLogprobFromJSONTyped(json: any, ignoreDiscriminator: boolean): CCTopLogprob {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
        'logprob': json['logprob'],
    };
}

export function CCTopLogprobToJSON(json: any): CCTopLogprob {
    return CCTopLogprobToJSONTyped(json, false);
}

export function CCTopLogprobToJSONTyped(value?: CCTopLogprob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'token': value['token'],
        'bytes': value['bytes'],
        'logprob': value['logprob'],
    };
}

