/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MSGImageURL } from './MSGImageURL.js';
import {
    MSGImageURLFromJSON,
    MSGImageURLFromJSONTyped,
    MSGImageURLToJSON,
    MSGImageURLToJSONTyped,
} from './MSGImageURL.js';
import type { MSGFile } from './MSGFile.js';
import {
    MSGFileFromJSON,
    MSGFileFromJSONTyped,
    MSGFileToJSON,
    MSGFileToJSONTyped,
} from './MSGFile.js';
import type { MSGChatCompletionContentPartTextParam } from './MSGChatCompletionContentPartTextParam.js';
import {
    MSGChatCompletionContentPartTextParamFromJSON,
    MSGChatCompletionContentPartTextParamFromJSONTyped,
    MSGChatCompletionContentPartTextParamToJSON,
    MSGChatCompletionContentPartTextParamToJSONTyped,
} from './MSGChatCompletionContentPartTextParam.js';
import type { MSGFileFile } from './MSGFileFile.js';
import {
    MSGFileFileFromJSON,
    MSGFileFileFromJSONTyped,
    MSGFileFileToJSON,
    MSGFileFileToJSONTyped,
} from './MSGFileFile.js';
import type { MSGChatCompletionContentPartInputAudioParam } from './MSGChatCompletionContentPartInputAudioParam.js';
import {
    MSGChatCompletionContentPartInputAudioParamFromJSON,
    MSGChatCompletionContentPartInputAudioParamFromJSONTyped,
    MSGChatCompletionContentPartInputAudioParamToJSON,
    MSGChatCompletionContentPartInputAudioParamToJSONTyped,
} from './MSGChatCompletionContentPartInputAudioParam.js';
import type { MSGInputAudio } from './MSGInputAudio.js';
import {
    MSGInputAudioFromJSON,
    MSGInputAudioFromJSONTyped,
    MSGInputAudioToJSON,
    MSGInputAudioToJSONTyped,
} from './MSGInputAudio.js';
import type { MSGChatCompletionContentPartImageParam } from './MSGChatCompletionContentPartImageParam.js';
import {
    MSGChatCompletionContentPartImageParamFromJSON,
    MSGChatCompletionContentPartImageParamFromJSONTyped,
    MSGChatCompletionContentPartImageParamToJSON,
    MSGChatCompletionContentPartImageParamToJSONTyped,
} from './MSGChatCompletionContentPartImageParam.js';

/**
 * 
 * @export
 * @interface Content2AnyOfInner
 */
export interface Content2AnyOfInner {
    /**
     * 
     * @type {string}
     * @memberof Content2AnyOfInner
     */
    text: string;
    /**
     * 
     * @type {Content2AnyOfInnerTypeEnum}
     * @memberof Content2AnyOfInner
     */
    type: Content2AnyOfInnerTypeEnum;
    /**
     * 
     * @type {MSGImageURL}
     * @memberof Content2AnyOfInner
     */
    imageUrl: MSGImageURL;
    /**
     * 
     * @type {MSGInputAudio}
     * @memberof Content2AnyOfInner
     */
    inputAudio: MSGInputAudio;
    /**
     * 
     * @type {MSGFileFile}
     * @memberof Content2AnyOfInner
     */
    file: MSGFileFile;
}


/**
 * @export
 */
export const Content2AnyOfInnerTypeEnum = {
    Text: 'text',
    ImageUrl: 'image_url',
    InputAudio: 'input_audio',
    File: 'file'
} as const;
export type Content2AnyOfInnerTypeEnum = typeof Content2AnyOfInnerTypeEnum[keyof typeof Content2AnyOfInnerTypeEnum];


/**
 * Check if a given object implements the Content2AnyOfInner interface.
 */
export function instanceOfContent2AnyOfInner(value: object): value is Content2AnyOfInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('inputAudio' in value) || value['inputAudio'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function Content2AnyOfInnerFromJSON(json: any): Content2AnyOfInner {
    return Content2AnyOfInnerFromJSONTyped(json, false);
}

export function Content2AnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content2AnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'type': json['type'],
        'imageUrl': MSGImageURLFromJSON(json['image_url']),
        'inputAudio': MSGInputAudioFromJSON(json['input_audio']),
        'file': MSGFileFileFromJSON(json['file']),
    };
}

export function Content2AnyOfInnerToJSON(json: any): Content2AnyOfInner {
    return Content2AnyOfInnerToJSONTyped(json, false);
}

export function Content2AnyOfInnerToJSONTyped(value?: Content2AnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'type': value['type'],
        'image_url': MSGImageURLToJSON(value['imageUrl']),
        'input_audio': MSGInputAudioToJSON(value['inputAudio']),
        'file': MSGFileFileToJSON(value['file']),
    };
}

