/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Annotations } from './Annotations.js';
import {
    AnnotationsFromJSON,
    AnnotationsFromJSONTyped,
    AnnotationsToJSON,
    AnnotationsToJSONTyped,
} from './Annotations.js';
import type { EmbeddedResource } from './EmbeddedResource.js';
import {
    EmbeddedResourceFromJSON,
    EmbeddedResourceFromJSONTyped,
    EmbeddedResourceToJSON,
    EmbeddedResourceToJSONTyped,
} from './EmbeddedResource.js';
import type { ImageContent } from './ImageContent.js';
import {
    ImageContentFromJSON,
    ImageContentFromJSONTyped,
    ImageContentToJSON,
    ImageContentToJSONTyped,
} from './ImageContent.js';
import type { ResourceLink } from './ResourceLink.js';
import {
    ResourceLinkFromJSON,
    ResourceLinkFromJSONTyped,
    ResourceLinkToJSON,
    ResourceLinkToJSONTyped,
} from './ResourceLink.js';
import type { AudioContent } from './AudioContent.js';
import {
    AudioContentFromJSON,
    AudioContentFromJSONTyped,
    AudioContentToJSON,
    AudioContentToJSONTyped,
} from './AudioContent.js';
import type { Resource } from './Resource.js';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource.js';
import type { Icon } from './Icon.js';
import {
    IconFromJSON,
    IconFromJSONTyped,
    IconToJSON,
    IconToJSONTyped,
} from './Icon.js';
import type { TextContent } from './TextContent.js';
import {
    TextContentFromJSON,
    TextContentFromJSONTyped,
    TextContentToJSON,
    TextContentToJSONTyped,
} from './TextContent.js';

/**
 * 
 * @export
 * @interface ContentInner
 */
export interface ContentInner {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ContentInner
     */
    meta?: { [key: string]: any; };
    /**
     * 
     * @type {Annotations}
     * @memberof ContentInner
     */
    annotations?: Annotations;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    text: string;
    /**
     * 
     * @type {ContentInnerTypeEnum}
     * @memberof ContentInner
     */
    type: ContentInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    description?: string;
    /**
     * 
     * @type {Array<Icon>}
     * @memberof ContentInner
     */
    icons?: Array<Icon>;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ContentInner
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentInner
     */
    uri: string;
    /**
     * 
     * @type {Resource}
     * @memberof ContentInner
     */
    resource: Resource;
}


/**
 * @export
 */
export const ContentInnerTypeEnum = {
    Text: 'text',
    Image: 'image',
    Audio: 'audio',
    ResourceLink: 'resource_link',
    Resource: 'resource'
} as const;
export type ContentInnerTypeEnum = typeof ContentInnerTypeEnum[keyof typeof ContentInnerTypeEnum];


/**
 * Check if a given object implements the ContentInner interface.
 */
export function instanceOfContentInner(value: object): value is ContentInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    return true;
}

export function ContentInnerFromJSON(json: any): ContentInner {
    return ContentInnerFromJSONTyped(json, false);
}

export function ContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['_meta'] == null ? undefined : json['_meta'],
        'annotations': json['annotations'] == null ? undefined : AnnotationsFromJSON(json['annotations']),
        'text': json['text'],
        'type': json['type'],
        'data': json['data'],
        'mimeType': json['mimeType'],
        'description': json['description'] == null ? undefined : json['description'],
        'icons': json['icons'] == null ? undefined : ((json['icons'] as Array<any>).map(IconFromJSON)),
        'name': json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'title': json['title'] == null ? undefined : json['title'],
        'uri': json['uri'],
        'resource': ResourceFromJSON(json['resource']),
    };
}

export function ContentInnerToJSON(json: any): ContentInner {
    return ContentInnerToJSONTyped(json, false);
}

export function ContentInnerToJSONTyped(value?: ContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_meta': value['meta'],
        'annotations': AnnotationsToJSON(value['annotations']),
        'text': value['text'],
        'type': value['type'],
        'data': value['data'],
        'mimeType': value['mimeType'],
        'description': value['description'],
        'icons': value['icons'] == null ? undefined : ((value['icons'] as Array<any>).map(IconToJSON)),
        'name': value['name'],
        'size': value['size'],
        'title': value['title'],
        'uri': value['uri'],
        'resource': ResourceToJSON(value['resource']),
    };
}

