/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MRTextBlockCitationsInner } from './MRTextBlockCitationsInner';
import {
    MRTextBlockCitationsInnerFromJSON,
    MRTextBlockCitationsInnerFromJSONTyped,
    MRTextBlockCitationsInnerToJSON,
    MRTextBlockCitationsInnerToJSONTyped,
} from './MRTextBlockCitationsInner';
import type { MRWebSearchToolResultBlock } from './MRWebSearchToolResultBlock';
import {
    MRWebSearchToolResultBlockFromJSON,
    MRWebSearchToolResultBlockFromJSONTyped,
    MRWebSearchToolResultBlockToJSON,
    MRWebSearchToolResultBlockToJSONTyped,
} from './MRWebSearchToolResultBlock';
import type { MRToolSearchToolResultBlock } from './MRToolSearchToolResultBlock';
import {
    MRToolSearchToolResultBlockFromJSON,
    MRToolSearchToolResultBlockFromJSONTyped,
    MRToolSearchToolResultBlockToJSON,
    MRToolSearchToolResultBlockToJSONTyped,
} from './MRToolSearchToolResultBlock';
import type { MRWebFetchToolResultBlock } from './MRWebFetchToolResultBlock';
import {
    MRWebFetchToolResultBlockFromJSON,
    MRWebFetchToolResultBlockFromJSONTyped,
    MRWebFetchToolResultBlockToJSON,
    MRWebFetchToolResultBlockToJSONTyped,
} from './MRWebFetchToolResultBlock';
import type { MRBashCodeExecutionToolResultBlock } from './MRBashCodeExecutionToolResultBlock';
import {
    MRBashCodeExecutionToolResultBlockFromJSON,
    MRBashCodeExecutionToolResultBlockFromJSONTyped,
    MRBashCodeExecutionToolResultBlockToJSON,
    MRBashCodeExecutionToolResultBlockToJSONTyped,
} from './MRBashCodeExecutionToolResultBlock';
import type { MRCodeExecutionToolResultBlock } from './MRCodeExecutionToolResultBlock';
import {
    MRCodeExecutionToolResultBlockFromJSON,
    MRCodeExecutionToolResultBlockFromJSONTyped,
    MRCodeExecutionToolResultBlockToJSON,
    MRCodeExecutionToolResultBlockToJSONTyped,
} from './MRCodeExecutionToolResultBlock';
import type { MRServerToolUseBlock } from './MRServerToolUseBlock';
import {
    MRServerToolUseBlockFromJSON,
    MRServerToolUseBlockFromJSONTyped,
    MRServerToolUseBlockToJSON,
    MRServerToolUseBlockToJSONTyped,
} from './MRServerToolUseBlock';
import type { MRContainerUploadBlock } from './MRContainerUploadBlock';
import {
    MRContainerUploadBlockFromJSON,
    MRContainerUploadBlockFromJSONTyped,
    MRContainerUploadBlockToJSON,
    MRContainerUploadBlockToJSONTyped,
} from './MRContainerUploadBlock';
import type { MRThinkingBlock } from './MRThinkingBlock';
import {
    MRThinkingBlockFromJSON,
    MRThinkingBlockFromJSONTyped,
    MRThinkingBlockToJSON,
    MRThinkingBlockToJSONTyped,
} from './MRThinkingBlock';
import type { MRRedactedThinkingBlock } from './MRRedactedThinkingBlock';
import {
    MRRedactedThinkingBlockFromJSON,
    MRRedactedThinkingBlockFromJSONTyped,
    MRRedactedThinkingBlockToJSON,
    MRRedactedThinkingBlockToJSONTyped,
} from './MRRedactedThinkingBlock';
import type { Content6 } from './Content6';
import {
    Content6FromJSON,
    Content6FromJSONTyped,
    Content6ToJSON,
    Content6ToJSONTyped,
} from './Content6';
import type { MRToolUseBlock } from './MRToolUseBlock';
import {
    MRToolUseBlockFromJSON,
    MRToolUseBlockFromJSONTyped,
    MRToolUseBlockToJSON,
    MRToolUseBlockToJSONTyped,
} from './MRToolUseBlock';
import type { Caller } from './Caller';
import {
    CallerFromJSON,
    CallerFromJSONTyped,
    CallerToJSON,
    CallerToJSONTyped,
} from './Caller';
import type { MRTextBlock } from './MRTextBlock';
import {
    MRTextBlockFromJSON,
    MRTextBlockFromJSONTyped,
    MRTextBlockToJSON,
    MRTextBlockToJSONTyped,
} from './MRTextBlock';
import type { MRTextEditorCodeExecutionToolResultBlock } from './MRTextEditorCodeExecutionToolResultBlock';
import {
    MRTextEditorCodeExecutionToolResultBlockFromJSON,
    MRTextEditorCodeExecutionToolResultBlockFromJSONTyped,
    MRTextEditorCodeExecutionToolResultBlockToJSON,
    MRTextEditorCodeExecutionToolResultBlockToJSONTyped,
} from './MRTextEditorCodeExecutionToolResultBlock';

/**
 * 
 * @export
 * @interface Content9Inner
 */
export interface Content9Inner {
    /**
     * 
     * @type {Array<MRTextBlockCitationsInner>}
     * @memberof Content9Inner
     */
    citations?: Array<MRTextBlockCitationsInner>;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    text: string;
    /**
     * 
     * @type {Content9InnerTypeEnum}
     * @memberof Content9Inner
     */
    type: Content9InnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    signature: string;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    thinking: string;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    id: string;
    /**
     * 
     * @type {Caller}
     * @memberof Content9Inner
     */
    caller?: Caller | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Content9Inner
     */
    input: { [key: string]: any; };
    /**
     * 
     * @type {Content9InnerNameEnum}
     * @memberof Content9Inner
     */
    name: Content9InnerNameEnum;
    /**
     * 
     * @type {Content6}
     * @memberof Content9Inner
     */
    content: Content6;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    toolUseId: string;
    /**
     * 
     * @type {string}
     * @memberof Content9Inner
     */
    fileId: string;
}


/**
 * @export
 */
export const Content9InnerTypeEnum = {
    Text: 'text',
    Thinking: 'thinking',
    RedactedThinking: 'redacted_thinking',
    ToolUse: 'tool_use',
    ServerToolUse: 'server_tool_use',
    WebSearchToolResult: 'web_search_tool_result',
    WebFetchToolResult: 'web_fetch_tool_result',
    CodeExecutionToolResult: 'code_execution_tool_result',
    BashCodeExecutionToolResult: 'bash_code_execution_tool_result',
    TextEditorCodeExecutionToolResult: 'text_editor_code_execution_tool_result',
    ToolSearchToolResult: 'tool_search_tool_result',
    ContainerUpload: 'container_upload'
} as const;
export type Content9InnerTypeEnum = typeof Content9InnerTypeEnum[keyof typeof Content9InnerTypeEnum];

/**
 * @export
 */
export const Content9InnerNameEnum = {
    WebSearch: 'web_search',
    WebFetch: 'web_fetch',
    CodeExecution: 'code_execution',
    BashCodeExecution: 'bash_code_execution',
    TextEditorCodeExecution: 'text_editor_code_execution',
    ToolSearchToolRegex: 'tool_search_tool_regex',
    ToolSearchToolBm25: 'tool_search_tool_bm25'
} as const;
export type Content9InnerNameEnum = typeof Content9InnerNameEnum[keyof typeof Content9InnerNameEnum];


/**
 * Check if a given object implements the Content9Inner interface.
 */
export function instanceOfContent9Inner(value: object): value is Content9Inner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('thinking' in value) || value['thinking'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if ((!('toolUseId' in value) && !('tool_use_id' in value)) || (value['toolUseId'] === undefined && value['tool_use_id'] === undefined)) return false;
    if ((!('fileId' in value) && !('file_id' in value)) || (value['fileId'] === undefined && value['file_id'] === undefined)) return false;
    return true;
}

export function Content9InnerFromJSON(json: any): Content9Inner {
    return Content9InnerFromJSONTyped(json, false);
}

export function Content9InnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content9Inner {
    if (json == null) {
        return json;
    }
    return {
        
        'citations': json['citations'] == null ? undefined : ((json['citations'] as Array<any>).map(MRTextBlockCitationsInnerFromJSON)),
        'text': json['text'],
        'type': json['type'],
        'signature': json['signature'],
        'thinking': json['thinking'],
        'data': json['data'],
        'id': json['id'],
        'caller': json['caller'] == null ? undefined : CallerFromJSON(json['caller']),
        'input': json['input'],
        'name': json['name'],
        'content': Content6FromJSON(json['content']),
        'toolUseId': json['tool_use_id'],
        'fileId': json['file_id'],
    };
}

export function Content9InnerToJSON(json: any): Content9Inner {
    return Content9InnerToJSONTyped(json, false);
}

export function Content9InnerToJSONTyped(value?: Content9Inner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'citations': value['citations'] == null ? undefined : ((value['citations'] as Array<any>).map(MRTextBlockCitationsInnerToJSON)),
        'text': value['text'],
        'type': value['type'],
        'signature': value['signature'],
        'thinking': value['thinking'],
        'data': value['data'],
        'id': value['id'],
        'caller': CallerToJSON(value['caller']),
        'input': value['input'],
        'name': value['name'],
        'content': Content6ToJSON(value['content']),
        'tool_use_id': value['toolUseId'],
        'file_id': value['fileId'],
    };
}

