/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MRBetaWebFetchBlock } from './MRBetaWebFetchBlock';
import {
    MRBetaWebFetchBlockFromJSON,
    MRBetaWebFetchBlockFromJSONTyped,
    MRBetaWebFetchBlockToJSON,
    MRBetaWebFetchBlockToJSONTyped,
} from './MRBetaWebFetchBlock';
import type { MRBetaDocumentBlock } from './MRBetaDocumentBlock';
import {
    MRBetaDocumentBlockFromJSON,
    MRBetaDocumentBlockFromJSONTyped,
    MRBetaDocumentBlockToJSON,
    MRBetaDocumentBlockToJSONTyped,
} from './MRBetaDocumentBlock';
import type { MRBetaWebFetchToolResultErrorBlock } from './MRBetaWebFetchToolResultErrorBlock';
import {
    MRBetaWebFetchToolResultErrorBlockFromJSON,
    MRBetaWebFetchToolResultErrorBlockFromJSONTyped,
    MRBetaWebFetchToolResultErrorBlockToJSON,
    MRBetaWebFetchToolResultErrorBlockToJSONTyped,
} from './MRBetaWebFetchToolResultErrorBlock';

/**
 * 
 * @export
 * @interface Content9
 */
export interface Content9 {
    /**
     * 
     * @type {Content9ErrorCodeEnum}
     * @memberof Content9
     */
    errorCode: Content9ErrorCodeEnum;
    /**
     * 
     * @type {Content9TypeEnum}
     * @memberof Content9
     */
    type: Content9TypeEnum;
    /**
     * 
     * @type {MRBetaDocumentBlock}
     * @memberof Content9
     */
    content: MRBetaDocumentBlock;
    /**
     * 
     * @type {string}
     * @memberof Content9
     */
    retrievedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Content9
     */
    url: string;
}


/**
 * @export
 */
export const Content9ErrorCodeEnum = {
    InvalidToolInput: 'invalid_tool_input',
    UrlTooLong: 'url_too_long',
    UrlNotAllowed: 'url_not_allowed',
    UrlNotAccessible: 'url_not_accessible',
    UnsupportedContentType: 'unsupported_content_type',
    TooManyRequests: 'too_many_requests',
    MaxUsesExceeded: 'max_uses_exceeded',
    Unavailable: 'unavailable'
} as const;
export type Content9ErrorCodeEnum = typeof Content9ErrorCodeEnum[keyof typeof Content9ErrorCodeEnum];

/**
 * @export
 */
export const Content9TypeEnum = {
    WebFetchToolResultError: 'web_fetch_tool_result_error',
    WebFetchResult: 'web_fetch_result'
} as const;
export type Content9TypeEnum = typeof Content9TypeEnum[keyof typeof Content9TypeEnum];


/**
 * Check if a given object implements the Content9 interface.
 */
export function instanceOfContent9(value: object): value is Content9 {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function Content9FromJSON(json: any): Content9 {
    return Content9FromJSONTyped(json, false);
}

export function Content9FromJSONTyped(json: any, ignoreDiscriminator: boolean): Content9 {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['error_code'],
        'type': json['type'],
        'content': MRBetaDocumentBlockFromJSON(json['content']),
        'retrievedAt': json['retrieved_at'] == null ? undefined : json['retrieved_at'],
        'url': json['url'],
    };
}

export function Content9ToJSON(json: any): Content9 {
    return Content9ToJSONTyped(json, false);
}

export function Content9ToJSONTyped(value?: Content9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': value['errorCode'],
        'type': value['type'],
        'content': MRBetaDocumentBlockToJSON(value['content']),
        'retrieved_at': value['retrievedAt'],
        'url': value['url'],
    };
}

