/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaToolSearchToolSearchResultBlock } from './MRBetaToolSearchToolSearchResultBlock.js';
import {
    MRBetaToolSearchToolSearchResultBlockFromJSON,
    MRBetaToolSearchToolSearchResultBlockFromJSONTyped,
    MRBetaToolSearchToolSearchResultBlockToJSON,
    MRBetaToolSearchToolSearchResultBlockToJSONTyped,
} from './MRBetaToolSearchToolSearchResultBlock.js';
import type { MRBetaToolSearchToolResultError } from './MRBetaToolSearchToolResultError.js';
import {
    MRBetaToolSearchToolResultErrorFromJSON,
    MRBetaToolSearchToolResultErrorFromJSONTyped,
    MRBetaToolSearchToolResultErrorToJSON,
    MRBetaToolSearchToolResultErrorToJSONTyped,
} from './MRBetaToolSearchToolResultError.js';
import type { MRBetaToolReferenceBlock } from './MRBetaToolReferenceBlock.js';
import {
    MRBetaToolReferenceBlockFromJSON,
    MRBetaToolReferenceBlockFromJSONTyped,
    MRBetaToolReferenceBlockToJSON,
    MRBetaToolReferenceBlockToJSONTyped,
} from './MRBetaToolReferenceBlock.js';

/**
 * 
 * @export
 * @interface Content9
 */
export interface Content9 {
    /**
     * 
     * @type {Content9ErrorCodeEnum}
     * @memberof Content9
     */
    errorCode: Content9ErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof Content9
     */
    errorMessage?: string;
    /**
     * 
     * @type {Content9TypeEnum}
     * @memberof Content9
     */
    type: Content9TypeEnum;
    /**
     * 
     * @type {Array<MRBetaToolReferenceBlock>}
     * @memberof Content9
     */
    toolReferences: Array<MRBetaToolReferenceBlock>;
}


/**
 * @export
 */
export const Content9ErrorCodeEnum = {
    InvalidToolInput: 'invalid_tool_input',
    Unavailable: 'unavailable',
    TooManyRequests: 'too_many_requests',
    ExecutionTimeExceeded: 'execution_time_exceeded'
} as const;
export type Content9ErrorCodeEnum = typeof Content9ErrorCodeEnum[keyof typeof Content9ErrorCodeEnum];

/**
 * @export
 */
export const Content9TypeEnum = {
    ToolSearchToolResultError: 'tool_search_tool_result_error',
    ToolSearchToolSearchResult: 'tool_search_tool_search_result'
} as const;
export type Content9TypeEnum = typeof Content9TypeEnum[keyof typeof Content9TypeEnum];


/**
 * Check if a given object implements the Content9 interface.
 */
export function instanceOfContent9(value: object): value is Content9 {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('toolReferences' in value) || value['toolReferences'] === undefined) return false;
    return true;
}

export function Content9FromJSON(json: any): Content9 {
    return Content9FromJSONTyped(json, false);
}

export function Content9FromJSONTyped(json: any, ignoreDiscriminator: boolean): Content9 {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['error_code'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'type': json['type'],
        'toolReferences': ((json['tool_references'] as Array<any>).map(MRBetaToolReferenceBlockFromJSON)),
    };
}

export function Content9ToJSON(json: any): Content9 {
    return Content9ToJSONTyped(json, false);
}

export function Content9ToJSONTyped(value?: Content9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': value['errorCode'],
        'error_message': value['errorMessage'],
        'type': value['type'],
        'tool_references': ((value['toolReferences'] as Array<any>).map(MRBetaToolReferenceBlockToJSON)),
    };
}

