/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MRTextEditorCodeExecutionViewResultBlock } from './MRTextEditorCodeExecutionViewResultBlock';
import {
    MRTextEditorCodeExecutionViewResultBlockFromJSON,
    MRTextEditorCodeExecutionViewResultBlockFromJSONTyped,
    MRTextEditorCodeExecutionViewResultBlockToJSON,
    MRTextEditorCodeExecutionViewResultBlockToJSONTyped,
} from './MRTextEditorCodeExecutionViewResultBlock';
import type { MRTextEditorCodeExecutionToolResultError } from './MRTextEditorCodeExecutionToolResultError';
import {
    MRTextEditorCodeExecutionToolResultErrorFromJSON,
    MRTextEditorCodeExecutionToolResultErrorFromJSONTyped,
    MRTextEditorCodeExecutionToolResultErrorToJSON,
    MRTextEditorCodeExecutionToolResultErrorToJSONTyped,
} from './MRTextEditorCodeExecutionToolResultError';
import type { MRTextEditorCodeExecutionStrReplaceResultBlock } from './MRTextEditorCodeExecutionStrReplaceResultBlock';
import {
    MRTextEditorCodeExecutionStrReplaceResultBlockFromJSON,
    MRTextEditorCodeExecutionStrReplaceResultBlockFromJSONTyped,
    MRTextEditorCodeExecutionStrReplaceResultBlockToJSON,
    MRTextEditorCodeExecutionStrReplaceResultBlockToJSONTyped,
} from './MRTextEditorCodeExecutionStrReplaceResultBlock';
import type { MRTextEditorCodeExecutionCreateResultBlock } from './MRTextEditorCodeExecutionCreateResultBlock';
import {
    MRTextEditorCodeExecutionCreateResultBlockFromJSON,
    MRTextEditorCodeExecutionCreateResultBlockFromJSONTyped,
    MRTextEditorCodeExecutionCreateResultBlockToJSON,
    MRTextEditorCodeExecutionCreateResultBlockToJSONTyped,
} from './MRTextEditorCodeExecutionCreateResultBlock';

/**
 * 
 * @export
 * @interface Content12
 */
export interface Content12 {
    /**
     * 
     * @type {Content12ErrorCodeEnum}
     * @memberof Content12
     */
    errorCode: Content12ErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof Content12
     */
    errorMessage?: string;
    /**
     * 
     * @type {Content12TypeEnum}
     * @memberof Content12
     */
    type: Content12TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Content12
     */
    content: string;
    /**
     * 
     * @type {Content12FileTypeEnum}
     * @memberof Content12
     */
    fileType: Content12FileTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    numLines?: number;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    startLine?: number;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    totalLines?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Content12
     */
    isFileUpdate: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Content12
     */
    lines?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    newLines?: number;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    newStart?: number;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    oldLines?: number;
    /**
     * 
     * @type {number}
     * @memberof Content12
     */
    oldStart?: number;
}


/**
 * @export
 */
export const Content12ErrorCodeEnum = {
    InvalidToolInput: 'invalid_tool_input',
    Unavailable: 'unavailable',
    TooManyRequests: 'too_many_requests',
    ExecutionTimeExceeded: 'execution_time_exceeded',
    FileNotFound: 'file_not_found'
} as const;
export type Content12ErrorCodeEnum = typeof Content12ErrorCodeEnum[keyof typeof Content12ErrorCodeEnum];

/**
 * @export
 */
export const Content12TypeEnum = {
    TextEditorCodeExecutionToolResultError: 'text_editor_code_execution_tool_result_error',
    TextEditorCodeExecutionViewResult: 'text_editor_code_execution_view_result',
    TextEditorCodeExecutionCreateResult: 'text_editor_code_execution_create_result',
    TextEditorCodeExecutionStrReplaceResult: 'text_editor_code_execution_str_replace_result'
} as const;
export type Content12TypeEnum = typeof Content12TypeEnum[keyof typeof Content12TypeEnum];

/**
 * @export
 */
export const Content12FileTypeEnum = {
    Text: 'text',
    Image: 'image',
    Pdf: 'pdf'
} as const;
export type Content12FileTypeEnum = typeof Content12FileTypeEnum[keyof typeof Content12FileTypeEnum];


/**
 * Check if a given object implements the Content12 interface.
 */
export function instanceOfContent12(value: object): value is Content12 {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('isFileUpdate' in value) || value['isFileUpdate'] === undefined) return false;
    return true;
}

export function Content12FromJSON(json: any): Content12 {
    return Content12FromJSONTyped(json, false);
}

export function Content12FromJSONTyped(json: any, ignoreDiscriminator: boolean): Content12 {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['error_code'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'type': json['type'],
        'content': json['content'],
        'fileType': json['file_type'],
        'numLines': json['num_lines'] == null ? undefined : json['num_lines'],
        'startLine': json['start_line'] == null ? undefined : json['start_line'],
        'totalLines': json['total_lines'] == null ? undefined : json['total_lines'],
        'isFileUpdate': json['is_file_update'],
        'lines': json['lines'] == null ? undefined : json['lines'],
        'newLines': json['new_lines'] == null ? undefined : json['new_lines'],
        'newStart': json['new_start'] == null ? undefined : json['new_start'],
        'oldLines': json['old_lines'] == null ? undefined : json['old_lines'],
        'oldStart': json['old_start'] == null ? undefined : json['old_start'],
    };
}

export function Content12ToJSON(json: any): Content12 {
    return Content12ToJSONTyped(json, false);
}

export function Content12ToJSONTyped(value?: Content12 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': value['errorCode'],
        'error_message': value['errorMessage'],
        'type': value['type'],
        'content': value['content'],
        'file_type': value['fileType'],
        'num_lines': value['numLines'],
        'start_line': value['startLine'],
        'total_lines': value['totalLines'],
        'is_file_update': value['isFileUpdate'],
        'lines': value['lines'],
        'new_lines': value['newLines'],
        'new_start': value['newStart'],
        'old_lines': value['oldLines'],
        'old_start': value['oldStart'],
    };
}

