/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for creating a new API key.
 * @export
 * @interface CreateKeyResponse
 */
export interface CreateKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    expiresAt: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateKeyResponse
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    keyName: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateKeyResponse
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    userId: string | null;
}

/**
 * Check if a given object implements the CreateKeyResponse interface.
 */
export function instanceOfCreateKeyResponse(value: object): value is CreateKeyResponse {
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('expiresAt' in value) && !('expires_at' in value)) || (value['expiresAt'] === undefined && value['expires_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('isActive' in value) && !('is_active' in value)) || (value['isActive'] === undefined && value['is_active'] === undefined)) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if ((!('keyName' in value) && !('key_name' in value)) || (value['keyName'] === undefined && value['key_name'] === undefined)) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    return true;
}

export function CreateKeyResponseFromJSON(json: any): CreateKeyResponse {
    return CreateKeyResponseFromJSONTyped(json, false);
}

export function CreateKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'expiresAt': json['expires_at'],
        'id': json['id'],
        'isActive': json['is_active'],
        'key': json['key'],
        'keyName': json['key_name'],
        'metadata': json['metadata'],
        'userId': json['user_id'],
    };
}

export function CreateKeyResponseToJSON(json: any): CreateKeyResponse {
    return CreateKeyResponseToJSONTyped(json, false);
}

export function CreateKeyResponseToJSONTyped(value?: CreateKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'is_active': value['isActive'],
        'key': value['key'],
        'key_name': value['keyName'],
        'metadata': value['metadata'],
        'user_id': value['userId'],
    };
}

