/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request model for creating a new budget.
 * @export
 * @interface CreateBudgetRequest
 */
export interface CreateBudgetRequest {
    /**
     * Budget duration in seconds (e.g., 86400 for daily, 604800 for weekly)
     * @type {number}
     * @memberof CreateBudgetRequest
     */
    budgetDurationSec?: number | null;
    /**
     * Maximum spending limit
     * @type {number}
     * @memberof CreateBudgetRequest
     */
    maxBudget?: number | null;
    /**
     * Admin-facing label for the budget
     * @type {string}
     * @memberof CreateBudgetRequest
     */
    name?: string | null;
    /**
     * Maximum requests over the period. Independent of max_budget; null is unlimited
     * @type {number}
     * @memberof CreateBudgetRequest
     */
    requestLimit?: number | null;
    /**
     * Reset on a UTC calendar boundary instead of a fixed number of seconds, which is the only way to express a calendar month. Mutually exclusive with budget_duration_sec
     * @type {CreateBudgetRequestResetAlignmentEnum}
     * @memberof CreateBudgetRequest
     */
    resetAlignment?: CreateBudgetRequestResetAlignmentEnum | null;
    /**
     * Maximum tokens over the period. Independent of max_budget; null is unlimited
     * @type {number}
     * @memberof CreateBudgetRequest
     */
    tokenLimit?: number | null;
}


/**
 * @export
 */
export const CreateBudgetRequestResetAlignmentEnum = {
    CalendarDay: 'calendar_day',
    CalendarWeek: 'calendar_week',
    CalendarMonth: 'calendar_month'
} as const;
export type CreateBudgetRequestResetAlignmentEnum = typeof CreateBudgetRequestResetAlignmentEnum[keyof typeof CreateBudgetRequestResetAlignmentEnum];


/**
 * Check if a given object implements the CreateBudgetRequest interface.
 */
export function instanceOfCreateBudgetRequest(value: object): value is CreateBudgetRequest {
    return true;
}

export function CreateBudgetRequestFromJSON(json: any): CreateBudgetRequest {
    return CreateBudgetRequestFromJSONTyped(json, false);
}

export function CreateBudgetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBudgetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'budgetDurationSec': json['budget_duration_sec'] == null ? undefined : json['budget_duration_sec'],
        'maxBudget': json['max_budget'] == null ? undefined : json['max_budget'],
        'name': json['name'] == null ? undefined : json['name'],
        'requestLimit': json['request_limit'] == null ? undefined : json['request_limit'],
        'resetAlignment': json['reset_alignment'] == null ? undefined : json['reset_alignment'],
        'tokenLimit': json['token_limit'] == null ? undefined : json['token_limit'],
    };
}

export function CreateBudgetRequestToJSON(json: any): CreateBudgetRequest {
    return CreateBudgetRequestToJSONTyped(json, false);
}

export function CreateBudgetRequestToJSONTyped(value?: CreateBudgetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget_duration_sec': value['budgetDurationSec'],
        'max_budget': value['maxBudget'],
        'name': value['name'],
        'request_limit': value['requestLimit'],
        'reset_alignment': value['resetAlignment'],
        'token_limit': value['tokenLimit'],
    };
}

