/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeploymentUserOrganizationPublic } from './DeploymentUserOrganizationPublic.js';
import {
    DeploymentUserOrganizationPublicFromJSON,
    DeploymentUserOrganizationPublicFromJSONTyped,
    DeploymentUserOrganizationPublicToJSON,
    DeploymentUserOrganizationPublicToJSONTyped,
} from './DeploymentUserOrganizationPublic.js';

/**
 * An identity on this deployment, whatever organization it belongs to.
 * 
 * Not ``ActiveOrganizationMemberPublic``: that shape is a *membership* joined
 * to an identity, scoped to one organization and hiding the suspended rows.
 * This one is the identity itself, and its ``organizations`` list carries every
 * membership at whatever status, because an account whose only membership is
 * suspended is precisely what an operator comes here to find.
 * 
 * ``is_bootstrap_operator`` and ``is_self`` are the two rows an operator may
 * not deactivate or demote, and they travel on the row so the page can disable
 * those controls rather than offering ones the server refuses. Neither is an
 * authorization: the server refuses either way. ``is_self`` is answered here
 * because nothing else the dashboard fetches names the caller's identity, so
 * without it the page could not tell which row is the reader's own.
 * @export
 * @interface DeploymentUserPublic
 */
export interface DeploymentUserPublic {
    /**
     * 
     * @type {Date}
     * @memberof DeploymentUserPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DeploymentUserPublic
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentUserPublic
     */
    fullName: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentUserPublic
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentUserPublic
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentUserPublic
     */
    isBootstrapOperator: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentUserPublic
     */
    isSelf: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentUserPublic
     */
    isSuperuser: boolean;
    /**
     * 
     * @type {Date}
     * @memberof DeploymentUserPublic
     */
    lastSignInAt: Date | null;
    /**
     * 
     * @type {Array<DeploymentUserOrganizationPublic>}
     * @memberof DeploymentUserPublic
     */
    organizations: Array<DeploymentUserOrganizationPublic>;
}

/**
 * Check if a given object implements the DeploymentUserPublic interface.
 */
export function instanceOfDeploymentUserPublic(value: object): value is DeploymentUserPublic {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('isBootstrapOperator' in value) || value['isBootstrapOperator'] === undefined) return false;
    if (!('isSelf' in value) || value['isSelf'] === undefined) return false;
    if (!('isSuperuser' in value) || value['isSuperuser'] === undefined) return false;
    if (!('lastSignInAt' in value) || value['lastSignInAt'] === undefined) return false;
    if (!('organizations' in value) || value['organizations'] === undefined) return false;
    return true;
}

export function DeploymentUserPublicFromJSON(json: any): DeploymentUserPublic {
    return DeploymentUserPublicFromJSONTyped(json, false);
}

export function DeploymentUserPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentUserPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'],
        'fullName': json['full_name'],
        'id': json['id'],
        'isActive': json['is_active'],
        'isBootstrapOperator': json['is_bootstrap_operator'],
        'isSelf': json['is_self'],
        'isSuperuser': json['is_superuser'],
        'lastSignInAt': (json['last_sign_in_at'] == null ? null : new Date(json['last_sign_in_at'])),
        'organizations': ((json['organizations'] as Array<any>).map(DeploymentUserOrganizationPublicFromJSON)),
    };
}

export function DeploymentUserPublicToJSON(json: any): DeploymentUserPublic {
    return DeploymentUserPublicToJSONTyped(json, false);
}

export function DeploymentUserPublicToJSONTyped(value?: DeploymentUserPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'email': value['email'],
        'full_name': value['fullName'],
        'id': value['id'],
        'is_active': value['isActive'],
        'is_bootstrap_operator': value['isBootstrapOperator'],
        'is_self': value['isSelf'],
        'is_superuser': value['isSuperuser'],
        'last_sign_in_at': value['lastSignInAt'] == null ? value['lastSignInAt'] : value['lastSignInAt'].toISOString(),
        'organizations': ((value['organizations'] as Array<any>).map(DeploymentUserOrganizationPublicToJSON)),
    };
}

