/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The usage information for the request.
 * @export
 * @interface EMBUsage
 */
export interface EMBUsage {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof EMBUsage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof EMBUsage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the EMBUsage interface.
 */
export function instanceOfEMBUsage(value: object): value is EMBUsage {
    if ((!('promptTokens' in value) && !('prompt_tokens' in value)) || (value['promptTokens'] === undefined && value['prompt_tokens'] === undefined)) return false;
    if ((!('totalTokens' in value) && !('total_tokens' in value)) || (value['totalTokens'] === undefined && value['total_tokens'] === undefined)) return false;
    return true;
}

export function EMBUsageFromJSON(json: any): EMBUsage {
    return EMBUsageFromJSONTyped(json, false);
}

export function EMBUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EMBUsage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'promptTokens': json['prompt_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function EMBUsageToJSON(json: any): EMBUsage {
    return EMBUsageToJSONTyped(json, false);
}

export function EMBUsageToJSONTyped(value?: EMBUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'prompt_tokens': value['promptTokens'],
        'total_tokens': value['totalTokens'],
    };
}

