/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single guardrail check the caller wants the gateway to enforce.
 * 
 * URL safety: when ``url`` is supplied it is validated at parse time with the
 * same SSRF guard used for MCP server URLs (loopback allowed by default for
 * same-host sidecars; gated by ``OTARI_MCP_ALLOW_LOOPBACK`` /
 * ``OTARI_MCP_ALLOW_PRIVATE_HOSTS``). Most deployments omit ``url`` and rely
 * on the operator-set ``OTARI_GUARDRAILS_URL`` instead.
 * @export
 * @interface GuardrailConfig
 */
export interface GuardrailConfig {
    /**
     * 
     * @type {GuardrailConfigModeEnum}
     * @memberof GuardrailConfig
     */
    mode?: GuardrailConfigModeEnum;
    /**
     * 
     * @type {Array<GuardrailConfigOnEnum>}
     * @memberof GuardrailConfig
     */
    on?: Array<GuardrailConfigOnEnum>;
    /**
     * 
     * @type {string}
     * @memberof GuardrailConfig
     */
    profile: string;
    /**
     * 
     * @type {string}
     * @memberof GuardrailConfig
     */
    url?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GuardrailConfig
     */
    validateKwargs?: { [key: string]: any; };
}


/**
 * @export
 */
export const GuardrailConfigModeEnum = {
    Block: 'block',
    Monitor: 'monitor'
} as const;
export type GuardrailConfigModeEnum = typeof GuardrailConfigModeEnum[keyof typeof GuardrailConfigModeEnum];

/**
 * @export
 */
export const GuardrailConfigOnEnum = {
    Input: 'input',
    Output: 'output'
} as const;
export type GuardrailConfigOnEnum = typeof GuardrailConfigOnEnum[keyof typeof GuardrailConfigOnEnum];


/**
 * Check if a given object implements the GuardrailConfig interface.
 */
export function instanceOfGuardrailConfig(value: object): value is GuardrailConfig {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function GuardrailConfigFromJSON(json: any): GuardrailConfig {
    return GuardrailConfigFromJSONTyped(json, false);
}

export function GuardrailConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuardrailConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
        'on': json['on'] == null ? undefined : json['on'],
        'profile': json['profile'],
        'url': json['url'] == null ? undefined : json['url'],
        'validateKwargs': json['validate_kwargs'] == null ? undefined : json['validate_kwargs'],
    };
}

export function GuardrailConfigToJSON(json: any): GuardrailConfig {
    return GuardrailConfigToJSONTyped(json, false);
}

export function GuardrailConfigToJSONTyped(value?: GuardrailConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'on': value['on'],
        'profile': value['profile'],
        'url': value['url'],
        'validate_kwargs': value['validateKwargs'],
    };
}

