/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the content or the URL of an image generated by the OpenAI API.
 * @export
 * @interface IMGImage
 */
export interface IMGImage {
    [key: string]: any | any;
    /**
     * Filter models by provider name
     * @type {string}
     * @memberof IMGImage
     */
    b64Json?: string | null;
    /**
     * Filter models by provider name
     * @type {string}
     * @memberof IMGImage
     */
    revisedPrompt?: string | null;
    /**
     * Filter models by provider name
     * @type {string}
     * @memberof IMGImage
     */
    url?: string | null;
}

/**
 * Check if a given object implements the IMGImage interface.
 */
export function instanceOfIMGImage(value: object): value is IMGImage {
    return true;
}

export function IMGImageFromJSON(json: any): IMGImage {
    return IMGImageFromJSONTyped(json, false);
}

export function IMGImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMGImage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'b64Json': json['b64_json'] == null ? undefined : json['b64_json'],
        'revisedPrompt': json['revised_prompt'] == null ? undefined : json['revised_prompt'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function IMGImageToJSON(json: any): IMGImage {
    return IMGImageToJSONTyped(json, false);
}

export function IMGImageToJSONTyped(value?: IMGImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'b64_json': value['b64Json'],
        'revised_prompt': value['revisedPrompt'],
        'url': value['url'],
    };
}

