/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IMGUsageInputTokensDetails } from './IMGUsageInputTokensDetails';
import {
    IMGUsageInputTokensDetailsFromJSON,
    IMGUsageInputTokensDetailsFromJSONTyped,
    IMGUsageInputTokensDetailsToJSON,
    IMGUsageInputTokensDetailsToJSONTyped,
} from './IMGUsageInputTokensDetails';
import type { IMGUsageOutputTokensDetails } from './IMGUsageOutputTokensDetails';
import {
    IMGUsageOutputTokensDetailsFromJSON,
    IMGUsageOutputTokensDetailsFromJSONTyped,
    IMGUsageOutputTokensDetailsToJSON,
    IMGUsageOutputTokensDetailsToJSONTyped,
} from './IMGUsageOutputTokensDetails';

/**
 * For `gpt-image-1` only, the token usage information for the image generation.
 * @export
 * @interface IMGUsage
 */
export interface IMGUsage {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof IMGUsage
     */
    inputTokens: number;
    /**
     * 
     * @type {IMGUsageInputTokensDetails}
     * @memberof IMGUsage
     */
    inputTokensDetails: IMGUsageInputTokensDetails;
    /**
     * 
     * @type {number}
     * @memberof IMGUsage
     */
    outputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof IMGUsage
     */
    totalTokens: number;
    /**
     * 
     * @type {IMGUsageOutputTokensDetails}
     * @memberof IMGUsage
     */
    outputTokensDetails?: IMGUsageOutputTokensDetails | null;
}

/**
 * Check if a given object implements the IMGUsage interface.
 */
export function instanceOfIMGUsage(value: object): value is IMGUsage {
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('inputTokensDetails' in value) || value['inputTokensDetails'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function IMGUsageFromJSON(json: any): IMGUsage {
    return IMGUsageFromJSONTyped(json, false);
}

export function IMGUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMGUsage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'inputTokens': json['input_tokens'],
        'inputTokensDetails': IMGUsageInputTokensDetailsFromJSON(json['input_tokens_details']),
        'outputTokens': json['output_tokens'],
        'totalTokens': json['total_tokens'],
        'outputTokensDetails': json['output_tokens_details'] == null ? undefined : IMGUsageOutputTokensDetailsFromJSON(json['output_tokens_details']),
    };
}

export function IMGUsageToJSON(json: any): IMGUsage {
    return IMGUsageToJSONTyped(json, false);
}

export function IMGUsageToJSONTyped(value?: IMGUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'input_tokens': value['inputTokens'],
        'input_tokens_details': IMGUsageInputTokensDetailsToJSON(value['inputTokensDetails']),
        'output_tokens': value['outputTokens'],
        'total_tokens': value['totalTokens'],
        'output_tokens_details': IMGUsageOutputTokensDetailsToJSON(value['outputTokensDetails']),
    };
}

