/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { WorkspaceAssignmentRequest } from './WorkspaceAssignmentRequest.js';
import {
    WorkspaceAssignmentRequestFromJSON,
    WorkspaceAssignmentRequestFromJSONTyped,
    WorkspaceAssignmentRequestToJSON,
    WorkspaceAssignmentRequestToJSONTyped,
} from './WorkspaceAssignmentRequest.js';

/**
 * Invite an address to the caller's organization, optionally into workspaces at once.
 * 
 * Field-for-field ``ActiveOrganizationMemberCreateRequest``'s twin: the two
 * requests ask for the same thing and differ only in what creating one
 * produces (this lands ``invited`` and emails a link; that lands ``active``
 * immediately).
 * @export
 * @interface InviteOrganizationMemberRequest
 */
export interface InviteOrganizationMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof InviteOrganizationMemberRequest
     */
    email: string;
    /**
     * 
     * @type {InviteOrganizationMemberRequestRoleEnum}
     * @memberof InviteOrganizationMemberRequest
     */
    role?: InviteOrganizationMemberRequestRoleEnum;
    /**
     * 
     * @type {Array<WorkspaceAssignmentRequest>}
     * @memberof InviteOrganizationMemberRequest
     */
    workspaceAssignments?: Array<WorkspaceAssignmentRequest> | null;
}


/**
 * @export
 */
export const InviteOrganizationMemberRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member',
    Viewer: 'viewer'
} as const;
export type InviteOrganizationMemberRequestRoleEnum = typeof InviteOrganizationMemberRequestRoleEnum[keyof typeof InviteOrganizationMemberRequestRoleEnum];


/**
 * Check if a given object implements the InviteOrganizationMemberRequest interface.
 */
export function instanceOfInviteOrganizationMemberRequest(value: object): value is InviteOrganizationMemberRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function InviteOrganizationMemberRequestFromJSON(json: any): InviteOrganizationMemberRequest {
    return InviteOrganizationMemberRequestFromJSONTyped(json, false);
}

export function InviteOrganizationMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteOrganizationMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'] == null ? undefined : json['role'],
        'workspaceAssignments': json['workspace_assignments'] == null ? undefined : ((json['workspace_assignments'] as Array<any>).map(WorkspaceAssignmentRequestFromJSON)),
    };
}

export function InviteOrganizationMemberRequestToJSON(json: any): InviteOrganizationMemberRequest {
    return InviteOrganizationMemberRequestToJSONTyped(json, false);
}

export function InviteOrganizationMemberRequestToJSONTyped(value?: InviteOrganizationMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
        'workspace_assignments': value['workspaceAssignments'] == null ? undefined : ((value['workspaceAssignments'] as Array<any>).map(WorkspaceAssignmentRequestToJSON)),
    };
}

