/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MemberCeilingPublic } from './MemberCeilingPublic.js';
import {
    MemberCeilingPublicFromJSON,
    MemberCeilingPublicFromJSONTyped,
    MemberCeilingPublicToJSON,
    MemberCeilingPublicToJSONTyped,
} from './MemberCeilingPublic.js';

/**
 * One workspace a member is in, with their role and ceiling there.
 * 
 * A ceiling is keyed on the *membership*, not on the person, so a member of two
 * workspaces has two of them. The membership id is carried in its own right
 * rather than read back off the ceiling, because it is needed precisely when
 * there is no ceiling yet and one is about to be created.
 * @export
 * @interface MemberWorkspacePlacementPublic
 */
export interface MemberWorkspacePlacementPublic {
    /**
     * 
     * @type {MemberCeilingPublic}
     * @memberof MemberWorkspacePlacementPublic
     */
    ceiling?: MemberCeilingPublic | null;
    /**
     * 
     * @type {string}
     * @memberof MemberWorkspacePlacementPublic
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof MemberWorkspacePlacementPublic
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof MemberWorkspacePlacementPublic
     */
    workspaceMemberId: string;
    /**
     * 
     * @type {string}
     * @memberof MemberWorkspacePlacementPublic
     */
    workspaceName: string;
}

/**
 * Check if a given object implements the MemberWorkspacePlacementPublic interface.
 */
export function instanceOfMemberWorkspacePlacementPublic(value: object): value is MemberWorkspacePlacementPublic {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('workspaceMemberId' in value) || value['workspaceMemberId'] === undefined) return false;
    if (!('workspaceName' in value) || value['workspaceName'] === undefined) return false;
    return true;
}

export function MemberWorkspacePlacementPublicFromJSON(json: any): MemberWorkspacePlacementPublic {
    return MemberWorkspacePlacementPublicFromJSONTyped(json, false);
}

export function MemberWorkspacePlacementPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberWorkspacePlacementPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'ceiling': json['ceiling'] == null ? undefined : MemberCeilingPublicFromJSON(json['ceiling']),
        'role': json['role'],
        'workspaceId': json['workspace_id'],
        'workspaceMemberId': json['workspace_member_id'],
        'workspaceName': json['workspace_name'],
    };
}

export function MemberWorkspacePlacementPublicToJSON(json: any): MemberWorkspacePlacementPublic {
    return MemberWorkspacePlacementPublicToJSONTyped(json, false);
}

export function MemberWorkspacePlacementPublicToJSONTyped(value?: MemberWorkspacePlacementPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ceiling': MemberCeilingPublicToJSON(value['ceiling']),
        'role': value['role'],
        'workspace_id': value['workspaceId'],
        'workspace_member_id': value['workspaceMemberId'],
        'workspace_name': value['workspaceName'],
    };
}

