/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MRAnthropicTypesThinkingBlockThinkingBlock
 */
export interface MRAnthropicTypesThinkingBlockThinkingBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MRAnthropicTypesThinkingBlockThinkingBlock
     */
    signature: string;
    /**
     * 
     * @type {string}
     * @memberof MRAnthropicTypesThinkingBlockThinkingBlock
     */
    thinking: string;
    /**
     * 
     * @type {MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum}
     * @memberof MRAnthropicTypesThinkingBlockThinkingBlock
     */
    type: MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum;
}


/**
 * @export
 */
export const MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum = {
    Thinking: 'thinking'
} as const;
export type MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum = typeof MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum[keyof typeof MRAnthropicTypesThinkingBlockThinkingBlockTypeEnum];


/**
 * Check if a given object implements the MRAnthropicTypesThinkingBlockThinkingBlock interface.
 */
export function instanceOfMRAnthropicTypesThinkingBlockThinkingBlock(value: object): value is MRAnthropicTypesThinkingBlockThinkingBlock {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('thinking' in value) || value['thinking'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRAnthropicTypesThinkingBlockThinkingBlockFromJSON(json: any): MRAnthropicTypesThinkingBlockThinkingBlock {
    return MRAnthropicTypesThinkingBlockThinkingBlockFromJSONTyped(json, false);
}

export function MRAnthropicTypesThinkingBlockThinkingBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRAnthropicTypesThinkingBlockThinkingBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'signature': json['signature'],
        'thinking': json['thinking'],
        'type': json['type'],
    };
}

export function MRAnthropicTypesThinkingBlockThinkingBlockToJSON(json: any): MRAnthropicTypesThinkingBlockThinkingBlock {
    return MRAnthropicTypesThinkingBlockThinkingBlockToJSONTyped(json, false);
}

export function MRAnthropicTypesThinkingBlockThinkingBlockToJSONTyped(value?: MRAnthropicTypesThinkingBlockThinkingBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'signature': value['signature'],
        'thinking': value['thinking'],
        'type': value['type'],
    };
}

