/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRBase64PDFSource
 */
export interface MRBase64PDFSource {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MRBase64PDFSource
     */
    data: string;
    /**
     * 
     * @type {MRBase64PDFSourceMediaTypeEnum}
     * @memberof MRBase64PDFSource
     */
    mediaType: MRBase64PDFSourceMediaTypeEnum;
    /**
     * 
     * @type {MRBase64PDFSourceTypeEnum}
     * @memberof MRBase64PDFSource
     */
    type: MRBase64PDFSourceTypeEnum;
}


/**
 * @export
 */
export const MRBase64PDFSourceMediaTypeEnum = {
    ApplicationPdf: 'application/pdf'
} as const;
export type MRBase64PDFSourceMediaTypeEnum = typeof MRBase64PDFSourceMediaTypeEnum[keyof typeof MRBase64PDFSourceMediaTypeEnum];

/**
 * @export
 */
export const MRBase64PDFSourceTypeEnum = {
    Base64: 'base64'
} as const;
export type MRBase64PDFSourceTypeEnum = typeof MRBase64PDFSourceTypeEnum[keyof typeof MRBase64PDFSourceTypeEnum];


/**
 * Check if a given object implements the MRBase64PDFSource interface.
 */
export function instanceOfMRBase64PDFSource(value: object): value is MRBase64PDFSource {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('mediaType' in value) && !('media_type' in value)) || (value['mediaType'] === undefined && value['media_type'] === undefined)) return false;
    if (value['mediaType'] !== 'application/pdf' && value['media_type'] !== 'application/pdf') return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'base64') return false;
    
    return true;
}

export function MRBase64PDFSourceFromJSON(json: any): MRBase64PDFSource {
    return MRBase64PDFSourceFromJSONTyped(json, false);
}

export function MRBase64PDFSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBase64PDFSource {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': json['data'],
        'mediaType': json['media_type'],
        'type': json['type'],
    };
}

export function MRBase64PDFSourceToJSON(json: any): MRBase64PDFSource {
    return MRBase64PDFSourceToJSONTyped(json, false);
}

export function MRBase64PDFSourceToJSONTyped(value?: MRBase64PDFSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': value['data'],
        'media_type': value['mediaType'],
        'type': value['type'],
    };
}

