/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRBetaCitationCharLocation
 */
export interface MRBetaCitationCharLocation {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MRBetaCitationCharLocation
     */
    citedText: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaCitationCharLocation
     */
    documentIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaCitationCharLocation
     */
    documentTitle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MRBetaCitationCharLocation
     */
    endCharIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaCitationCharLocation
     */
    fileId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MRBetaCitationCharLocation
     */
    startCharIndex: number;
    /**
     * 
     * @type {MRBetaCitationCharLocationTypeEnum}
     * @memberof MRBetaCitationCharLocation
     */
    type: MRBetaCitationCharLocationTypeEnum;
}


/**
 * @export
 */
export const MRBetaCitationCharLocationTypeEnum = {
    CharLocation: 'char_location'
} as const;
export type MRBetaCitationCharLocationTypeEnum = typeof MRBetaCitationCharLocationTypeEnum[keyof typeof MRBetaCitationCharLocationTypeEnum];


/**
 * Check if a given object implements the MRBetaCitationCharLocation interface.
 */
export function instanceOfMRBetaCitationCharLocation(value: object): value is MRBetaCitationCharLocation {
    if (!('citedText' in value) || value['citedText'] === undefined) return false;
    if (!('documentIndex' in value) || value['documentIndex'] === undefined) return false;
    if (!('endCharIndex' in value) || value['endCharIndex'] === undefined) return false;
    if (!('startCharIndex' in value) || value['startCharIndex'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaCitationCharLocationFromJSON(json: any): MRBetaCitationCharLocation {
    return MRBetaCitationCharLocationFromJSONTyped(json, false);
}

export function MRBetaCitationCharLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaCitationCharLocation {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'citedText': json['cited_text'],
        'documentIndex': json['document_index'],
        'documentTitle': json['document_title'] == null ? undefined : json['document_title'],
        'endCharIndex': json['end_char_index'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'startCharIndex': json['start_char_index'],
        'type': json['type'],
    };
}

export function MRBetaCitationCharLocationToJSON(json: any): MRBetaCitationCharLocation {
    return MRBetaCitationCharLocationToJSONTyped(json, false);
}

export function MRBetaCitationCharLocationToJSONTyped(value?: MRBetaCitationCharLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'cited_text': value['citedText'],
        'document_index': value['documentIndex'],
        'document_title': value['documentTitle'],
        'end_char_index': value['endCharIndex'],
        'file_id': value['fileId'],
        'start_char_index': value['startCharIndex'],
        'type': value['type'],
    };
}

