/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaCitationContentBlockLocation } from './MRBetaCitationContentBlockLocation.js';
import {
    MRBetaCitationContentBlockLocationFromJSON,
    MRBetaCitationContentBlockLocationFromJSONTyped,
    MRBetaCitationContentBlockLocationToJSON,
    MRBetaCitationContentBlockLocationToJSONTyped,
} from './MRBetaCitationContentBlockLocation.js';
import type { MRBetaCitationPageLocation } from './MRBetaCitationPageLocation.js';
import {
    MRBetaCitationPageLocationFromJSON,
    MRBetaCitationPageLocationFromJSONTyped,
    MRBetaCitationPageLocationToJSON,
    MRBetaCitationPageLocationToJSONTyped,
} from './MRBetaCitationPageLocation.js';
import type { MRBetaCitationSearchResultLocation } from './MRBetaCitationSearchResultLocation.js';
import {
    MRBetaCitationSearchResultLocationFromJSON,
    MRBetaCitationSearchResultLocationFromJSONTyped,
    MRBetaCitationSearchResultLocationToJSON,
    MRBetaCitationSearchResultLocationToJSONTyped,
} from './MRBetaCitationSearchResultLocation.js';
import type { MRBetaCitationsWebSearchResultLocation } from './MRBetaCitationsWebSearchResultLocation.js';
import {
    MRBetaCitationsWebSearchResultLocationFromJSON,
    MRBetaCitationsWebSearchResultLocationFromJSONTyped,
    MRBetaCitationsWebSearchResultLocationToJSON,
    MRBetaCitationsWebSearchResultLocationToJSONTyped,
} from './MRBetaCitationsWebSearchResultLocation.js';
import type { MRBetaCitationCharLocation } from './MRBetaCitationCharLocation.js';
import {
    MRBetaCitationCharLocationFromJSON,
    MRBetaCitationCharLocationFromJSONTyped,
    MRBetaCitationCharLocationToJSON,
    MRBetaCitationCharLocationToJSONTyped,
} from './MRBetaCitationCharLocation.js';

/**
 * 
 * @export
 * @interface MRBetaTextBlockCitationsInner
 */
export interface MRBetaTextBlockCitationsInner {
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    citedText: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    documentIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    documentTitle?: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    endCharIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    fileId?: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    startCharIndex: number;
    /**
     * 
     * @type {MRBetaTextBlockCitationsInnerTypeEnum}
     * @memberof MRBetaTextBlockCitationsInner
     */
    type: MRBetaTextBlockCitationsInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    endPageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    startPageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    endBlockIndex: number;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    startBlockIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    encryptedIndex: string;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaTextBlockCitationsInner
     */
    searchResultIndex: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaTextBlockCitationsInner
     */
    source: string;
}


/**
 * @export
 */
export const MRBetaTextBlockCitationsInnerTypeEnum = {
    CharLocation: 'char_location',
    PageLocation: 'page_location',
    ContentBlockLocation: 'content_block_location',
    WebSearchResultLocation: 'web_search_result_location',
    SearchResultLocation: 'search_result_location'
} as const;
export type MRBetaTextBlockCitationsInnerTypeEnum = typeof MRBetaTextBlockCitationsInnerTypeEnum[keyof typeof MRBetaTextBlockCitationsInnerTypeEnum];


/**
 * Check if a given object implements the MRBetaTextBlockCitationsInner interface.
 */
export function instanceOfMRBetaTextBlockCitationsInner(value: object): value is MRBetaTextBlockCitationsInner {
    if (!('citedText' in value) || value['citedText'] === undefined) return false;
    if (!('documentIndex' in value) || value['documentIndex'] === undefined) return false;
    if (!('endCharIndex' in value) || value['endCharIndex'] === undefined) return false;
    if (!('startCharIndex' in value) || value['startCharIndex'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('endPageNumber' in value) || value['endPageNumber'] === undefined) return false;
    if (!('startPageNumber' in value) || value['startPageNumber'] === undefined) return false;
    if (!('endBlockIndex' in value) || value['endBlockIndex'] === undefined) return false;
    if (!('startBlockIndex' in value) || value['startBlockIndex'] === undefined) return false;
    if (!('encryptedIndex' in value) || value['encryptedIndex'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('searchResultIndex' in value) || value['searchResultIndex'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function MRBetaTextBlockCitationsInnerFromJSON(json: any): MRBetaTextBlockCitationsInner {
    return MRBetaTextBlockCitationsInnerFromJSONTyped(json, false);
}

export function MRBetaTextBlockCitationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaTextBlockCitationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'citedText': json['cited_text'],
        'documentIndex': json['document_index'],
        'documentTitle': json['document_title'] == null ? undefined : json['document_title'],
        'endCharIndex': json['end_char_index'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'startCharIndex': json['start_char_index'],
        'type': json['type'],
        'endPageNumber': json['end_page_number'],
        'startPageNumber': json['start_page_number'],
        'endBlockIndex': json['end_block_index'],
        'startBlockIndex': json['start_block_index'],
        'encryptedIndex': json['encrypted_index'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'],
        'searchResultIndex': json['search_result_index'],
        'source': json['source'],
    };
}

export function MRBetaTextBlockCitationsInnerToJSON(json: any): MRBetaTextBlockCitationsInner {
    return MRBetaTextBlockCitationsInnerToJSONTyped(json, false);
}

export function MRBetaTextBlockCitationsInnerToJSONTyped(value?: MRBetaTextBlockCitationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cited_text': value['citedText'],
        'document_index': value['documentIndex'],
        'document_title': value['documentTitle'],
        'end_char_index': value['endCharIndex'],
        'file_id': value['fileId'],
        'start_char_index': value['startCharIndex'],
        'type': value['type'],
        'end_page_number': value['endPageNumber'],
        'start_page_number': value['startPageNumber'],
        'end_block_index': value['endBlockIndex'],
        'start_block_index': value['startBlockIndex'],
        'encrypted_index': value['encryptedIndex'],
        'title': value['title'],
        'url': value['url'],
        'search_result_index': value['searchResultIndex'],
        'source': value['source'],
    };
}

