/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MRBetaCacheMissPreviousMessageNotFound
 */
export interface MRBetaCacheMissPreviousMessageNotFound {
    [key: string]: any | any;
    /**
     * 
     * @type {MRBetaCacheMissPreviousMessageNotFoundTypeEnum}
     * @memberof MRBetaCacheMissPreviousMessageNotFound
     */
    type: MRBetaCacheMissPreviousMessageNotFoundTypeEnum;
}


/**
 * @export
 */
export const MRBetaCacheMissPreviousMessageNotFoundTypeEnum = {
    PreviousMessageNotFound: 'previous_message_not_found'
} as const;
export type MRBetaCacheMissPreviousMessageNotFoundTypeEnum = typeof MRBetaCacheMissPreviousMessageNotFoundTypeEnum[keyof typeof MRBetaCacheMissPreviousMessageNotFoundTypeEnum];


/**
 * Check if a given object implements the MRBetaCacheMissPreviousMessageNotFound interface.
 */
export function instanceOfMRBetaCacheMissPreviousMessageNotFound(value: object): value is MRBetaCacheMissPreviousMessageNotFound {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaCacheMissPreviousMessageNotFoundFromJSON(json: any): MRBetaCacheMissPreviousMessageNotFound {
    return MRBetaCacheMissPreviousMessageNotFoundFromJSONTyped(json, false);
}

export function MRBetaCacheMissPreviousMessageNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaCacheMissPreviousMessageNotFound {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
    };
}

export function MRBetaCacheMissPreviousMessageNotFoundToJSON(json: any): MRBetaCacheMissPreviousMessageNotFound {
    return MRBetaCacheMissPreviousMessageNotFoundToJSONTyped(json, false);
}

export function MRBetaCacheMissPreviousMessageNotFoundToJSONTyped(value?: MRBetaCacheMissPreviousMessageNotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
    };
}

