/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * The `from` model declined for policy reasons.
 * @export
 * @interface MRBetaFallbackRefusalTrigger
 */
export interface MRBetaFallbackRefusalTrigger {
    [key: string]: any | any;
    /**
     * 
     * @type {MRBetaFallbackRefusalTriggerCategoryEnum}
     * @memberof MRBetaFallbackRefusalTrigger
     */
    category?: MRBetaFallbackRefusalTriggerCategoryEnum | null;
    /**
     * 
     * @type {MRBetaFallbackRefusalTriggerTypeEnum}
     * @memberof MRBetaFallbackRefusalTrigger
     */
    type: MRBetaFallbackRefusalTriggerTypeEnum;
}


/**
 * @export
 */
export const MRBetaFallbackRefusalTriggerCategoryEnum = {
    Cyber: 'cyber',
    Bio: 'bio',
    FrontierLlm: 'frontier_llm',
    ReasoningExtraction: 'reasoning_extraction',
    GeneralHarms: 'general_harms'
} as const;
export type MRBetaFallbackRefusalTriggerCategoryEnum = typeof MRBetaFallbackRefusalTriggerCategoryEnum[keyof typeof MRBetaFallbackRefusalTriggerCategoryEnum];

/**
 * @export
 */
export const MRBetaFallbackRefusalTriggerTypeEnum = {
    Refusal: 'refusal'
} as const;
export type MRBetaFallbackRefusalTriggerTypeEnum = typeof MRBetaFallbackRefusalTriggerTypeEnum[keyof typeof MRBetaFallbackRefusalTriggerTypeEnum];


/**
 * Check if a given object implements the MRBetaFallbackRefusalTrigger interface.
 */
export function instanceOfMRBetaFallbackRefusalTrigger(value: object): value is MRBetaFallbackRefusalTrigger {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaFallbackRefusalTriggerFromJSON(json: any): MRBetaFallbackRefusalTrigger {
    return MRBetaFallbackRefusalTriggerFromJSONTyped(json, false);
}

export function MRBetaFallbackRefusalTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaFallbackRefusalTrigger {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'category': json['category'] == null ? undefined : json['category'],
        'type': json['type'],
    };
}

export function MRBetaFallbackRefusalTriggerToJSON(json: any): MRBetaFallbackRefusalTrigger {
    return MRBetaFallbackRefusalTriggerToJSONTyped(json, false);
}

export function MRBetaFallbackRefusalTriggerToJSONTyped(value?: MRBetaFallbackRefusalTrigger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'category': value['category'],
        'type': value['type'],
    };
}

