/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Caller } from './Caller.js';
import {
    CallerFromJSON,
    CallerFromJSONTyped,
    CallerToJSON,
    CallerToJSONTyped,
} from './Caller.js';
import type { Content10 } from './Content10.js';
import {
    Content10FromJSON,
    Content10FromJSONTyped,
    Content10ToJSON,
    Content10ToJSONTyped,
} from './Content10.js';

/**
 * 
 * @export
 * @interface MRBetaWebFetchToolResultBlock
 */
export interface MRBetaWebFetchToolResultBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {Content10}
     * @memberof MRBetaWebFetchToolResultBlock
     */
    content: Content10;
    /**
     * 
     * @type {string}
     * @memberof MRBetaWebFetchToolResultBlock
     */
    toolUseId: string;
    /**
     * 
     * @type {MRBetaWebFetchToolResultBlockTypeEnum}
     * @memberof MRBetaWebFetchToolResultBlock
     */
    type: MRBetaWebFetchToolResultBlockTypeEnum;
    /**
     * 
     * @type {Caller}
     * @memberof MRBetaWebFetchToolResultBlock
     */
    caller?: Caller | null;
}


/**
 * @export
 */
export const MRBetaWebFetchToolResultBlockTypeEnum = {
    WebFetchToolResult: 'web_fetch_tool_result'
} as const;
export type MRBetaWebFetchToolResultBlockTypeEnum = typeof MRBetaWebFetchToolResultBlockTypeEnum[keyof typeof MRBetaWebFetchToolResultBlockTypeEnum];


/**
 * Check if a given object implements the MRBetaWebFetchToolResultBlock interface.
 */
export function instanceOfMRBetaWebFetchToolResultBlock(value: object): value is MRBetaWebFetchToolResultBlock {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('toolUseId' in value) || value['toolUseId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaWebFetchToolResultBlockFromJSON(json: any): MRBetaWebFetchToolResultBlock {
    return MRBetaWebFetchToolResultBlockFromJSONTyped(json, false);
}

export function MRBetaWebFetchToolResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaWebFetchToolResultBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'content': Content10FromJSON(json['content']),
        'toolUseId': json['tool_use_id'],
        'type': json['type'],
        'caller': json['caller'] == null ? undefined : CallerFromJSON(json['caller']),
    };
}

export function MRBetaWebFetchToolResultBlockToJSON(json: any): MRBetaWebFetchToolResultBlock {
    return MRBetaWebFetchToolResultBlockToJSONTyped(json, false);
}

export function MRBetaWebFetchToolResultBlockToJSONTyped(value?: MRBetaWebFetchToolResultBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'content': Content10ToJSON(value['content']),
        'tool_use_id': value['toolUseId'],
        'type': value['type'],
        'caller': CallerToJSON(value['caller']),
    };
}

