/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaToolReferenceBlock } from './MRBetaToolReferenceBlock.js';
import {
    MRBetaToolReferenceBlockFromJSON,
    MRBetaToolReferenceBlockFromJSONTyped,
    MRBetaToolReferenceBlockToJSON,
    MRBetaToolReferenceBlockToJSONTyped,
} from './MRBetaToolReferenceBlock.js';

/**
 * 
 * @export
 * @interface MRBetaToolSearchToolSearchResultBlock
 */
export interface MRBetaToolSearchToolSearchResultBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<MRBetaToolReferenceBlock>}
     * @memberof MRBetaToolSearchToolSearchResultBlock
     */
    toolReferences: Array<MRBetaToolReferenceBlock>;
    /**
     * 
     * @type {MRBetaToolSearchToolSearchResultBlockTypeEnum}
     * @memberof MRBetaToolSearchToolSearchResultBlock
     */
    type: MRBetaToolSearchToolSearchResultBlockTypeEnum;
}


/**
 * @export
 */
export const MRBetaToolSearchToolSearchResultBlockTypeEnum = {
    ToolSearchToolSearchResult: 'tool_search_tool_search_result'
} as const;
export type MRBetaToolSearchToolSearchResultBlockTypeEnum = typeof MRBetaToolSearchToolSearchResultBlockTypeEnum[keyof typeof MRBetaToolSearchToolSearchResultBlockTypeEnum];


/**
 * Check if a given object implements the MRBetaToolSearchToolSearchResultBlock interface.
 */
export function instanceOfMRBetaToolSearchToolSearchResultBlock(value: object): value is MRBetaToolSearchToolSearchResultBlock {
    if (!('toolReferences' in value) || value['toolReferences'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaToolSearchToolSearchResultBlockFromJSON(json: any): MRBetaToolSearchToolSearchResultBlock {
    return MRBetaToolSearchToolSearchResultBlockFromJSONTyped(json, false);
}

export function MRBetaToolSearchToolSearchResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaToolSearchToolSearchResultBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'toolReferences': ((json['tool_references'] as Array<any>).map(MRBetaToolReferenceBlockFromJSON)),
        'type': json['type'],
    };
}

export function MRBetaToolSearchToolSearchResultBlockToJSON(json: any): MRBetaToolSearchToolSearchResultBlock {
    return MRBetaToolSearchToolSearchResultBlockToJSONTyped(json, false);
}

export function MRBetaToolSearchToolSearchResultBlockToJSONTyped(value?: MRBetaToolSearchToolSearchResultBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'tool_references': ((value['toolReferences'] as Array<any>).map(MRBetaToolReferenceBlockToJSON)),
        'type': value['type'],
    };
}

