/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaCodeExecutionOutputBlock } from './MRBetaCodeExecutionOutputBlock.js';
import {
    MRBetaCodeExecutionOutputBlockFromJSON,
    MRBetaCodeExecutionOutputBlockFromJSONTyped,
    MRBetaCodeExecutionOutputBlockToJSON,
    MRBetaCodeExecutionOutputBlockToJSONTyped,
} from './MRBetaCodeExecutionOutputBlock.js';

/**
 * Code execution result with encrypted stdout for PFC + web_search results.
 * @export
 * @interface MRBetaEncryptedCodeExecutionResultBlock
 */
export interface MRBetaEncryptedCodeExecutionResultBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<MRBetaCodeExecutionOutputBlock>}
     * @memberof MRBetaEncryptedCodeExecutionResultBlock
     */
    content: Array<MRBetaCodeExecutionOutputBlock>;
    /**
     * 
     * @type {string}
     * @memberof MRBetaEncryptedCodeExecutionResultBlock
     */
    encryptedStdout: string;
    /**
     * 
     * @type {number}
     * @memberof MRBetaEncryptedCodeExecutionResultBlock
     */
    returnCode: number;
    /**
     * 
     * @type {string}
     * @memberof MRBetaEncryptedCodeExecutionResultBlock
     */
    stderr: string;
    /**
     * 
     * @type {MRBetaEncryptedCodeExecutionResultBlockTypeEnum}
     * @memberof MRBetaEncryptedCodeExecutionResultBlock
     */
    type: MRBetaEncryptedCodeExecutionResultBlockTypeEnum;
}


/**
 * @export
 */
export const MRBetaEncryptedCodeExecutionResultBlockTypeEnum = {
    EncryptedCodeExecutionResult: 'encrypted_code_execution_result'
} as const;
export type MRBetaEncryptedCodeExecutionResultBlockTypeEnum = typeof MRBetaEncryptedCodeExecutionResultBlockTypeEnum[keyof typeof MRBetaEncryptedCodeExecutionResultBlockTypeEnum];


/**
 * Check if a given object implements the MRBetaEncryptedCodeExecutionResultBlock interface.
 */
export function instanceOfMRBetaEncryptedCodeExecutionResultBlock(value: object): value is MRBetaEncryptedCodeExecutionResultBlock {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('encryptedStdout' in value) || value['encryptedStdout'] === undefined) return false;
    if (!('returnCode' in value) || value['returnCode'] === undefined) return false;
    if (!('stderr' in value) || value['stderr'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaEncryptedCodeExecutionResultBlockFromJSON(json: any): MRBetaEncryptedCodeExecutionResultBlock {
    return MRBetaEncryptedCodeExecutionResultBlockFromJSONTyped(json, false);
}

export function MRBetaEncryptedCodeExecutionResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaEncryptedCodeExecutionResultBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'content': ((json['content'] as Array<any>).map(MRBetaCodeExecutionOutputBlockFromJSON)),
        'encryptedStdout': json['encrypted_stdout'],
        'returnCode': json['return_code'],
        'stderr': json['stderr'],
        'type': json['type'],
    };
}

export function MRBetaEncryptedCodeExecutionResultBlockToJSON(json: any): MRBetaEncryptedCodeExecutionResultBlock {
    return MRBetaEncryptedCodeExecutionResultBlockToJSONTyped(json, false);
}

export function MRBetaEncryptedCodeExecutionResultBlockToJSONTyped(value?: MRBetaEncryptedCodeExecutionResultBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'content': ((value['content'] as Array<any>).map(MRBetaCodeExecutionOutputBlockToJSON)),
        'encrypted_stdout': value['encryptedStdout'],
        'return_code': value['returnCode'],
        'stderr': value['stderr'],
        'type': value['type'],
    };
}

