/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MRBetaFallbackInfo } from './MRBetaFallbackInfo.js';
import {
    MRBetaFallbackInfoFromJSON,
    MRBetaFallbackInfoFromJSONTyped,
    MRBetaFallbackInfoToJSON,
    MRBetaFallbackInfoToJSONTyped,
} from './MRBetaFallbackInfo.js';
import type { MRBetaFallbackRefusalTrigger } from './MRBetaFallbackRefusalTrigger.js';
import {
    MRBetaFallbackRefusalTriggerFromJSON,
    MRBetaFallbackRefusalTriggerFromJSONTyped,
    MRBetaFallbackRefusalTriggerToJSON,
    MRBetaFallbackRefusalTriggerToJSONTyped,
} from './MRBetaFallbackRefusalTrigger.js';

/**
 * Marks the point in `content` where one model's output gives way to the next.
 * 
 * One block appears per hop where a preceding model actually ran this turn and
 * declined. A turn where no preceding model ran and declined has no such
 * boundary and carries no block — the signal for whether a fallback model
 * served the response is the presence of a `fallback_message` entry in
 * `usage.iterations`, not this block.
 * 
 * The block is treated like a server-tool content block for streaming: it
 * arrives via the standard `content_block_start` / `content_block_stop`
 * pair and carries no deltas.
 * @export
 * @interface MRBetaFallbackBlock
 */
export interface MRBetaFallbackBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {MRBetaFallbackInfo}
     * @memberof MRBetaFallbackBlock
     */
    from: MRBetaFallbackInfo;
    /**
     * 
     * @type {MRBetaFallbackInfo}
     * @memberof MRBetaFallbackBlock
     */
    to: MRBetaFallbackInfo;
    /**
     * 
     * @type {MRBetaFallbackRefusalTrigger}
     * @memberof MRBetaFallbackBlock
     */
    trigger: MRBetaFallbackRefusalTrigger;
    /**
     * 
     * @type {MRBetaFallbackBlockTypeEnum}
     * @memberof MRBetaFallbackBlock
     */
    type: MRBetaFallbackBlockTypeEnum;
}


/**
 * @export
 */
export const MRBetaFallbackBlockTypeEnum = {
    Fallback: 'fallback'
} as const;
export type MRBetaFallbackBlockTypeEnum = typeof MRBetaFallbackBlockTypeEnum[keyof typeof MRBetaFallbackBlockTypeEnum];


/**
 * Check if a given object implements the MRBetaFallbackBlock interface.
 */
export function instanceOfMRBetaFallbackBlock(value: object): value is MRBetaFallbackBlock {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('trigger' in value) || value['trigger'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaFallbackBlockFromJSON(json: any): MRBetaFallbackBlock {
    return MRBetaFallbackBlockFromJSONTyped(json, false);
}

export function MRBetaFallbackBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaFallbackBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'from': MRBetaFallbackInfoFromJSON(json['from']),
        'to': MRBetaFallbackInfoFromJSON(json['to']),
        'trigger': MRBetaFallbackRefusalTriggerFromJSON(json['trigger']),
        'type': json['type'],
    };
}

export function MRBetaFallbackBlockToJSON(json: any): MRBetaFallbackBlock {
    return MRBetaFallbackBlockToJSONTyped(json, false);
}

export function MRBetaFallbackBlockToJSONTyped(value?: MRBetaFallbackBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'from': MRBetaFallbackInfoToJSON(value['from']),
        'to': MRBetaFallbackInfoToJSON(value['to']),
        'trigger': MRBetaFallbackRefusalTriggerToJSON(value['trigger']),
        'type': value['type'],
    };
}

