/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRBetaClearToolUses20250919EditResponse
 */
export interface MRBetaClearToolUses20250919EditResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof MRBetaClearToolUses20250919EditResponse
     */
    clearedInputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof MRBetaClearToolUses20250919EditResponse
     */
    clearedToolUses: number;
    /**
     * 
     * @type {MRBetaClearToolUses20250919EditResponseTypeEnum}
     * @memberof MRBetaClearToolUses20250919EditResponse
     */
    type: MRBetaClearToolUses20250919EditResponseTypeEnum;
}


/**
 * @export
 */
export const MRBetaClearToolUses20250919EditResponseTypeEnum = {
    ClearToolUses20250919: 'clear_tool_uses_20250919'
} as const;
export type MRBetaClearToolUses20250919EditResponseTypeEnum = typeof MRBetaClearToolUses20250919EditResponseTypeEnum[keyof typeof MRBetaClearToolUses20250919EditResponseTypeEnum];


/**
 * Check if a given object implements the MRBetaClearToolUses20250919EditResponse interface.
 */
export function instanceOfMRBetaClearToolUses20250919EditResponse(value: object): value is MRBetaClearToolUses20250919EditResponse {
    if (!('clearedInputTokens' in value) || value['clearedInputTokens'] === undefined) return false;
    if (!('clearedToolUses' in value) || value['clearedToolUses'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaClearToolUses20250919EditResponseFromJSON(json: any): MRBetaClearToolUses20250919EditResponse {
    return MRBetaClearToolUses20250919EditResponseFromJSONTyped(json, false);
}

export function MRBetaClearToolUses20250919EditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaClearToolUses20250919EditResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'clearedInputTokens': json['cleared_input_tokens'],
        'clearedToolUses': json['cleared_tool_uses'],
        'type': json['type'],
    };
}

export function MRBetaClearToolUses20250919EditResponseToJSON(json: any): MRBetaClearToolUses20250919EditResponse {
    return MRBetaClearToolUses20250919EditResponseToJSONTyped(json, false);
}

export function MRBetaClearToolUses20250919EditResponseToJSONTyped(value?: MRBetaClearToolUses20250919EditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'cleared_input_tokens': value['clearedInputTokens'],
        'cleared_tool_uses': value['clearedToolUses'],
        'type': value['type'],
    };
}

