/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MRBetaClearThinking20251015EditResponse
 */
export interface MRBetaClearThinking20251015EditResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof MRBetaClearThinking20251015EditResponse
     */
    clearedInputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof MRBetaClearThinking20251015EditResponse
     */
    clearedThinkingTurns: number;
    /**
     * 
     * @type {MRBetaClearThinking20251015EditResponseTypeEnum}
     * @memberof MRBetaClearThinking20251015EditResponse
     */
    type: MRBetaClearThinking20251015EditResponseTypeEnum;
}


/**
 * @export
 */
export const MRBetaClearThinking20251015EditResponseTypeEnum = {
    ClearThinking20251015: 'clear_thinking_20251015'
} as const;
export type MRBetaClearThinking20251015EditResponseTypeEnum = typeof MRBetaClearThinking20251015EditResponseTypeEnum[keyof typeof MRBetaClearThinking20251015EditResponseTypeEnum];


/**
 * Check if a given object implements the MRBetaClearThinking20251015EditResponse interface.
 */
export function instanceOfMRBetaClearThinking20251015EditResponse(value: object): value is MRBetaClearThinking20251015EditResponse {
    if (!('clearedInputTokens' in value) || value['clearedInputTokens'] === undefined) return false;
    if (!('clearedThinkingTurns' in value) || value['clearedThinkingTurns'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaClearThinking20251015EditResponseFromJSON(json: any): MRBetaClearThinking20251015EditResponse {
    return MRBetaClearThinking20251015EditResponseFromJSONTyped(json, false);
}

export function MRBetaClearThinking20251015EditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaClearThinking20251015EditResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'clearedInputTokens': json['cleared_input_tokens'],
        'clearedThinkingTurns': json['cleared_thinking_turns'],
        'type': json['type'],
    };
}

export function MRBetaClearThinking20251015EditResponseToJSON(json: any): MRBetaClearThinking20251015EditResponse {
    return MRBetaClearThinking20251015EditResponseToJSONTyped(json, false);
}

export function MRBetaClearThinking20251015EditResponseToJSONTyped(value?: MRBetaClearThinking20251015EditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'cleared_input_tokens': value['clearedInputTokens'],
        'cleared_thinking_turns': value['clearedThinkingTurns'],
        'type': value['type'],
    };
}

