/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MRBetaCodeExecutionToolResultError
 */
export interface MRBetaCodeExecutionToolResultError {
    [key: string]: any | any;
    /**
     * 
     * @type {MRBetaCodeExecutionToolResultErrorErrorCodeEnum}
     * @memberof MRBetaCodeExecutionToolResultError
     */
    errorCode: MRBetaCodeExecutionToolResultErrorErrorCodeEnum;
    /**
     * 
     * @type {MRBetaCodeExecutionToolResultErrorTypeEnum}
     * @memberof MRBetaCodeExecutionToolResultError
     */
    type: MRBetaCodeExecutionToolResultErrorTypeEnum;
}


/**
 * @export
 */
export const MRBetaCodeExecutionToolResultErrorErrorCodeEnum = {
    InvalidToolInput: 'invalid_tool_input',
    Unavailable: 'unavailable',
    TooManyRequests: 'too_many_requests',
    ExecutionTimeExceeded: 'execution_time_exceeded'
} as const;
export type MRBetaCodeExecutionToolResultErrorErrorCodeEnum = typeof MRBetaCodeExecutionToolResultErrorErrorCodeEnum[keyof typeof MRBetaCodeExecutionToolResultErrorErrorCodeEnum];

/**
 * @export
 */
export const MRBetaCodeExecutionToolResultErrorTypeEnum = {
    CodeExecutionToolResultError: 'code_execution_tool_result_error'
} as const;
export type MRBetaCodeExecutionToolResultErrorTypeEnum = typeof MRBetaCodeExecutionToolResultErrorTypeEnum[keyof typeof MRBetaCodeExecutionToolResultErrorTypeEnum];


/**
 * Check if a given object implements the MRBetaCodeExecutionToolResultError interface.
 */
export function instanceOfMRBetaCodeExecutionToolResultError(value: object): value is MRBetaCodeExecutionToolResultError {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRBetaCodeExecutionToolResultErrorFromJSON(json: any): MRBetaCodeExecutionToolResultError {
    return MRBetaCodeExecutionToolResultErrorFromJSONTyped(json, false);
}

export function MRBetaCodeExecutionToolResultErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRBetaCodeExecutionToolResultError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'errorCode': json['error_code'],
        'type': json['type'],
    };
}

export function MRBetaCodeExecutionToolResultErrorToJSON(json: any): MRBetaCodeExecutionToolResultError {
    return MRBetaCodeExecutionToolResultErrorToJSONTyped(json, false);
}

export function MRBetaCodeExecutionToolResultErrorToJSONTyped(value?: MRBetaCodeExecutionToolResultError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error_code': value['errorCode'],
        'type': value['type'],
    };
}

