/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRCodeExecutionToolResultError
 */
export interface MRCodeExecutionToolResultError {
    [key: string]: any | any;
    /**
     * 
     * @type {MRCodeExecutionToolResultErrorErrorCodeEnum}
     * @memberof MRCodeExecutionToolResultError
     */
    errorCode: MRCodeExecutionToolResultErrorErrorCodeEnum;
    /**
     * 
     * @type {MRCodeExecutionToolResultErrorTypeEnum}
     * @memberof MRCodeExecutionToolResultError
     */
    type: MRCodeExecutionToolResultErrorTypeEnum;
}


/**
 * @export
 */
export const MRCodeExecutionToolResultErrorErrorCodeEnum = {
    InvalidToolInput: 'invalid_tool_input',
    Unavailable: 'unavailable',
    TooManyRequests: 'too_many_requests',
    ExecutionTimeExceeded: 'execution_time_exceeded'
} as const;
export type MRCodeExecutionToolResultErrorErrorCodeEnum = typeof MRCodeExecutionToolResultErrorErrorCodeEnum[keyof typeof MRCodeExecutionToolResultErrorErrorCodeEnum];

/**
 * @export
 */
export const MRCodeExecutionToolResultErrorTypeEnum = {
    CodeExecutionToolResultError: 'code_execution_tool_result_error'
} as const;
export type MRCodeExecutionToolResultErrorTypeEnum = typeof MRCodeExecutionToolResultErrorTypeEnum[keyof typeof MRCodeExecutionToolResultErrorTypeEnum];


/**
 * Check if a given object implements the MRCodeExecutionToolResultError interface.
 */
export function instanceOfMRCodeExecutionToolResultError(value: object): value is MRCodeExecutionToolResultError {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MRCodeExecutionToolResultErrorFromJSON(json: any): MRCodeExecutionToolResultError {
    return MRCodeExecutionToolResultErrorFromJSONTyped(json, false);
}

export function MRCodeExecutionToolResultErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRCodeExecutionToolResultError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'errorCode': json['error_code'],
        'type': json['type'],
    };
}

export function MRCodeExecutionToolResultErrorToJSON(json: any): MRCodeExecutionToolResultError {
    return MRCodeExecutionToolResultErrorToJSONTyped(json, false);
}

export function MRCodeExecutionToolResultErrorToJSONTyped(value?: MRCodeExecutionToolResultError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error_code': value['errorCode'],
        'type': value['type'],
    };
}

