/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MRCodeExecutionOutputBlock } from './MRCodeExecutionOutputBlock';
import {
    MRCodeExecutionOutputBlockFromJSON,
    MRCodeExecutionOutputBlockFromJSONTyped,
    MRCodeExecutionOutputBlockToJSON,
    MRCodeExecutionOutputBlockToJSONTyped,
} from './MRCodeExecutionOutputBlock';

/**
 * Code execution result with encrypted stdout for PFC + web_search results.
 * @export
 * @interface MREncryptedCodeExecutionResultBlock
 */
export interface MREncryptedCodeExecutionResultBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<MRCodeExecutionOutputBlock>}
     * @memberof MREncryptedCodeExecutionResultBlock
     */
    content: Array<MRCodeExecutionOutputBlock>;
    /**
     * 
     * @type {string}
     * @memberof MREncryptedCodeExecutionResultBlock
     */
    encryptedStdout: string;
    /**
     * 
     * @type {number}
     * @memberof MREncryptedCodeExecutionResultBlock
     */
    returnCode: number;
    /**
     * 
     * @type {string}
     * @memberof MREncryptedCodeExecutionResultBlock
     */
    stderr: string;
    /**
     * 
     * @type {MREncryptedCodeExecutionResultBlockTypeEnum}
     * @memberof MREncryptedCodeExecutionResultBlock
     */
    type: MREncryptedCodeExecutionResultBlockTypeEnum;
}


/**
 * @export
 */
export const MREncryptedCodeExecutionResultBlockTypeEnum = {
    EncryptedCodeExecutionResult: 'encrypted_code_execution_result'
} as const;
export type MREncryptedCodeExecutionResultBlockTypeEnum = typeof MREncryptedCodeExecutionResultBlockTypeEnum[keyof typeof MREncryptedCodeExecutionResultBlockTypeEnum];


/**
 * Check if a given object implements the MREncryptedCodeExecutionResultBlock interface.
 */
export function instanceOfMREncryptedCodeExecutionResultBlock(value: object): value is MREncryptedCodeExecutionResultBlock {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('encryptedStdout' in value) || value['encryptedStdout'] === undefined) return false;
    if (!('returnCode' in value) || value['returnCode'] === undefined) return false;
    if (!('stderr' in value) || value['stderr'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MREncryptedCodeExecutionResultBlockFromJSON(json: any): MREncryptedCodeExecutionResultBlock {
    return MREncryptedCodeExecutionResultBlockFromJSONTyped(json, false);
}

export function MREncryptedCodeExecutionResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MREncryptedCodeExecutionResultBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'content': ((json['content'] as Array<any>).map(MRCodeExecutionOutputBlockFromJSON)),
        'encryptedStdout': json['encrypted_stdout'],
        'returnCode': json['return_code'],
        'stderr': json['stderr'],
        'type': json['type'],
    };
}

export function MREncryptedCodeExecutionResultBlockToJSON(json: any): MREncryptedCodeExecutionResultBlock {
    return MREncryptedCodeExecutionResultBlockToJSONTyped(json, false);
}

export function MREncryptedCodeExecutionResultBlockToJSONTyped(value?: MREncryptedCodeExecutionResultBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'content': ((value['content'] as Array<any>).map(MRCodeExecutionOutputBlockToJSON)),
        'encrypted_stdout': value['encryptedStdout'],
        'return_code': value['returnCode'],
        'stderr': value['stderr'],
        'type': value['type'],
    };
}

