/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRWebSearchResultBlock
 */
export interface MRWebSearchResultBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MRWebSearchResultBlock
     */
    encryptedContent: string;
    /**
     * Filter models by provider name
     * @type {string}
     * @memberof MRWebSearchResultBlock
     */
    pageAge?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MRWebSearchResultBlock
     */
    title: string;
    /**
     * 
     * @type {MRWebSearchResultBlockTypeEnum}
     * @memberof MRWebSearchResultBlock
     */
    type: MRWebSearchResultBlockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MRWebSearchResultBlock
     */
    url: string;
}


/**
 * @export
 */
export const MRWebSearchResultBlockTypeEnum = {
    WebSearchResult: 'web_search_result'
} as const;
export type MRWebSearchResultBlockTypeEnum = typeof MRWebSearchResultBlockTypeEnum[keyof typeof MRWebSearchResultBlockTypeEnum];


/**
 * Check if a given object implements the MRWebSearchResultBlock interface.
 */
export function instanceOfMRWebSearchResultBlock(value: object): value is MRWebSearchResultBlock {
    if (!('encryptedContent' in value) || value['encryptedContent'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function MRWebSearchResultBlockFromJSON(json: any): MRWebSearchResultBlock {
    return MRWebSearchResultBlockFromJSONTyped(json, false);
}

export function MRWebSearchResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRWebSearchResultBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'encryptedContent': json['encrypted_content'],
        'pageAge': json['page_age'] == null ? undefined : json['page_age'],
        'title': json['title'],
        'type': json['type'],
        'url': json['url'],
    };
}

export function MRWebSearchResultBlockToJSON(json: any): MRWebSearchResultBlock {
    return MRWebSearchResultBlockToJSONTyped(json, false);
}

export function MRWebSearchResultBlockToJSONTyped(value?: MRWebSearchResultBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'encrypted_content': value['encryptedContent'],
        'page_age': value['pageAge'],
        'title': value['title'],
        'type': value['type'],
        'url': value['url'],
    };
}

