/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MSGChatCompletionContentPartRefusalParam
 */
export interface MSGChatCompletionContentPartRefusalParam {
    /**
     * 
     * @type {string}
     * @memberof MSGChatCompletionContentPartRefusalParam
     */
    refusal: string;
    /**
     * 
     * @type {MSGChatCompletionContentPartRefusalParamTypeEnum}
     * @memberof MSGChatCompletionContentPartRefusalParam
     */
    type: MSGChatCompletionContentPartRefusalParamTypeEnum;
}


/**
 * @export
 */
export const MSGChatCompletionContentPartRefusalParamTypeEnum = {
    Refusal: 'refusal'
} as const;
export type MSGChatCompletionContentPartRefusalParamTypeEnum = typeof MSGChatCompletionContentPartRefusalParamTypeEnum[keyof typeof MSGChatCompletionContentPartRefusalParamTypeEnum];


/**
 * Check if a given object implements the MSGChatCompletionContentPartRefusalParam interface.
 */
export function instanceOfMSGChatCompletionContentPartRefusalParam(value: object): value is MSGChatCompletionContentPartRefusalParam {
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'refusal') return false;
    
    return true;
}

export function MSGChatCompletionContentPartRefusalParamFromJSON(json: any): MSGChatCompletionContentPartRefusalParam {
    return MSGChatCompletionContentPartRefusalParamFromJSONTyped(json, false);
}

export function MSGChatCompletionContentPartRefusalParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSGChatCompletionContentPartRefusalParam {
    if (json == null) {
        return json;
    }
    return {
        
        'refusal': json['refusal'],
        'type': json['type'],
    };
}

export function MSGChatCompletionContentPartRefusalParamToJSON(json: any): MSGChatCompletionContentPartRefusalParam {
    return MSGChatCompletionContentPartRefusalParamToJSONTyped(json, false);
}

export function MSGChatCompletionContentPartRefusalParamToJSONTyped(value?: MSGChatCompletionContentPartRefusalParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refusal': value['refusal'],
        'type': value['type'],
    };
}

