/* tslint:disable */
/* eslint-disable */
/**
 * otari-gateway
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MSGFunction } from './MSGFunction';
import {
    MSGFunctionFromJSON,
    MSGFunctionFromJSONTyped,
    MSGFunctionToJSON,
    MSGFunctionToJSONTyped,
} from './MSGFunction';

/**
 * A call to a function tool created by the model.
 * @export
 * @interface MSGChatCompletionMessageFunctionToolCallParam
 */
export interface MSGChatCompletionMessageFunctionToolCallParam {
    /**
     * 
     * @type {string}
     * @memberof MSGChatCompletionMessageFunctionToolCallParam
     */
    id: string;
    /**
     * 
     * @type {MSGFunction}
     * @memberof MSGChatCompletionMessageFunctionToolCallParam
     */
    _function: MSGFunction;
    /**
     * 
     * @type {MSGChatCompletionMessageFunctionToolCallParamTypeEnum}
     * @memberof MSGChatCompletionMessageFunctionToolCallParam
     */
    type: MSGChatCompletionMessageFunctionToolCallParamTypeEnum;
}


/**
 * @export
 */
export const MSGChatCompletionMessageFunctionToolCallParamTypeEnum = {
    Function: 'function'
} as const;
export type MSGChatCompletionMessageFunctionToolCallParamTypeEnum = typeof MSGChatCompletionMessageFunctionToolCallParamTypeEnum[keyof typeof MSGChatCompletionMessageFunctionToolCallParamTypeEnum];


/**
 * Check if a given object implements the MSGChatCompletionMessageFunctionToolCallParam interface.
 */
export function instanceOfMSGChatCompletionMessageFunctionToolCallParam(value: object): value is MSGChatCompletionMessageFunctionToolCallParam {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MSGChatCompletionMessageFunctionToolCallParamFromJSON(json: any): MSGChatCompletionMessageFunctionToolCallParam {
    return MSGChatCompletionMessageFunctionToolCallParamFromJSONTyped(json, false);
}

export function MSGChatCompletionMessageFunctionToolCallParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSGChatCompletionMessageFunctionToolCallParam {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        '_function': MSGFunctionFromJSON(json['function']),
        'type': json['type'],
    };
}

export function MSGChatCompletionMessageFunctionToolCallParamToJSON(json: any): MSGChatCompletionMessageFunctionToolCallParam {
    return MSGChatCompletionMessageFunctionToolCallParamToJSONTyped(json, false);
}

export function MSGChatCompletionMessageFunctionToolCallParamToJSONTyped(value?: MSGChatCompletionMessageFunctionToolCallParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'function': MSGFunctionToJSON(value['_function']),
        'type': value['type'],
    };
}

