/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * One offered model, with the rate the caller's organization is charged for it.
 * 
 * ``price_source`` says which rung of ``services.pricing_service`` answered:
 * ``organization`` for a rate an admin set, ``defaults`` for the
 * community-maintained rate this surface seeded or the genai-prices fallback,
 * ``deployment`` for the deployment's own price list, and None when nothing
 * prices the model yet. ``pricing_id`` names the organization's own row where
 * there is one, so a client can edit that rate without re-deriving the key.
 * @export
 * @interface OrgProviderKeyModelPublic
 */
export interface OrgProviderKeyModelPublic {
    /**
     * 
     * @type {number}
     * @memberof OrgProviderKeyModelPublic
     */
    cacheReadPricePerMillion?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrgProviderKeyModelPublic
     */
    cacheWrite1hPricePerMillion?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrgProviderKeyModelPublic
     */
    cacheWritePricePerMillion?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof OrgProviderKeyModelPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof OrgProviderKeyModelPublic
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrgProviderKeyModelPublic
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof OrgProviderKeyModelPublic
     */
    inputPricePerMillion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrgProviderKeyModelPublic
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof OrgProviderKeyModelPublic
     */
    orgProviderKeyId: string;
    /**
     * 
     * @type {number}
     * @memberof OrgProviderKeyModelPublic
     */
    outputPricePerMillion?: number | null;
    /**
     * 
     * @type {OrgProviderKeyModelPublicPriceSourceEnum}
     * @memberof OrgProviderKeyModelPublic
     */
    priceSource?: OrgProviderKeyModelPublicPriceSourceEnum | null;
    /**
     * 
     * @type {string}
     * @memberof OrgProviderKeyModelPublic
     */
    pricingId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrgProviderKeyModelPublic
     */
    updatedAt?: Date | null;
}


/**
 * @export
 */
export const OrgProviderKeyModelPublicPriceSourceEnum = {
    Organization: 'organization',
    Deployment: 'deployment',
    Defaults: 'defaults'
} as const;
export type OrgProviderKeyModelPublicPriceSourceEnum = typeof OrgProviderKeyModelPublicPriceSourceEnum[keyof typeof OrgProviderKeyModelPublicPriceSourceEnum];


/**
 * Check if a given object implements the OrgProviderKeyModelPublic interface.
 */
export function instanceOfOrgProviderKeyModelPublic(value: object): value is OrgProviderKeyModelPublic {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('orgProviderKeyId' in value) || value['orgProviderKeyId'] === undefined) return false;
    return true;
}

export function OrgProviderKeyModelPublicFromJSON(json: any): OrgProviderKeyModelPublic {
    return OrgProviderKeyModelPublicFromJSONTyped(json, false);
}

export function OrgProviderKeyModelPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgProviderKeyModelPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheReadPricePerMillion': json['cache_read_price_per_million'] == null ? undefined : json['cache_read_price_per_million'],
        'cacheWrite1hPricePerMillion': json['cache_write_1h_price_per_million'] == null ? undefined : json['cache_write_1h_price_per_million'],
        'cacheWritePricePerMillion': json['cache_write_price_per_million'] == null ? undefined : json['cache_write_price_per_million'],
        'createdAt': (new Date(json['created_at'])),
        'enabled': json['enabled'],
        'id': json['id'],
        'inputPricePerMillion': json['input_price_per_million'] == null ? undefined : json['input_price_per_million'],
        'model': json['model'],
        'orgProviderKeyId': json['org_provider_key_id'],
        'outputPricePerMillion': json['output_price_per_million'] == null ? undefined : json['output_price_per_million'],
        'priceSource': json['price_source'] == null ? undefined : json['price_source'],
        'pricingId': json['pricing_id'] == null ? undefined : json['pricing_id'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function OrgProviderKeyModelPublicToJSON(json: any): OrgProviderKeyModelPublic {
    return OrgProviderKeyModelPublicToJSONTyped(json, false);
}

export function OrgProviderKeyModelPublicToJSONTyped(value?: OrgProviderKeyModelPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read_price_per_million': value['cacheReadPricePerMillion'],
        'cache_write_1h_price_per_million': value['cacheWrite1hPricePerMillion'],
        'cache_write_price_per_million': value['cacheWritePricePerMillion'],
        'created_at': value['createdAt'].toISOString(),
        'enabled': value['enabled'],
        'id': value['id'],
        'input_price_per_million': value['inputPricePerMillion'],
        'model': value['model'],
        'org_provider_key_id': value['orgProviderKeyId'],
        'output_price_per_million': value['outputPricePerMillion'],
        'price_source': value['priceSource'],
        'pricing_id': value['pricingId'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

