/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AllocationHealthResponse } from './AllocationHealthResponse.js';
import {
    AllocationHealthResponseFromJSON,
    AllocationHealthResponseFromJSONTyped,
    AllocationHealthResponseToJSON,
    AllocationHealthResponseToJSONTyped,
} from './AllocationHealthResponse.js';

/**
 * What the dashboard overview renders beside its usage chart.
 * 
 * ``budgets`` and ``ceilings`` are null where the caller may not see them,
 * which is not the same as a strip with nothing in it: deployment budgets are
 * the operator's, and spend ceilings are an organization owner's or admin's.
 * @export
 * @interface OverviewSummaryResponse
 */
export interface OverviewSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof OverviewSummaryResponse
     */
    activeKeys: number;
    /**
     * Active members of the named workspace; 0 when none is named.
     * @type {number}
     * @memberof OverviewSummaryResponse
     */
    activeMembers: number;
    /**
     * 
     * @type {AllocationHealthResponse}
     * @memberof OverviewSummaryResponse
     */
    budgets: AllocationHealthResponse | null;
    /**
     * 
     * @type {AllocationHealthResponse}
     * @memberof OverviewSummaryResponse
     */
    ceilings: AllocationHealthResponse | null;
}

/**
 * Check if a given object implements the OverviewSummaryResponse interface.
 */
export function instanceOfOverviewSummaryResponse(value: object): value is OverviewSummaryResponse {
    if (!('activeKeys' in value) || value['activeKeys'] === undefined) return false;
    if (!('activeMembers' in value) || value['activeMembers'] === undefined) return false;
    if (!('budgets' in value) || value['budgets'] === undefined) return false;
    if (!('ceilings' in value) || value['ceilings'] === undefined) return false;
    return true;
}

export function OverviewSummaryResponseFromJSON(json: any): OverviewSummaryResponse {
    return OverviewSummaryResponseFromJSONTyped(json, false);
}

export function OverviewSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeKeys': json['active_keys'],
        'activeMembers': json['active_members'],
        'budgets': AllocationHealthResponseFromJSON(json['budgets']),
        'ceilings': AllocationHealthResponseFromJSON(json['ceilings']),
    };
}

export function OverviewSummaryResponseToJSON(json: any): OverviewSummaryResponse {
    return OverviewSummaryResponseToJSONTyped(json, false);
}

export function OverviewSummaryResponseToJSONTyped(value?: OverviewSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_keys': value['activeKeys'],
        'active_members': value['activeMembers'],
        'budgets': AllocationHealthResponseToJSON(value['budgets']),
        'ceilings': AllocationHealthResponseToJSON(value['ceilings']),
    };
}

