/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A row in the comparison history: the question, the pair, the verdict.
 * 
 * Deliberately without the two answers. The list shows a dozen rows at once
 * and none of them renders an answer body, so sending them would move
 * megabytes to draw a few lines of text. There is no detail endpoint either,
 * because the page has no screen that reads one back: a comparison is a
 * judgment that was recorded, not a transcript to resume.
 * @export
 * @interface PlaygroundComparisonSummary
 */
export interface PlaygroundComparisonSummary {
    /**
     * 
     * @type {Date}
     * @memberof PlaygroundComparisonSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    modelA: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    modelB: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    preference: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    userQuestion: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundComparisonSummary
     */
    workspaceId: string;
}

/**
 * Check if a given object implements the PlaygroundComparisonSummary interface.
 */
export function instanceOfPlaygroundComparisonSummary(value: object): value is PlaygroundComparisonSummary {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modelA' in value) || value['modelA'] === undefined) return false;
    if (!('modelB' in value) || value['modelB'] === undefined) return false;
    if (!('preference' in value) || value['preference'] === undefined) return false;
    if (!('userQuestion' in value) || value['userQuestion'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    return true;
}

export function PlaygroundComparisonSummaryFromJSON(json: any): PlaygroundComparisonSummary {
    return PlaygroundComparisonSummaryFromJSONTyped(json, false);
}

export function PlaygroundComparisonSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaygroundComparisonSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'modelA': json['model_a'],
        'modelB': json['model_b'],
        'preference': json['preference'],
        'userQuestion': json['user_question'],
        'workspaceId': json['workspace_id'],
    };
}

export function PlaygroundComparisonSummaryToJSON(json: any): PlaygroundComparisonSummary {
    return PlaygroundComparisonSummaryToJSONTyped(json, false);
}

export function PlaygroundComparisonSummaryToJSONTyped(value?: PlaygroundComparisonSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'model_a': value['modelA'],
        'model_b': value['modelB'],
        'preference': value['preference'],
        'user_question': value['userQuestion'],
        'workspace_id': value['workspaceId'],
    };
}

