/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request to create or update a routing policy.
 * @export
 * @interface PolicyRequest
 */
export interface PolicyRequest {
    /**
     * Model name callers send, e.g. 'fast'.
     * @type {string}
     * @memberof PolicyRequest
     */
    name: string;
    /**
     * Current name of the policy to rename, in the same scope, meaning the same workspace and the same user. A rename never moves a policy between them. The stored row keeps its id and created_at and takes `name` and `spec`. Sending it asserts that policy exists, so a name with no stored row is a 404 rather than a create, even when it equals `name`. Omit to create or update the policy named `name`. Renaming changes what callers must send as `model`; usage already recorded keeps the old name.
     * @type {string}
     * @memberof PolicyRequest
     */
    renameFrom?: string | null;
    /**
     * The policy body: select (with exactly one `default` entry, last), optional on_failure and guardrails. Same schema as a `routing.policies` entry in config.yml, and closed to unknown keys, so a typo is a 400 rather than a silently ignored setting.
     * @type {{ [key: string]: any; }}
     * @memberof PolicyRequest
     */
    spec: { [key: string]: any; };
    /**
     * User this policy belongs to. Omit for a policy every caller in the workspace sees. A user-scoped policy resolves only for that user and shadows the workspace-wide one of the same name.
     * @type {string}
     * @memberof PolicyRequest
     */
    userId?: string | null;
    /**
     * Workspace this policy belongs to. Omit for the deployment's default workspace. The policy resolves only for requests in that workspace, so two workspaces can each define their own 'fast'.
     * @type {string}
     * @memberof PolicyRequest
     */
    workspaceId?: string | null;
}

/**
 * Check if a given object implements the PolicyRequest interface.
 */
export function instanceOfPolicyRequest(value: object): value is PolicyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    return true;
}

export function PolicyRequestFromJSON(json: any): PolicyRequest {
    return PolicyRequestFromJSONTyped(json, false);
}

export function PolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'renameFrom': json['rename_from'] == null ? undefined : json['rename_from'],
        'spec': json['spec'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'workspaceId': json['workspace_id'] == null ? undefined : json['workspace_id'],
    };
}

export function PolicyRequestToJSON(json: any): PolicyRequest {
    return PolicyRequestToJSONTyped(json, false);
}

export function PolicyRequestToJSONTyped(value?: PolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'rename_from': value['renameFrom'],
        'spec': value['spec'],
        'user_id': value['userId'],
        'workspace_id': value['workspaceId'],
    };
}

