/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * One default model price changed by a pending refresh.
 * @export
 * @interface PricingRefreshChangeResponse
 */
export interface PricingRefreshChangeResponse {
    /**
     * 
     * @type {string}
     * @memberof PricingRefreshChangeResponse
     */
    change: string;
    /**
     * 
     * @type {string}
     * @memberof PricingRefreshChangeResponse
     */
    modelKey: string;
}

/**
 * Check if a given object implements the PricingRefreshChangeResponse interface.
 */
export function instanceOfPricingRefreshChangeResponse(value: object): value is PricingRefreshChangeResponse {
    if (!('change' in value) || value['change'] === undefined) return false;
    if (!('modelKey' in value) || value['modelKey'] === undefined) return false;
    return true;
}

export function PricingRefreshChangeResponseFromJSON(json: any): PricingRefreshChangeResponse {
    return PricingRefreshChangeResponseFromJSONTyped(json, false);
}

export function PricingRefreshChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingRefreshChangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'change': json['change'],
        'modelKey': json['model_key'],
    };
}

export function PricingRefreshChangeResponseToJSON(json: any): PricingRefreshChangeResponse {
    return PricingRefreshChangeResponseToJSONTyped(json, false);
}

export function PricingRefreshChangeResponseToJSONTyped(value?: PricingRefreshChangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change': value['change'],
        'model_key': value['modelKey'],
    };
}

