/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result of activating a reviewed genai-prices refresh.
 * @export
 * @interface PricingRefreshConfirmationResponse
 */
export interface PricingRefreshConfirmationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PricingRefreshConfirmationResponse
     */
    applied?: boolean;
}

/**
 * Check if a given object implements the PricingRefreshConfirmationResponse interface.
 */
export function instanceOfPricingRefreshConfirmationResponse(value: object): value is PricingRefreshConfirmationResponse {
    return true;
}

export function PricingRefreshConfirmationResponseFromJSON(json: any): PricingRefreshConfirmationResponse {
    return PricingRefreshConfirmationResponseFromJSONTyped(json, false);
}

export function PricingRefreshConfirmationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingRefreshConfirmationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'applied': json['applied'] == null ? undefined : json['applied'],
    };
}

export function PricingRefreshConfirmationResponseToJSON(json: any): PricingRefreshConfirmationResponse {
    return PricingRefreshConfirmationResponseToJSONTyped(json, false);
}

export function PricingRefreshConfirmationResponseToJSONTyped(value?: PricingRefreshConfirmationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applied': value['applied'],
    };
}

