/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A partial update. Only what is set is applied; an explicit null ``api_key`` clears it.
 * @export
 * @interface ProviderEndpointUpdateRequest
 */
export interface ProviderEndpointUpdateRequest {
    /**
     * Base URL of the endpoint. Refused when it resolves to a private, loopback, link-local or reserved address.
     * @type {string}
     * @memberof ProviderEndpointUpdateRequest
     */
    apiBase?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderEndpointUpdateRequest
     */
    apiKey?: string | null;
    /**
     * Fields added to every request body sent to this endpoint, beneath the caller's own: a field the caller sets wins. For fields the gateway does not model, such as vLLM's 'chat_template_kwargs'. Credential and transport fields are refused.
     * @type {{ [key: string]: any; }}
     * @memberof ProviderEndpointUpdateRequest
     */
    defaultParams?: { [key: string]: any; } | null;
    /**
     * What callers put before the colon to reach this endpoint, as '<name>:<model>'. Letters, digits, '.', '_' and '-', starting with a letter or digit. It may not be a provider's name or a configured instance's.
     * @type {string}
     * @memberof ProviderEndpointUpdateRequest
     */
    name?: string | null;
    /**
     * The implementation that speaks to the endpoint: 'openai' for an OpenAI-compatible server, 'anthropic' for an Anthropic-compatible one. Whichever it is, callers may use any of the chat, responses and messages routes.
     * @type {string}
     * @memberof ProviderEndpointUpdateRequest
     */
    provider?: string | null;
}

/**
 * Check if a given object implements the ProviderEndpointUpdateRequest interface.
 */
export function instanceOfProviderEndpointUpdateRequest(value: object): value is ProviderEndpointUpdateRequest {
    return true;
}

export function ProviderEndpointUpdateRequestFromJSON(json: any): ProviderEndpointUpdateRequest {
    return ProviderEndpointUpdateRequestFromJSONTyped(json, false);
}

export function ProviderEndpointUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEndpointUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiBase': json['api_base'] == null ? undefined : json['api_base'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'defaultParams': json['default_params'] == null ? undefined : json['default_params'],
        'name': json['name'] == null ? undefined : json['name'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function ProviderEndpointUpdateRequestToJSON(json: any): ProviderEndpointUpdateRequest {
    return ProviderEndpointUpdateRequestToJSONTyped(json, false);
}

export function ProviderEndpointUpdateRequestToJSONTyped(value?: ProviderEndpointUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_base': value['apiBase'],
        'api_key': value['apiKey'],
        'default_params': value['defaultParams'],
        'name': value['name'],
        'provider': value['provider'],
    };
}

