/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProviderCapabilitiesSchema } from './ProviderCapabilitiesSchema.js';
import {
    ProviderCapabilitiesSchemaFromJSON,
    ProviderCapabilitiesSchemaFromJSONTyped,
    ProviderCapabilitiesSchemaToJSON,
    ProviderCapabilitiesSchemaToJSONTyped,
} from './ProviderCapabilitiesSchema.js';

/**
 * Static, network-free metadata for one configured provider instance.
 * @export
 * @interface ProviderInfoSchema
 */
export interface ProviderInfoSchema {
    /**
     * 
     * @type {ProviderCapabilitiesSchema}
     * @memberof ProviderInfoSchema
     */
    capabilities: ProviderCapabilitiesSchema;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    docUrl?: string | null;
    /**
     * Env var the credential is read from.
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    envKey?: string | null;
    /**
     * Configured provider key (may differ from the type).
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    instance: string;
    /**
     * Human-friendly provider name.
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderInfoSchema
     */
    pricingUrls?: Array<string>;
    /**
     * Underlying any-llm provider type.
     * @type {string}
     * @memberof ProviderInfoSchema
     */
    providerType: string;
}

/**
 * Check if a given object implements the ProviderInfoSchema interface.
 */
export function instanceOfProviderInfoSchema(value: object): value is ProviderInfoSchema {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    return true;
}

export function ProviderInfoSchemaFromJSON(json: any): ProviderInfoSchema {
    return ProviderInfoSchemaFromJSONTyped(json, false);
}

export function ProviderInfoSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderInfoSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilities': ProviderCapabilitiesSchemaFromJSON(json['capabilities']),
        'description': json['description'] == null ? undefined : json['description'],
        'docUrl': json['doc_url'] == null ? undefined : json['doc_url'],
        'envKey': json['env_key'] == null ? undefined : json['env_key'],
        'instance': json['instance'],
        'name': json['name'],
        'pricingUrls': json['pricing_urls'] == null ? undefined : json['pricing_urls'],
        'providerType': json['provider_type'],
    };
}

export function ProviderInfoSchemaToJSON(json: any): ProviderInfoSchema {
    return ProviderInfoSchemaToJSONTyped(json, false);
}

export function ProviderInfoSchemaToJSONTyped(value?: ProviderInfoSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capabilities': ProviderCapabilitiesSchemaToJSON(value['capabilities']),
        'description': value['description'],
        'doc_url': value['docUrl'],
        'env_key': value['envKey'],
        'instance': value['instance'],
        'name': value['name'],
        'pricing_urls': value['pricingUrls'],
        'provider_type': value['providerType'],
    };
}

