/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * What a caller sends to create an owned endpoint. The key is stored encrypted.
 * @export
 * @interface ProviderEndpointCreateRequest
 */
export interface ProviderEndpointCreateRequest {
    /**
     * Base URL of the endpoint. Refused when it resolves to a private, loopback, link-local or reserved address.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    apiBase: string;
    /**
     * Sent to the endpoint. Never returned, only its last four.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    apiKey?: string | null;
    /**
     * Tags for cost attribution, recorded on the request's usage rows and filterable in the usage API: up to 16 string pairs, keys up to 64 characters and values up to 512. A null value is ignored. LiteLLM's nested `spend_logs_metadata` object is also read, and wins over a flat key of the same name; it is never forwarded to the provider.
     * @type {{ [key: string]: any; }}
     * @memberof ProviderEndpointCreateRequest
     */
    defaultParams?: { [key: string]: any; } | null;
    /**
     * What callers put before the colon to reach this endpoint, as '<name>:<model>'. Letters, digits, '.', '_' and '-', starting with a letter or digit. It may not be a provider's name or a configured instance's.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    name: string;
    /**
     * The implementation that speaks to the endpoint: 'openai' for an OpenAI-compatible server, 'anthropic' for an Anthropic-compatible one. Whichever it is, callers may use any of the chat, responses and messages routes.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    provider: string;
    /**
     * User that owns the endpoint. Omit for one every caller in the workspace reaches. A user's endpoint shadows a workspace-wide one of the same name for that user alone.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    userId?: string | null;
    /**
     * Workspace that owns the endpoint. Omit for the deployment's default workspace.
     * @type {string}
     * @memberof ProviderEndpointCreateRequest
     */
    workspaceId?: string | null;
}

/**
 * Check if a given object implements the ProviderEndpointCreateRequest interface.
 */
export function instanceOfProviderEndpointCreateRequest(value: object): value is ProviderEndpointCreateRequest {
    if (!('apiBase' in value) || value['apiBase'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function ProviderEndpointCreateRequestFromJSON(json: any): ProviderEndpointCreateRequest {
    return ProviderEndpointCreateRequestFromJSONTyped(json, false);
}

export function ProviderEndpointCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEndpointCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiBase': json['api_base'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'defaultParams': json['default_params'] == null ? undefined : json['default_params'],
        'name': json['name'],
        'provider': json['provider'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'workspaceId': json['workspace_id'] == null ? undefined : json['workspace_id'],
    };
}

export function ProviderEndpointCreateRequestToJSON(json: any): ProviderEndpointCreateRequest {
    return ProviderEndpointCreateRequestToJSONTyped(json, false);
}

export function ProviderEndpointCreateRequestToJSONTyped(value?: ProviderEndpointCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_base': value['apiBase'],
        'api_key': value['apiKey'],
        'default_params': value['defaultParams'],
        'name': value['name'],
        'provider': value['provider'],
        'user_id': value['userId'],
        'workspace_id': value['workspaceId'],
    };
}

