/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { RecordedPool } from './RecordedPool.js';
import {
    RecordedPoolFromJSON,
    RecordedPoolFromJSONTyped,
    RecordedPoolToJSON,
    RecordedPoolToJSONTyped,
} from './RecordedPool.js';

/**
 * 
 * @export
 * @interface RankResponse
 */
export interface RankResponse {
    /**
     * 
     * @type {Array<RecordedPool>}
     * @memberof RankResponse
     */
    pools: Array<RecordedPool>;
    /**
     * 
     * @type {number}
     * @memberof RankResponse
     */
    recorded: number;
    /**
     * 
     * @type {number}
     * @memberof RankResponse
     */
    seedCount: number;
}

/**
 * Check if a given object implements the RankResponse interface.
 */
export function instanceOfRankResponse(value: object): value is RankResponse {
    if (!('pools' in value) || value['pools'] === undefined) return false;
    if (!('recorded' in value) || value['recorded'] === undefined) return false;
    if (!('seedCount' in value) || value['seedCount'] === undefined) return false;
    return true;
}

export function RankResponseFromJSON(json: any): RankResponse {
    return RankResponseFromJSONTyped(json, false);
}

export function RankResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pools': ((json['pools'] as Array<any>).map(RecordedPoolFromJSON)),
        'recorded': json['recorded'],
        'seedCount': json['seed_count'],
    };
}

export function RankResponseToJSON(json: any): RankResponse {
    return RankResponseToJSONTyped(json, false);
}

export function RankResponseToJSONTyped(value?: RankResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pools': ((value['pools'] as Array<any>).map(RecordedPoolToJSON)),
        'recorded': value['recorded'],
        'seed_count': value['seedCount'],
    };
}

