/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * What one request settled at, summed over every usage row it wrote.
 * 
 * A routed request writes a row per attempt and a vision-normalized one a row for
 * the describe call, all sharing the ``Otari-Request-ID`` the caller was sent as
 * their ``request_group_id``, so this is the request's whole bill rather than one
 * attempt's. ``cost_usd`` uses the inline ``usage.cost_usd`` format and is null
 * when no row was priced.
 * @export
 * @interface RequestSettlement
 */
export interface RequestSettlement {
    /**
     * 
     * @type {number}
     * @memberof RequestSettlement
     */
    completionTokens: number;
    /**
     * 
     * @type {string}
     * @memberof RequestSettlement
     */
    costUsd: string | null;
    /**
     * 
     * @type {number}
     * @memberof RequestSettlement
     */
    promptTokens: number;
    /**
     * 
     * @type {string}
     * @memberof RequestSettlement
     */
    requestId: string;
    /**
     * 
     * @type {number}
     * @memberof RequestSettlement
     */
    rowCount: number;
    /**
     * 
     * @type {RequestSettlementStatusEnum}
     * @memberof RequestSettlement
     */
    status: RequestSettlementStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof RequestSettlement
     */
    totalTokens: number;
}


/**
 * @export
 */
export const RequestSettlementStatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type RequestSettlementStatusEnum = typeof RequestSettlementStatusEnum[keyof typeof RequestSettlementStatusEnum];


/**
 * Check if a given object implements the RequestSettlement interface.
 */
export function instanceOfRequestSettlement(value: object): value is RequestSettlement {
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('costUsd' in value) || value['costUsd'] === undefined) return false;
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('rowCount' in value) || value['rowCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function RequestSettlementFromJSON(json: any): RequestSettlement {
    return RequestSettlementFromJSONTyped(json, false);
}

export function RequestSettlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestSettlement {
    if (json == null) {
        return json;
    }
    return {
        
        'completionTokens': json['completion_tokens'],
        'costUsd': json['cost_usd'],
        'promptTokens': json['prompt_tokens'],
        'requestId': json['request_id'],
        'rowCount': json['row_count'],
        'status': json['status'],
        'totalTokens': json['total_tokens'],
    };
}

export function RequestSettlementToJSON(json: any): RequestSettlement {
    return RequestSettlementToJSONTyped(json, false);
}

export function RequestSettlementToJSONTyped(value?: RequestSettlement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completion_tokens': value['completionTokens'],
        'cost_usd': value['costUsd'],
        'prompt_tokens': value['promptTokens'],
        'request_id': value['requestId'],
        'row_count': value['rowCount'],
        'status': value['status'],
        'total_tokens': value['totalTokens'],
    };
}

