/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Annotations } from './Annotations.js';
import {
    AnnotationsFromJSON,
    AnnotationsFromJSONTyped,
    AnnotationsToJSON,
    AnnotationsToJSONTyped,
} from './Annotations.js';
import type { Icon } from './Icon.js';
import {
    IconFromJSON,
    IconFromJSONTyped,
    IconToJSON,
    IconToJSONTyped,
} from './Icon.js';

/**
 * A resource that the server is capable of reading, included in a prompt or tool call result.
 * 
 * Note: resource links returned by tools are not guaranteed to appear in the results of `resources/list` requests.
 * @export
 * @interface ResourceLink
 */
export interface ResourceLink {
    [key: string]: any | any;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ResourceLink
     */
    meta?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Annotations}
     * @memberof ResourceLink
     */
    annotations?: Annotations | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceLink
     */
    description?: string | null;
    /**
     * 
     * @type {Array<Icon>}
     * @memberof ResourceLink
     */
    icons?: Array<Icon> | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceLink
     */
    mimeType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceLink
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceLink
     */
    size?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceLink
     */
    title?: string | null;
    /**
     * 
     * @type {ResourceLinkTypeEnum}
     * @memberof ResourceLink
     */
    type: ResourceLinkTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceLink
     */
    uri: string;
}


/**
 * @export
 */
export const ResourceLinkTypeEnum = {
    ResourceLink: 'resource_link'
} as const;
export type ResourceLinkTypeEnum = typeof ResourceLinkTypeEnum[keyof typeof ResourceLinkTypeEnum];


/**
 * Check if a given object implements the ResourceLink interface.
 */
export function instanceOfResourceLink(value: object): value is ResourceLink {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function ResourceLinkFromJSON(json: any): ResourceLink {
    return ResourceLinkFromJSONTyped(json, false);
}

export function ResourceLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLink {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'meta': json['_meta'] == null ? undefined : json['_meta'],
        'annotations': json['annotations'] == null ? undefined : AnnotationsFromJSON(json['annotations']),
        'description': json['description'] == null ? undefined : json['description'],
        'icons': json['icons'] == null ? undefined : ((json['icons'] as Array<any>).map(IconFromJSON)),
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'name': json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'],
        'uri': json['uri'],
    };
}

export function ResourceLinkToJSON(json: any): ResourceLink {
    return ResourceLinkToJSONTyped(json, false);
}

export function ResourceLinkToJSONTyped(value?: ResourceLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        '_meta': value['meta'],
        'annotations': AnnotationsToJSON(value['annotations']),
        'description': value['description'],
        'icons': value['icons'] == null ? undefined : ((value['icons'] as Array<any>).map(IconToJSON)),
        'mimeType': value['mimeType'],
        'name': value['name'],
        'size': value['size'],
        'title': value['title'],
        'type': value['type'],
        'uri': value['uri'],
    };
}

