/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One search result.
 * @export
 * @interface SearchResultItem
 */
export interface SearchResultItem {
    /**
     * 
     * @type {string}
     * @memberof SearchResultItem
     */
    date?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResultItem
     */
    snippet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResultItem
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResultItem
     */
    url: string;
}

/**
 * Check if a given object implements the SearchResultItem interface.
 */
export function instanceOfSearchResultItem(value: object): value is SearchResultItem {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function SearchResultItemFromJSON(json: any): SearchResultItem {
    return SearchResultItemFromJSONTyped(json, false);
}

export function SearchResultItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'],
    };
}

export function SearchResultItemToJSON(json: any): SearchResultItem {
    return SearchResultItemToJSONTyped(json, false);
}

export function SearchResultItemToJSONTyped(value?: SearchResultItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'snippet': value['snippet'],
        'title': value['title'],
        'url': value['url'],
    };
}

