/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Text contents of a resource.
 * @export
 * @interface TextResourceContents
 */
export interface TextResourceContents {
    [key: string]: any | any;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TextResourceContents
     */
    meta?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof TextResourceContents
     */
    mimeType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TextResourceContents
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof TextResourceContents
     */
    uri: string;
}

/**
 * Check if a given object implements the TextResourceContents interface.
 */
export function instanceOfTextResourceContents(value: object): value is TextResourceContents {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function TextResourceContentsFromJSON(json: any): TextResourceContents {
    return TextResourceContentsFromJSONTyped(json, false);
}

export function TextResourceContentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextResourceContents {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'meta': json['_meta'] == null ? undefined : json['_meta'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'text': json['text'],
        'uri': json['uri'],
    };
}

export function TextResourceContentsToJSON(json: any): TextResourceContents {
    return TextResourceContentsToJSONTyped(json, false);
}

export function TextResourceContentsToJSONTyped(value?: TextResourceContents | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        '_meta': value['meta'],
        'mimeType': value['mimeType'],
        'text': value['text'],
        'uri': value['uri'],
    };
}

