/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Calls billed on this meter.
 * @export
 * @interface Units1
 */
export interface Units1 {
}

/**
 * Check if a given object implements the Units1 interface.
 */
export function instanceOfUnits1(value: object): value is Units1 {
    return true;
}

export function Units1FromJSON(json: any): Units1 {
    return Units1FromJSONTyped(json, false);
}

export function Units1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Units1 {
    return json;
}

export function Units1ToJSON(json: any): Units1 {
    return Units1ToJSONTyped(json, false);
}

export function Units1ToJSONTyped(value?: Units1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

