/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Tokens billed on this meter.
 * @export
 * @interface Units
 */
export interface Units {
}

/**
 * Check if a given object implements the Units interface.
 */
export function instanceOfUnits(value: object): value is Units {
    return true;
}

export function UnitsFromJSON(json: any): Units {
    return UnitsFromJSONTyped(json, false);
}

export function UnitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Units {
    return json;
}

export function UnitsToJSON(json: any): Units {
    return UnitsToJSONTyped(json, false);
}

export function UnitsToJSONTyped(value?: Units | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

