/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Selection of imported usage rows to delete.
 * @export
 * @interface UsageDeleteRequest
 */
export interface UsageDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    apiKeyId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UsageDeleteRequest
     */
    byFilter?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UsageDeleteRequest
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    endpoint?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UsageDeleteRequest
     */
    ids?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    model?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UsageDeleteRequest
     */
    priced?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    source?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    sourceLabel?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UsageDeleteRequest
     */
    startDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    tool?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsageDeleteRequest
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the UsageDeleteRequest interface.
 */
export function instanceOfUsageDeleteRequest(value: object): value is UsageDeleteRequest {
    return true;
}

export function UsageDeleteRequestFromJSON(json: any): UsageDeleteRequest {
    return UsageDeleteRequestFromJSONTyped(json, false);
}

export function UsageDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeyId': json['api_key_id'] == null ? undefined : json['api_key_id'],
        'byFilter': json['by_filter'] == null ? undefined : json['by_filter'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'ids': json['ids'] == null ? undefined : json['ids'],
        'model': json['model'] == null ? undefined : json['model'],
        'priced': json['priced'] == null ? undefined : json['priced'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceLabel': json['source_label'] == null ? undefined : json['source_label'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'status': json['status'] == null ? undefined : json['status'],
        'tool': json['tool'] == null ? undefined : json['tool'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function UsageDeleteRequestToJSON(json: any): UsageDeleteRequest {
    return UsageDeleteRequestToJSONTyped(json, false);
}

export function UsageDeleteRequestToJSONTyped(value?: UsageDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key_id': value['apiKeyId'],
        'by_filter': value['byFilter'],
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'endpoint': value['endpoint'],
        'ids': value['ids'],
        'model': value['model'],
        'priced': value['priced'],
        'provider': value['provider'],
        'source': value['source'],
        'source_label': value['sourceLabel'],
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'status': value['status'],
        'tool': value['tool'],
        'user_id': value['userId'],
    };
}

