/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserId
 */
export interface UserId {
}

/**
 * Check if a given object implements the UserId interface.
 */
export function instanceOfUserId(value: object): value is UserId {
    return true;
}

export function UserIdFromJSON(json: any): UserId {
    return UserIdFromJSONTyped(json, false);
}

export function UserIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserId {
    return json;
}

export function UserIdToJSON(json: any): UserId {
    return UserIdToJSONTyped(json, false);
}

export function UserIdToJSONTyped(value?: UserId | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

