/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A workspace and the role to grant in it, applied when a member is added.
 * @export
 * @interface WorkspaceAssignmentRequest
 */
export interface WorkspaceAssignmentRequest {
    /**
     * 
     * @type {WorkspaceAssignmentRequestRoleEnum}
     * @memberof WorkspaceAssignmentRequest
     */
    role?: WorkspaceAssignmentRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceAssignmentRequest
     */
    workspaceId: string;
}


/**
 * @export
 */
export const WorkspaceAssignmentRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member',
    Viewer: 'viewer'
} as const;
export type WorkspaceAssignmentRequestRoleEnum = typeof WorkspaceAssignmentRequestRoleEnum[keyof typeof WorkspaceAssignmentRequestRoleEnum];


/**
 * Check if a given object implements the WorkspaceAssignmentRequest interface.
 */
export function instanceOfWorkspaceAssignmentRequest(value: object): value is WorkspaceAssignmentRequest {
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    return true;
}

export function WorkspaceAssignmentRequestFromJSON(json: any): WorkspaceAssignmentRequest {
    return WorkspaceAssignmentRequestFromJSONTyped(json, false);
}

export function WorkspaceAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceAssignmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'workspaceId': json['workspace_id'],
    };
}

export function WorkspaceAssignmentRequestToJSON(json: any): WorkspaceAssignmentRequest {
    return WorkspaceAssignmentRequestToJSONTyped(json, false);
}

export function WorkspaceAssignmentRequestToJSONTyped(value?: WorkspaceAssignmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'workspace_id': value['workspaceId'],
    };
}

