/* tslint:disable */
/* eslint-disable */
/**
 * otari
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * The row furthest through its allowance.
 * @export
 * @interface WorstAllocationResponse
 */
export interface WorstAllocationResponse {
    /**
     * 
     * @type {number}
     * @memberof WorstAllocationResponse
     */
    allocated: number;
    /**
     * 
     * @type {string}
     * @memberof WorstAllocationResponse
     */
    budgetId: string;
    /**
     * The row's own name, or null where nobody gave it one.
     * @type {string}
     * @memberof WorstAllocationResponse
     */
    name: string | null;
    /**
     * The scope's id, so an unnamed ceiling can be named after it.
     * @type {string}
     * @memberof WorstAllocationResponse
     */
    scopeId: string | null;
    /**
     * What a spend ceiling caps (workspace, org_member, api_token, ...); null for a budget.
     * @type {string}
     * @memberof WorstAllocationResponse
     */
    scopeType: string | null;
    /**
     * 
     * @type {number}
     * @memberof WorstAllocationResponse
     */
    spent: number;
}

/**
 * Check if a given object implements the WorstAllocationResponse interface.
 */
export function instanceOfWorstAllocationResponse(value: object): value is WorstAllocationResponse {
    if (!('allocated' in value) || value['allocated'] === undefined) return false;
    if (!('budgetId' in value) || value['budgetId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopeId' in value) || value['scopeId'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('spent' in value) || value['spent'] === undefined) return false;
    return true;
}

export function WorstAllocationResponseFromJSON(json: any): WorstAllocationResponse {
    return WorstAllocationResponseFromJSONTyped(json, false);
}

export function WorstAllocationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorstAllocationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allocated': json['allocated'],
        'budgetId': json['budget_id'],
        'name': json['name'],
        'scopeId': json['scope_id'],
        'scopeType': json['scope_type'],
        'spent': json['spent'],
    };
}

export function WorstAllocationResponseToJSON(json: any): WorstAllocationResponse {
    return WorstAllocationResponseToJSONTyped(json, false);
}

export function WorstAllocationResponseToJSONTyped(value?: WorstAllocationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allocated': value['allocated'],
        'budget_id': value['budgetId'],
        'name': value['name'],
        'scope_id': value['scopeId'],
        'scope_type': value['scopeType'],
        'spent': value['spent'],
    };
}

